from pathlib import Path
from datetime import datetime,timezone
import hashlib,json,re,subprocess
P=Path(__file__).resolve().parent;S=P.parents[1];R=S.parents[4]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def bind(p):return dict(path=p.relative_to(R).as_posix(),sha256=sha(p))
def write(name,v):
 p=P/name;assert not p.exists();p.write_bytes((json.dumps(v,indent=2)+'\n').encode());return p
assert sha(S/'unblock-nine-20260908/selected-interpretations.json')=='cfde240a9dda9a58be99f85369b43e99003b0024c7147a33ffa8b071ca7dcf34'
paths=[R/'lean-toolchain',R/'lake-manifest.json',P/'REVIEW.md',P/'capture-review.py',S/'unblock-nine-20260908/selected-interpretations.json',S/'current-thread-question-provenance-v2-batch10/projection.json',S/'prospective-source-choice-boundaries-batch10-v2.json']
owners=['Source/LeVeque/Chapter01/AcousticsModes.lean','Source/LeVeque/Chapter01/AcousticsRightModeAlgebraic.lean','Source/LeVeque/Chapter01/EigenvaluePropagation.lean','Source/LeVeque/Chapter01/RiemannHyperbolicProblem.lean','Source/LeVeque/Chapter01/RiemannInitialConfiguration.lean','Analysis/PartialDifferentialEquations/LinearAcoustics.lean','Analysis/PartialDifferentialEquations/LinearAdvection.lean','Analysis/PartialDifferentialEquations/Transport/Characteristics.lean','Analysis/PartialDifferentialEquations/Transport/ClassicalCharacteristics.lean','Analysis/PartialDifferentialEquations/ConservationLaws/TravelingWaveCharacterization.lean','Analysis/PartialDifferentialEquations/LinearSystems/EigenbasisCoordinates.lean','Analysis/PartialDifferentialEquations/LinearSystems/CharacteristicPropagation.lean','Analysis/PartialDifferentialEquations/FirstOrderEquation.lean','Analysis/PartialDifferentialEquations/InitialValue/FirstOrderRiemann.lean','Analysis/PartialDifferentialEquations/FiniteVolume/RiemannData.lean','Analysis/PartialDifferentialEquations/Hyperbolicity.lean']
paths += [R/'ComputationalMathematics'/n for n in owners]
frozen=['left-mode-domain-draft/candidate.lean','left-mode-domain-draft/final-receipt.json','left-mode-alternative-evidence/Candidate.lean','left-mode-alternative-evidence/Fixtures.lean.fragment','left-mode-alternative-evidence/PROSPECTIVE-CONTRACT.md','left-mode-alternative-evidence/REVIEW.md','left-mode-alternative-evidence/manifest.json','left-mode-alternative-evidence/final-receipt.json','left-mode-alternative-evidence/native03-final.json','left-mode-alternative-evidence/native03-final.txt','left-mode-alternative-evidence/native03-final-input.lean','prospective-eigen-fv-qualification-review/Checks.lean','prospective-eigen-fv-qualification-review/QUALIFICATION.md','prospective-eigen-fv-qualification-review/native01-exit.json','prospective-eigen-fv-qualification-review/native01-output.txt','prospective-eigen-fv-qualification-review/verification.json','prospective-density-material-riemann-capstones-draft/Capstones.lean','prospective-density-material-riemann-capstones-draft/REVIEW.md','prospective-density-material-riemann-capstones-draft/evidence-manifest.json','prospective-density-material-riemann-capstones-draft/capstones-final-03.receipt.json','prospective-density-material-riemann-capstones-draft/capstones-final-03.native.txt']
paths += [S/n for n in frozen]
ids=['LEV-CH01-ACOUSTICS-LEFT-MODE-CANONICAL-20260908','LEV-CH01-EIGENVALUES-WAVE-SPEEDS-CANONICAL-20260908','LEV-CH01-EIGENVALUES-GENERAL-PROPAGATION-PRODUCTION-20260908','LEV-CH01-RIEMANN-INITIAL-VALUE-DEFINITION-PRODUCTION-20260908','LEV-CH01-RIEMANN-HYPERBOLIC-PROBLEM-DATA-PRODUCTION-20260908']
audits=[]
for task_id in ids:
 d=S/'audits'/task_id;t=json.loads((d/'audit-task.json').read_bytes());v=json.loads((d/'faithfulness/decision.json').read_bytes())
 for n in ['audit-task.json','faithfulness/decision.json','faithfulness/report.md','faithfulness/manifest.json','faithfulness/inputs/source_locator.json']:paths.append(d/n)
 source=R/t['source']['path'];assert sha(source)==t['source']['sha256'];paths.append(source)
 audits.append(dict(task_id=task_id,task=bind(d/'audit-task.json'),target=t['target'],source=t['source'],decision=bind(d/'faithfulness/decision.json'),historical_classification=v['classification'],accepted=v['accepted'],findings=v['findings'],remaining_uncertainties=v['remaining_uncertainties']))
for task,n in [(ids[0],'023'),(ids[0],'024'),(ids[1],'025'),(ids[4],'027')]:paths.append(S/'audits'/task/'faithfulness/orchestration'/('page-'+n+'.png'))
cmd=['rg','-n',r'linearAcousticsLeftInvariant_isLinearAdvectionSolutionAt|travelingWave_isLinearAdvectionSolution_iff|travelingWave_isRectangleConservationLawSolution_iff|constantCoefficientSystem_characteristicPropagation|constantCoefficientSystem_iff_eigenbasisAdvection|isRiemann_characterization|fromEqualStates_not_isJumpRiemann|fromStates_isJumpRiemann|fromStates_isRiemannWithStates','ComputationalMathematics/Analysis/PartialDifferentialEquations','.lake/packages/mathlib/Mathlib','-g','*.lean']
out=P/'reuse-search.txt';assert not out.exists()
with out.open('xb') as f:r=subprocess.run(cmd,cwd=R,stdout=f,stderr=subprocess.STDOUT)
assert r.returncode==0;paths.append(out)
pins={p.relative_to(R).as_posix():sha(p) for p in paths}
selected=json.loads((S/'unblock-nine-20260908/selected-interpretations.json').read_bytes())
report=write('review-before-implementation.json',dict(schema=1,kind='bounded-implementation-review-not-sealed-audit',created_utc=datetime.now(timezone.utc).isoformat(),review=bind(P/'REVIEW.md'),selected_conventions=[x for x in selected['choices'] if x['choice_id'] in ['Q3','Q4','Q9']],authority=selected['authority'],audits=audits,source_renders_viewed=[bind(p) for p in paths if p.suffix=='.png'],reuse_search=dict(command=cmd,exit_code=r.returncode,output=bind(out)),input_files=pins,faithfulness_action='new-audit-required',new_semantic_audit=False,native_run_by_this_review=False,implementation_authorized_by_parent=True,implementation_files=['ComputationalMathematics/Source/LeVeque/Chapter01/AcousticsLeftSolutionDomains.lean','ComputationalMathematics/Source/LeVeque/Chapter01/RiemannProblemDataClassification.lean'],unchanged_target='ComputationalMathematics/Source/LeVeque/Chapter01/EigenvaluePropagation.lean',missing_reusable_producers_identified=[]))
assert all(sha(R/p)==h for p,h in pins.items())
print(json.dumps(dict(review_receipt=bind(report),pins=len(pins))))
