name = "numStability"
version = "0.1.0"
defaultTargets = ["ComputationalMathematics", "NumStability"]
testDriver = "NumStabilityTest"
lintDriver = "batteries/runLinter"
lintDriverArgs = ["ComputationalMathematics"]
weakLeanArgs = ["-j", "1"]

[[lean_lib]]
name = "ComputationalMathematics"

[[lean_lib]]
name = "NumStability"

[[lean_lib]]
name = "NumStabilityTest"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "e8ea1afc32790ce1d4e1a4e45cc412ba9388716b"
