import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Algorithms_LU_BlockLUTable13_1Families
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Higham_Chapter13_Table13_1
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_BlockLU
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_Equation25_Factorization
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_Problem04_ComparisonChains
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_Problem04_DeterminantChainProducts
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_Problem04_GlobalTableauChain
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_Problem04_InverseRatioChain
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_Problem04_LowerComparisonChain
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_Problem04_ProductBounds
import NumStabilityTest.Reorganization.R03.Consumer.NumStability_Source_Higham_Chapter13_Problem04_RecursiveBudgetChains
import NumStabilityTest.Reorganization.R12.Canonical.SourceHighamChapter13Equation23ProductBoundsPointRow
import NumStabilityTest.Reorganization.R12.Canonical.SourceHighamChapter13Equation25BackwardErrorBounds
import NumStabilityTest.Reorganization.R12.Canonical.SourceHighamChapter13Equation25PartitionedComputationImplementation1
import NumStabilityTest.Reorganization.R12.Canonical.SourceHighamChapter13Table01BackwardErrorBoundsEndpoints
import NumStabilityTest.Reorganization.R12.Canonical.SourceHighamChapter13Table01DiagonalDominanceBounds
import NumStabilityTest.Reorganization.R12.Canonical.SourceHighamChapter13Table01ProductTransfersFamilies
import NumStabilityTest.Reorganization.R12.Focused.SourceHighamChapter13Equation23ProductBoundsPointRow
import NumStabilityTest.Reorganization.R12.Focused.SourceHighamChapter13Equation25BackwardErrorBounds
import NumStabilityTest.Reorganization.R12.Focused.SourceHighamChapter13Equation25PartitionedComputationImplementation1
import NumStabilityTest.Reorganization.R12.Focused.SourceHighamChapter13Table01BackwardErrorBoundsEndpoints
import NumStabilityTest.Reorganization.R12.Focused.SourceHighamChapter13Table01DiagonalDominanceBounds
import NumStabilityTest.Reorganization.R12.Focused.SourceHighamChapter13Table01ProductTransfersFamilies
import NumStabilityTest.Reorganization.R12.OldOnly.SourceHighamChapter13Equation23
import NumStabilityTest.Reorganization.R12.OldOnly.SourceHighamChapter13Equation25
import NumStabilityTest.Reorganization.R12.OldOnly.SourceHighamChapter13Table01

/-!
# R12 test aggregate

Imports every R12 reorganization test module. This module declares nothing.
-/
