import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Carrier.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Carrier.BoydLocal
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.BoydDomain
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.BoydLocal
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.PNormGeneral
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.FixedPoints.BoydConcrete
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.FixedPoints.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.FixedPoints.BoydLocal
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.LocalStability.BoydConcrete
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.LocalStability.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.LocalStability.BoydLocal
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.LocalStability.BoydLocalStability
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.RowwiseDomain.Basic
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Scalar.BoydDomain
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Scalar.BoydLocal
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Scalar.BoydRowwise
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.SecondVariation.BoydConcrete
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.SecondVariation.BoydLocal
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Uniqueness.Basic

/-!
# Algorithms.NormEstimation.PNorm.Boyd

Reviewed W10 discovery entry point for the reusable Boyd p-norm family.
-/
