import Mathlib.MeasureTheory.Integral.IntervalIntegral.IntegrationByParts
import Mathlib.Analysis.CStarAlgebra.CStarMatrix
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Order
import Mathlib.Analysis.Matrix.Order
import Mathlib.Data.Matrix.Block
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.BlockDiagonal
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.BlockDiagonalCompression
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPair
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairPinching
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeProjection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeReflection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteDimensional
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteMatrixOrder
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealEmbedding
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealOrder
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ProjectionReflection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.RectangularCompression
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.RectangularMultiplication
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ReflectionAverage
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.StrictPositivity
import ComputationalMathematics.Analysis.FunctionalCalculus.Resolvent.Analyticity
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.BaiDemmelGu.DistanceToInstability
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Kreiss.ResolventBound
import ComputationalMathematics.Analysis.MatrixNorms.Basic
import ComputationalMathematics.Analysis.SingularValues.Basic
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Spijker.ArcLengthPowerBounds.FiniteDimension
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Spijker.ResolventCoefficients.Analytic

/-!
# Analysis.LinearOperators.MatrixPowers.Spijker.KreissBridge (compatibility wrapper)

Import-only historical R07 path. Its declaration block moved to `NumStability.Analysis.LinearOperators.MatrixPowers.Spijker.ArcLengthPowerBounds.FiniteDimension`, `NumStability.Analysis.LinearOperators.MatrixPowers.Spijker.ResolventCoefficients.Analytic`, imported above. The exact C0005 direct import sequence remains available so existing imports preserve their supported public surface. This module declares nothing.
-/
