import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannInformationFluxMethod
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannFieldFluxMethodInformation
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannInformationFluxError
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.Examples.LeftStateInformationFlux

#check NumStability.RiemannInformationFluxMethod
#print axioms NumStability.RiemannInformationFluxMethod
#check NumStability.RiemannInformationFluxMethod.selectedResult
#print axioms NumStability.RiemannInformationFluxMethod.selectedResult
#check NumStability.RiemannInformationFluxMethod.interfaceFlux
#print axioms NumStability.RiemannInformationFluxMethod.interfaceFlux
#check NumStability.RiemannInformationFluxMethod.interface_execution
#print axioms NumStability.RiemannInformationFluxMethod.interface_execution
#check NumStability.RiemannInformationFluxMethod.interfaceFlux_constant
#print axioms NumStability.RiemannInformationFluxMethod.interfaceFlux_constant
#check NumStability.RiemannInformationFluxMethod.ofField
#print axioms NumStability.RiemannInformationFluxMethod.ofField
#check NumStability.RiemannInformationFluxMethod.ofField_solve
#print axioms NumStability.RiemannInformationFluxMethod.ofField_solve
#check NumStability.RiemannInformationFluxMethod.ofField_extract
#print axioms NumStability.RiemannInformationFluxMethod.ofField_extract
#check NumStability.RiemannInformationFluxMethod.ofField_numericalFlux
#print axioms NumStability.RiemannInformationFluxMethod.ofField_numericalFlux
#check NumStability.RiemannInformationFluxMethod.ofField_interfaceFlux
#print axioms NumStability.RiemannInformationFluxMethod.ofField_interfaceFlux
#check NumStability.RiemannInformationFluxMethod.ofField_finite_trace_integrable
#print axioms NumStability.RiemannInformationFluxMethod.ofField_finite_trace_integrable
#check NumStability.RiemannInformationFluxMethod.interface_error_le
#print axioms NumStability.RiemannInformationFluxMethod.interface_error_le
#check NumStability.RiemannInformationFluxMethod.update_error_le
#print axioms NumStability.RiemannInformationFluxMethod.update_error_le
#check NumStability.LeftStateInformationFlux.OrderedResult
#print axioms NumStability.LeftStateInformationFlux.OrderedResult
#check NumStability.LeftStateInformationFlux.method
#print axioms NumStability.LeftStateInformationFlux.method
#check NumStability.LeftStateInformationFlux.selected_pair
#print axioms NumStability.LeftStateInformationFlux.selected_pair
#check NumStability.LeftStateInformationFlux.selected_flux
#print axioms NumStability.LeftStateInformationFlux.selected_flux
#check NumStability.LeftStateInformationFlux.concrete_information_only
#print axioms NumStability.LeftStateInformationFlux.concrete_information_only
#check NumStability.LeftStateInformationFlux.localTrace
#print axioms NumStability.LeftStateInformationFlux.localTrace
#check NumStability.LeftStateInformationFlux.localTrace_integrable
#print axioms NumStability.LeftStateInformationFlux.localTrace_integrable
#check NumStability.LeftStateInformationFlux.extraction_eq_localTrace
#print axioms NumStability.LeftStateInformationFlux.extraction_eq_localTrace
#check NumStability.LeftStateInformationFlux.localTrace_eq_transport_reference
#print axioms NumStability.LeftStateInformationFlux.localTrace_eq_transport_reference
#check NumStability.LeftStateInformationFlux.selected_flux_eq_reference_average
#print axioms NumStability.LeftStateInformationFlux.selected_flux_eq_reference_average
#check NumStability.LeftStateInformationFlux.existing_field_embedding
#print axioms NumStability.LeftStateInformationFlux.existing_field_embedding
