import ComputationalMathematics.Source.LeVeque.Chapter01

#check NumStability.leveque01_acousticsLeftSolutionDomains
#print axioms NumStability.leveque01_acousticsLeftSolutionDomains
#check NumStability.leveque01_acousticsMatrixEigenvalues
#print axioms NumStability.leveque01_acousticsMatrixEigenvalues
#check NumStability.leveque01_acousticsRightMode_of_pos_ratio
#print axioms NumStability.leveque01_acousticsRightMode_of_pos_ratio
#check NumStability.leveque01_acousticsTwoWaveDecomposition
#print axioms NumStability.leveque01_acousticsTwoWaveDecomposition
#check NumStability.leveque01_acoustics_hasConservationForm
#print axioms NumStability.leveque01_acoustics_hasConservationForm
#check NumStability.leveque01_advectionLinearFlux_fromMassConservation
#print axioms NumStability.leveque01_advectionLinearFlux_fromMassConservation
#check NumStability.leveque01_advectionWaveIdentity
#print axioms NumStability.leveque01_advectionWaveIdentity
#check NumStability.leveque01_coordinateDirectionalMethods_sourceContract
#print axioms NumStability.leveque01_coordinateDirectionalMethods_sourceContract
#check NumStability.leveque01_discontinuity_generalIntegralComparison
#print axioms NumStability.leveque01_discontinuity_generalIntegralComparison
#check NumStability.leveque01_eigenvalues_completeWavePropagation
#print axioms NumStability.leveque01_eigenvalues_completeWavePropagation
#check NumStability.leveque01_equation01_constantLinearSystemAt_iff
#print axioms NumStability.leveque01_equation01_constantLinearSystemAt_iff
#check NumStability.leveque01_equation02_uniformTransportDomains
#print axioms NumStability.leveque01_equation02_uniformTransportDomains
#check NumStability.leveque01_equation03_solutionDomains
#print axioms NumStability.leveque01_equation03_solutionDomains
#check NumStability.leveque01_equation04_acousticOneWayModel
#print axioms NumStability.leveque01_equation04_acousticOneWayModel
#check NumStability.leveque01_equation05_linearAcousticsAt_iff
#print axioms NumStability.leveque01_equation05_linearAcousticsAt_iff
#check NumStability.leveque01_equation06_acousticsMatrixForm
#print axioms NumStability.leveque01_equation06_acousticsMatrixForm
#check NumStability.leveque01_equation07_pressureWave
#print axioms NumStability.leveque01_equation07_pressureWave
#check NumStability.leveque01_equation07_secondOrderHyperbolic
#print axioms NumStability.leveque01_equation07_secondOrderHyperbolic
#check NumStability.leveque01_equation08_conservationLawAt_iff
#print axioms NumStability.leveque01_equation08_conservationLawAt_iff
#check NumStability.leveque01_equation09_quasilinearForm
#print axioms NumStability.leveque01_equation09_quasilinearForm
#check NumStability.leveque01_equation10_rectangleConservation_iff_integrated_and_ae_rate
#print axioms NumStability.leveque01_equation10_rectangleConservation_iff_integrated_and_ae_rate
#check NumStability.leveque01_equation11_characterization
#print axioms NumStability.leveque01_equation11_characterization
#check NumStability.leveque01_exists_hyperbolic_variableCoefficient_without_localFlux
#print axioms NumStability.leveque01_exists_hyperbolic_variableCoefficient_without_localFlux
#check NumStability.leveque01_finiteVolumeCellAverage_spec
#print axioms NumStability.leveque01_finiteVolumeCellAverage_spec
#check NumStability.leveque01_finiteVolumeLocalFluxUpdate_sourceContract
#print axioms NumStability.leveque01_finiteVolumeLocalFluxUpdate_sourceContract
#check NumStability.leveque01_fluxJacobian_hyperbolicity_iff
#print axioms NumStability.leveque01_fluxJacobian_hyperbolicity_iff
#check NumStability.leveque01_hyperbolicMatrixDefinition
#print axioms NumStability.leveque01_hyperbolicMatrixDefinition
#check NumStability.leveque01_hyperbolicMatrix_uniqueEigenbasisDecomposition
#print axioms NumStability.leveque01_hyperbolicMatrix_uniqueEigenbasisDecomposition
#check NumStability.leveque01_hyperbolicSystem_scalarWaveDecomposition
#print axioms NumStability.leveque01_hyperbolicSystem_scalarWaveDecomposition
#check NumStability.leveque01_integralLaw_impliesDifferentialLaw_of_smooth
#print axioms NumStability.leveque01_integralLaw_impliesDifferentialLaw_of_smooth
#check NumStability.leveque01_linearFlux_specializesEquation01
#print axioms NumStability.leveque01_linearFlux_specializesEquation01
#check NumStability.leveque01_linearRiemann_eigensolution
#print axioms NumStability.leveque01_linearRiemann_eigensolution
#check NumStability.leveque01_localRiemannInformationInterface_sourceContract
#print axioms NumStability.leveque01_localRiemannInformationInterface_sourceContract
#check NumStability.leveque01_materialCellVolumeAveraging
#print axioms NumStability.leveque01_materialCellVolumeAveraging
#check NumStability.leveque01_materialInterfaceLocalRiemannData
#print axioms NumStability.leveque01_materialInterfaceLocalRiemannData
#check NumStability.leveque01_nonlinear_shock_formation
#print axioms NumStability.leveque01_nonlinear_shock_formation
#check NumStability.leveque01_oneStepMethod_iff_attainableCurrentDataMap
#print axioms NumStability.leveque01_oneStepMethod_iff_attainableCurrentDataMap
#check NumStability.leveque01_riemannProblemDataClassification
#print axioms NumStability.leveque01_riemannProblemDataClassification
#check NumStability.leveque01_riemannRayZeroValue_iff
#print axioms NumStability.leveque01_riemannRayZeroValue_iff
#check NumStability.leveque01_scalarEquation_isHyperbolic
#print axioms NumStability.leveque01_scalarEquation_isHyperbolic
#check NumStability.leveque01_sourceTermsRectangleBalance
#print axioms NumStability.leveque01_sourceTermsRectangleBalance
