import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannInformationCoordinateUpdate
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannInformationCoordinateSweep
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.CartesianGridGeometry
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.CartesianCoordinateUpdate
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.Examples.LeftStateCoordinateSweep

#check NumStability.RiemannInformationCoordinate.FaceAdmitted
#print axioms NumStability.RiemannInformationCoordinate.FaceAdmitted
#check NumStability.RiemannInformationCoordinate.StageAdmitted
#print axioms NumStability.RiemannInformationCoordinate.StageAdmitted
#check NumStability.RiemannInformationCoordinate.selectedFaceFlux
#print axioms NumStability.RiemannInformationCoordinate.selectedFaceFlux
#check NumStability.RiemannInformationCoordinate.guardedRule
#print axioms NumStability.RiemannInformationCoordinate.guardedRule
#check NumStability.RiemannInformationCoordinate.normalFaceFlux_of_admitted
#print axioms NumStability.RiemannInformationCoordinate.normalFaceFlux_of_admitted
#check NumStability.RiemannInformationCoordinate.admitted_face_observation
#print axioms NumStability.RiemannInformationCoordinate.admitted_face_observation
#check NumStability.RiemannInformationCoordinate.normalFaceFlux_fallback_independent
#print axioms NumStability.RiemannInformationCoordinate.normalFaceFlux_fallback_independent
#check NumStability.RiemannInformationCoordinate.advance_fallback_independent
#print axioms NumStability.RiemannInformationCoordinate.advance_fallback_independent
#check NumStability.RiemannInformationCoordinate.admitted_cell_mass_balance
#print axioms NumStability.RiemannInformationCoordinate.admitted_cell_mass_balance
#check NumStability.RiemannInformationCoordinate.admitted_finite_line_mass_balance
#print axioms NumStability.RiemannInformationCoordinate.admitted_finite_line_mass_balance
#check NumStability.RiemannInformationCoordinate.SweepAdmitted
#print axioms NumStability.RiemannInformationCoordinate.SweepAdmitted
#check NumStability.RiemannInformationCoordinate.sweepAdmitted_fallback_independent
#print axioms NumStability.RiemannInformationCoordinate.sweepAdmitted_fallback_independent
#check NumStability.RiemannInformationCoordinate.sweep_fallback_independent
#print axioms NumStability.RiemannInformationCoordinate.sweep_fallback_independent
#check NumStability.RiemannInformationCoordinate.admission_at_prefix
#print axioms NumStability.RiemannInformationCoordinate.admission_at_prefix
#check NumStability.RiemannInformationCoordinate.executed_face_uses_selected_solve
#print axioms NumStability.RiemannInformationCoordinate.executed_face_uses_selected_solve
#check NumStability.RiemannInformationCoordinate.admitted_two_stage_balance
#print axioms NumStability.RiemannInformationCoordinate.admitted_two_stage_balance
#check NumStability.CartesianGrid.cellBox
#print axioms NumStability.CartesianGrid.cellBox
#check NumStability.CartesianGrid.cellVolume
#print axioms NumStability.CartesianGrid.cellVolume
#check NumStability.CartesianGrid.faceArea
#print axioms NumStability.CartesianGrid.faceArea
#check NumStability.CartesianGrid.cellVolume_pos
#print axioms NumStability.CartesianGrid.cellVolume_pos
#check NumStability.CartesianGrid.cellVolume_eq_width_mul_area
#print axioms NumStability.CartesianGrid.cellVolume_eq_width_mul_area
#check NumStability.CartesianGrid.cellBox_volume
#print axioms NumStability.CartesianGrid.cellBox_volume
#check NumStability.CartesianGrid.faceArea_update
#print axioms NumStability.CartesianGrid.faceArea_update
#check NumStability.CartesianGrid.tangentialFaceBox
#print axioms NumStability.CartesianGrid.tangentialFaceBox
#check NumStability.CartesianGrid.tangentialFaceBox_volume
#print axioms NumStability.CartesianGrid.tangentialFaceBox_volume
#check NumStability.CartesianGrid.tangentialFaceBox_update
#print axioms NumStability.CartesianGrid.tangentialFaceBox_update
#check NumStability.CartesianGrid.facePoint
#print axioms NumStability.CartesianGrid.facePoint
#check NumStability.CartesianGrid.facePoint_normal
#print axioms NumStability.CartesianGrid.facePoint_normal
#check NumStability.CartesianGrid.facePoint_transverse
#print axioms NumStability.CartesianGrid.facePoint_transverse
#check NumStability.CartesianGrid.shared_face_position
#print axioms NumStability.CartesianGrid.shared_face_position
#check NumStability.CartesianCoordinateUpdate.areaWeightedRule
#print axioms NumStability.CartesianCoordinateUpdate.areaWeightedRule
#check NumStability.CartesianCoordinateUpdate.cartesian_full_line_update
#print axioms NumStability.CartesianCoordinateUpdate.cartesian_full_line_update
#check NumStability.CartesianCoordinateUpdate.line_admission
#print axioms NumStability.CartesianCoordinateUpdate.line_admission
#check NumStability.CartesianCoordinateUpdate.selectedFaceFlux_on_line
#print axioms NumStability.CartesianCoordinateUpdate.selectedFaceFlux_on_line
#check NumStability.CartesianCoordinateUpdate.guardedRule_eq_areaWeightedRule
#print axioms NumStability.CartesianCoordinateUpdate.guardedRule_eq_areaWeightedRule
#check NumStability.CartesianCoordinateUpdate.cartesian_line_update
#print axioms NumStability.CartesianCoordinateUpdate.cartesian_line_update
#check NumStability.CartesianCoordinateUpdate.cartesian_measured_balance
#print axioms NumStability.CartesianCoordinateUpdate.cartesian_measured_balance
#check NumStability.LeftStateCoordinateSweep.left_rule
#print axioms NumStability.LeftStateCoordinateSweep.left_rule
#check NumStability.LeftStateCoordinateSweep.left_sweep_admitted
#print axioms NumStability.LeftStateCoordinateSweep.left_sweep_admitted
#check NumStability.LeftStateCoordinateSweep.left_unit_update
#print axioms NumStability.LeftStateCoordinateSweep.left_unit_update
#check NumStability.LeftStateCoordinateSweep.left_two_stage_nonvacuity
#print axioms NumStability.LeftStateCoordinateSweep.left_two_stage_nonvacuity
