import ComputationalMathematics.Analysis.SpecialFunctions.Huber
import ComputationalMathematics.Analysis.Calculus.Piecewise
import ComputationalMathematics.Analysis.Calculus.Deriv.Abs
import ComputationalMathematics.MeasureTheory.Integral.IntervalIntegral.Piecewise
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.HuberShock.Basic
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.HuberShock.Potential
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.HuberShock.Regularity
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.HuberShock.Jump
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.HuberShock.Conservation
import ComputationalMathematics.Source.LeVeque.Chapter01.NonlinearShockFormation

#check NumStability.huberSlope
#print axioms NumStability.huberSlope
#check NumStability.huberFlux
#print axioms NumStability.huberFlux
#check NumStability.huberSlope_continuous
#print axioms NumStability.huberSlope_continuous
#check NumStability.huberSlope_of_abs_le
#print axioms NumStability.huberSlope_of_abs_le
#check NumStability.huberSlope_of_ge
#print axioms NumStability.huberSlope_of_ge
#check NumStability.huberSlope_of_le
#print axioms NumStability.huberSlope_of_le
#check NumStability.hasDerivAt_huberFlux
#print axioms NumStability.hasDerivAt_huberFlux
#check NumStability.huberFlux_contDiff_one
#print axioms NumStability.huberFlux_contDiff_one
#check NumStability.huberFlux_of_abs_le
#print axioms NumStability.huberFlux_of_abs_le
#check NumStability.huberFlux_of_ge
#print axioms NumStability.huberFlux_of_ge
#check NumStability.huberFlux_of_le
#print axioms NumStability.huberFlux_of_le
#check NumStability.huberFlux_formula
#print axioms NumStability.huberFlux_formula
#check NumStability.huberFlux_not_linear
#print axioms NumStability.huberFlux_not_linear
#check NumStability.huberFlux_convex
#print axioms NumStability.huberFlux_convex
#check NumStability.huberFlux_not_affine
#print axioms NumStability.huberFlux_not_affine
#check NumStability.hasDerivWithinAt_if_lt_right
#print axioms NumStability.hasDerivWithinAt_if_lt_right
#check NumStability.hasDerivAt_if_of_eq
#print axioms NumStability.hasDerivAt_if_of_eq
#check NumStability.continuous_if_lt_of_closed
#print axioms NumStability.continuous_if_lt_of_closed
#check NumStability.hasDerivWithinAt_abs_right
#print axioms NumStability.hasDerivWithinAt_abs_right
#check NumStability.intervalIntegrable_piecewise
#print axioms NumStability.intervalIntegrable_piecewise
#check NumStability.HuberShock.centralPotential
#print axioms NumStability.HuberShock.centralPotential
#check NumStability.HuberShock.outerPotential
#print axioms NumStability.HuberShock.outerPotential
#check NumStability.HuberShock.outerState
#print axioms NumStability.HuberShock.outerState
#check NumStability.HuberShock.shockPotential
#print axioms NumStability.HuberShock.shockPotential
#check NumStability.HuberShock.shockState
#print axioms NumStability.HuberShock.shockState
#check NumStability.HuberShock.shockState_initial
#print axioms NumStability.HuberShock.shockState_initial
#check NumStability.HuberShock.shockState_initial_smooth
#print axioms NumStability.HuberShock.shockState_initial_smooth
#check NumStability.HuberShock.shockState_after
#print axioms NumStability.HuberShock.shockState_after
#check NumStability.HuberShock.central_flux
#print axioms NumStability.HuberShock.central_flux
#check NumStability.HuberShock.outer_flux
#print axioms NumStability.HuberShock.outer_flux
#check NumStability.HuberShock.potential_match
#print axioms NumStability.HuberShock.potential_match
#check NumStability.HuberShock.central_outer_state_match
#print axioms NumStability.HuberShock.central_outer_state_match
#check NumStability.HuberShock.centralPotential_space_deriv
#print axioms NumStability.HuberShock.centralPotential_space_deriv
#check NumStability.HuberShock.centralPotential_time_deriv
#print axioms NumStability.HuberShock.centralPotential_time_deriv
#check NumStability.HuberShock.outerPotential_time_deriv
#print axioms NumStability.HuberShock.outerPotential_time_deriv
#check NumStability.HuberShock.outerPotential_space_right_deriv
#print axioms NumStability.HuberShock.outerPotential_space_right_deriv
#check NumStability.HuberShock.outerPotential_space_deriv
#print axioms NumStability.HuberShock.outerPotential_space_deriv
#check NumStability.HuberShock.centralPotential_time_continuousOn
#print axioms NumStability.HuberShock.centralPotential_time_continuousOn
#check NumStability.HuberShock.shockPotential_time_continuous
#print axioms NumStability.HuberShock.shockPotential_time_continuous
#check NumStability.HuberShock.shockPotential_time_right_deriv
#print axioms NumStability.HuberShock.shockPotential_time_right_deriv
#check NumStability.HuberShock.shockPotential_space_continuous
#print axioms NumStability.HuberShock.shockPotential_space_continuous
#check NumStability.HuberShock.outerState_space_continuousAt
#print axioms NumStability.HuberShock.outerState_space_continuousAt
#check NumStability.HuberShock.shockState_continuous_before
#print axioms NumStability.HuberShock.shockState_continuous_before
#check NumStability.HuberShock.shockPotential_space_right_deriv
#print axioms NumStability.HuberShock.shockPotential_space_right_deriv
#check NumStability.HuberShock.stationary_shock_flux_and_speeds
#print axioms NumStability.HuberShock.stationary_shock_flux_and_speeds
#check NumStability.HuberShock.shockState_jump_traces
#print axioms NumStability.HuberShock.shockState_jump_traces
#check NumStability.HuberShock.shockState_not_continuous_after
#print axioms NumStability.HuberShock.shockState_not_continuous_after
#check NumStability.HuberShock.stationary_shock_oleinik
#print axioms NumStability.HuberShock.stationary_shock_oleinik
#check NumStability.HuberShock.shockState_space_intervalIntegrable
#print axioms NumStability.HuberShock.shockState_space_intervalIntegrable
#check NumStability.HuberShock.clippedCentralState_continuous
#print axioms NumStability.HuberShock.clippedCentralState_continuous
#check NumStability.HuberShock.shockState_flux_time_intervalIntegrable
#print axioms NumStability.HuberShock.shockState_flux_time_intervalIntegrable
#check NumStability.HuberShock.shockState_mass_potential
#print axioms NumStability.HuberShock.shockState_mass_potential
#check NumStability.HuberShock.shockState_flux_potential
#print axioms NumStability.HuberShock.shockState_flux_potential
#check NumStability.HuberShock.shockState_rectangle_balance
#print axioms NumStability.HuberShock.shockState_rectangle_balance
#check NumStability.HuberShock.shockState_isRectangleConservationLawSolution
#print axioms NumStability.HuberShock.shockState_isRectangleConservationLawSolution
#check NumStability.leveque01_nonlinear_shock_formation
#print axioms NumStability.leveque01_nonlinear_shock_formation
