import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.DiagonalDominance
import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.FinalizedRunFamilies.ResidualAndForwardEnvelopes
import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.PrintedTraceFamilies.ResidualAndForwardEndpoints
import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.RowDominantCertificates.CumulativeProductBounds
import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.WeakDominanceFamilies.ResidualAndForwardBounds

/-!
# NumStability.Source.Higham.Chapter14.Corollary07

Declaration-free W08 discovery aggregate.
-/
