from pathlib import Path
import hashlib,json,re
F=Path(__file__).resolve().parent;D=F.parent;S=D.parent;R=S.parents[3]
raw=lambda p:Path('\\\\?\\'+str(p.resolve())).read_bytes()
ref=lambda p:{'path':p.resolve().as_posix(),'sha256':hashlib.sha256(raw(p)).hexdigest()}
read=lambda p:json.loads(raw(p))
data=read(F/'report-data.json');extra=[]
def pin(p):v=ref(p);extra.append(v);return v
def link(v,label=None):return f"[{label or Path(v['path']).name}](<{v['path']}>)"
PDE='ComputationalMathematics/Analysis/PartialDifferentialEquations/'
plans={
'LEV-CH01-ACOUSTICS-LEFT-MODE':([('linearAcousticsLeftInvariant_isLinearAdvectionSolutionAt',PDE+'LinearAcoustics.lean'),('travelingWave_isLinearAdvectionSolution_iff',PDE+'Transport/Characteristics.lean'),('travelingWave_isRectangleConservationLawSolution_iff',PDE+'ConservationLaws/TravelingWaveCharacterization.lean')],['travelingWave','left invariant','Differentiable','IntervalIntegrable'],'The old locally differentiable-profile branch did not expose the complete chosen domain split. The wrapper composes the existing invariant and two iff producers; it does not duplicate generic transport theory.',[D/'linear-review/REVIEW.md',D/'linear-review/reuse-search.txt']),
'LEV-CH01-EIGENVALUES-WAVE-SPEEDS':([('constantCoefficientSystem_iff_eigenbasisAdvection',PDE+'LinearSystems/EigenbasisCoordinates.lean'),('constantCoefficientSystem_characteristicPropagation',PDE+'LinearSystems/CharacteristicPropagation.lean')],['complete eigenbasis','characteristicPropagation','MeanValue','Differentiable'],'A mode ansatz alone did not cover propagation of an arbitrary supplied classical solution. The accepted target retains full basis/nonzero eigenvectors, PDE equivalence and joint-differentiability propagation/reconstruction; the existing canonical wrapper was reused as a target under Q4.',[D/'linear-review/REVIEW.md',S/'general-propagation-discontinuity-production-inputs.json']),
'LEV-CH01-FINITE-VOLUME-FLUX-UPDATE':([('finiteVolumeLocalCell_error_contract',PDE+'FiniteVolume/LocalCellErrorBounds.lean')],['finiteVolumeCellAverageUpdate','LocalCellErrorBounds','norm_add_le','oneDimensionalCellAverage'],'A raw conservative update lacked physical error linkage; a global all-time/lattice requirement was unnecessary. The selected local cell/face contract reuses normalized integral and weighted error algebra. Later evidence-only successors resolved actual measure/integral/norm instances without replacing proofs.',[S/'finite-volume-flux-error-estimate/source-and-reuse-review.md',D/'riemann-routine-production/REVIEW.md']),
'LEV-CH01-HETEROGENEOUS-CELL-AVERAGING':([('existsUnique_cellVolumeAssignment',PDE+'FiniteVolume/CellVolumeAverage.lean'),('cellVolumeAverage_congr',PDE+'FiniteVolume/CellVolumeAverage.lean'),('cellVolumeAverage_const',PDE+'FiniteVolume/CellVolumeAverage.lean')],['cellVolumeAverage','setAverage_eq','average_congr','setAverage_const','Real.volume_Ioc'],'The old hdifferentCellAverages restriction was removed; a generic local/constant rule did not specify the selected normalized-volume operator. Mathlib average and interval integral producers are reused, allowing both equal and different resulting means.',[S/'heterogeneous-volume-average-draft/REVIEW.md',S/'heterogeneous-volume-average-draft/research.json']),
'LEV-CH01-NONCONSERVATION-SOURCE-TERMS':([('integrated_source_eq_mass_defect',PDE+'ConservationLaws/RectangleBalance.lean'),('conservation_iff_source_integrals_zero',PDE+'ConservationLaws/RectangleBalance.lean'),('not_conservation_iff_exists_nonzero_source_integral',PDE+'ConservationLaws/RectangleBalance.lean'),('hasDerivAt_mass_ae',PDE+'ConservationLaws/RectangleBalanceTemporalDerivative.lean')],['RectangleBalance','IsBalanceLawSolution','nonconservation_requires','intervalIntegral.integral_add','ae_hasDerivAt_intervalIntegral_pi'],'The classical residual producer required spatial differentiability and did not cover jumps. The new rectangle source law reuses homogeneous conservation and interval-integral algebra, with signed production and the separately refined iterated slice conditions; no pointwise source value substitutes for integrated production.',[S/'nonconservation-integral-source-draft/reuse-search.json',D/'riemann-definition-repair/q6-interpretation-refinement.json']),
'LEV-CH01-MATERIAL-INTERFACE-RIEMANN-DATA':([('hasJumpAt_and_iff_product_traces','ComputationalMathematics/Topology/Order/Jump.lean'),('hasJumpAt',PDE+'InitialValue/RiemannJump.lean')],['MaterialInterface','JumpAt','RiemannData','tendsto_nhds_unique','Filter.Tendsto.prodMk_nhds'],'Paired half-line constancy alone allowed no actual jump, and a product inequality alone could leave one component constant. The selected wrapper keeps both component inequalities, local material traces and strict state half-lines. Limit uniqueness/product topology are reused.',[S/'material-interface-general-draft/source-and-reuse-review.md']),
'LEV-CH01-RIEMANN-INITIAL-VALUE-DEFINITION':([('isRiemann_characterization',PDE+'InitialValue/FirstOrderRiemann.lean'),('fromStates_isRiemannWithStates',PDE+'InitialValue/FirstOrderRiemann.lean'),('fromEqualStates_not_isJumpRiemann',PDE+'InitialValue/FirstOrderRiemann.lean')],['OneDimensionalHyperbolicConservationLaw','HyperbolicRiemannProblem','FirstOrderEquation','IsHyperbolicFluxOn'],'An arbitrary equation predicate did not encode hyperbolicity; conservation laws alone would restrict the general equation role. A genuine first-order principal/residual model supplies problem-data classification, with explicit Q9 domain/forcing/global-coordinate refinement. Solver existence and uniqueness are not added.',[S/'riemann-initial-value-hyperbolic-draft/reuse-search.json',D/'riemann-definition-repair/interpretation-refinement.json']),
'LEV-CH01-DIMENSIONAL-SPLITTING':([('coordinate_highResolution_specification',PDE+'FiniteVolume/HighResolutionCoordinateSweep.lean'),('family_quality',PDE+'FiniteVolume/Examples/HighResolutionAdvectionLine.lean'),('execution_error_le_upto','ComputationalMathematics/Analysis/Normed/Group/SequentialError.lean')],['CoordinateLineBalance','orderedOperatorSweep','ParametricIntervalIntegral','integral_hasDerivAt_right','finiteVolumeCellAverageUpdate'],'Arbitrary constant-preserving or arbitrary line maps, endpoint-only balance and unrelated geometry were rejected. The fresh candidate composes actual refining line quality, all-subinterval references, same-data Cartesian measures and finite successive execution. It reuses canonical updates/integration/characteristics; no duplicate average or general reconstruction algorithm is introduced.',[D/'directional-high-resolution-production/REVIEW.md',D/'dim-local-characteristic-witness/reuse-searches.json',D/'dim-quality-family-witness/REVIEW.md']),
'LEV-CH01-RIEMANN-INTERFACE-FLUX':([('Routine',PDE+'FiniteVolume/LocalRiemannRoutine.lean'),('finiteVolumeLocalCell_error_contract',PDE+'FiniteVolume/LocalCellErrorBounds.lean')],['structure .*Routine','Method.consistent','norm_sub_le','selected flux','Reference'],'Full-field requirements and exact equal-state consistency narrowed the source routine role. Removing them alone left no mandatory exact-or-approximate solving relation. A supplied per-admitted-problem physical reference and certified numerical-flux error is now being developed; it must preserve information-only output and nonzero error. No accepted target is claimed.',[D/'riemann-routine-production/REVIEW.md'])}
mapping=[]
for row in data['nine_rows']:
    producers,terms,rationale,evidence=plans[row['id']];out=[]
    for name,path in producers:
        p=R/path
        if p.exists() and name in raw(p).decode():out.append({'name_fragment':name,'owner':pin(p),'selection_basis':'Observed exact source wrapper or reviewed generic producer; no new native declaration check by report task.'})
        else:out.append({'name_fragment':name,'owner_path':path,'status':'Pending precise owner resolution; not counted as a selected producer.'})
    refs=[]
    for p in evidence:
        if p.exists():refs.append(pin(p))
        else:refs.append({'path':p.as_posix(),'status':'Referenced navigation file unavailable; remaining exact evidence cited separately.'})
    mapping.append({'row':row['id'],'gate_status':row['status'],'target':row.get('target'),'producer_candidates':out,'recorded_search_terms':terms,'rejection_and_duplicate_avoidance':rationale,'evidence':refs})
with (F/'producer-reuse-map.json').open('x',encoding='utf-8',newline='\n') as f:json.dump(mapping,f,indent=2);f.write('\n')
snapshot_refs=[]
for scope,record in data['ledgers'].items():
    for name in ('issues.md','limitations.md','inconsistencies.md','tracker.json'):
        p=Path(record[name]['path']);b=raw(p)
        if hashlib.sha256(b).hexdigest()==record[name]['sha256']:
            out=F/(scope+'-'+name+'.snapshot.txt');out.write_bytes(b);snapshot_refs.append(pin(out))
pending=[]
dim=S/'audits/LEV-CH01-COORDINATE-HIGH-RESOLUTION-METHODS-PRODUCTION-20260908/audit-task.json'
task=read(dim);pending.append({'row':'LEV-CH01-DIMENSIONAL-SPLITTING','task':pin(dim),'target':{**task['target'],'file':pin(R/task['target']['path'])},'status':'Prepared/launched; final accepted decision not available in this captured report.','decision_available_at_capture':Path('\\\\?\\'+str((dim.parent/'faithfulness/decision.json').resolve())).exists(),'native':pin(D/'directional-high-resolution-production/final-receipt.json')})
pending.append({'row':'LEV-CH01-RIEMANN-INTERFACE-FLUX','status':'Substantive certified solving-linkage repair in D/riemann-certified-draft; no frozen successor acceptance or selected gate declaration at capture.','historical_decision':pin(S/'audits/LEV-CH01-LOCAL-RIEMANN-ROUTINE-INTERFACE-PRODUCTION-20260908/faithfulness/decision.json')})
obligation_refs=[pin(D/'linear-review/pass-checkpoint-review/REVIEW.md'),pin(D/'reconciliation-helpers/REVIEW.md'),pin(D/'reconciliation-concept-mapping/REVIEW.md'),pin(D/'final-candidate-epoch-preparation/REVIEW.md')]
focus=pin(S/'unblock-nine-high-resolution-focused-build-exit.json');focus_obj=read(Path(focus['path']));assert focus_obj['exit_code']==0
gateout=raw(F/'gate-check-output.txt').decode();defects=[l.strip() for l in gateout.splitlines() if 'DEFECT ' in l]
text='''**CURRENT REVIEW DRAFT — root review required. This is not a final completion, integration, or publication assertion.**

The active goal is “I want you to unblock all nine of them.” The current gate records **7 of those 9 closed**, and **39 of 41 Chapter 1 formalizable objects (95.12%)**: 22 PROVED, 17 REUSED, 2 IN_PROGRESS. The complete inventory has 57 rows, 16 SKIPPED and 0 DEFERRED; no HARD_BLOCKED or dependency-blocked row remains.

The fresh read-only released checker returned **exit 1: stored ACTIVE, derived FAIL**. Source/tree and row bindings are stale after additive production/organization changes, and all eight global evidence categories are OPEN. The recorded accepted decisions remain real historical semantic evidence; this snapshot does not pretend that final current-tree closure has passed. Root must rebind and validate them after the final source freeze.

'''+f"Exact snapshot: {link(data['gate_snapshot'])}; actual command/output: {link(data['gate_check'])}, {link(pin(F/'gate-check-output.txt'))}. Command did not include `--require-pass`.\n\n"
text+='| Original remaining row | Current status | Exact recorded target | Accepted decision SHA256 |\n|---|---|---|---|\n'
for row in data['nine_rows']:
    target='; '.join(row.get('lean_declarations') or []) or 'No selected gate declaration; work in progress'
    decision=(link(row['decision'],row['decision']['sha256']) if row.get('decision') else 'None')
    text+=f"| {row['id']} | {row['status']} | `{target}` | {decision} |\n"
text+='\nAll seven new closures are **faithful-equivalent under their recorded interpretations**, not unqualified assertions that the printed text states every selected analytic/model premise. Q3/Q4/Q5/Q6/Q7/Q8/Q9/Q10 are coordinator selections under the user’s goal; Q6 and Q9 have separate immutable refinements. The high-resolution convention is a later literal user adoption. Original PDF wording, ambiguities, stronger/scoped historical targets and nonaccepted audits remain unchanged. The full current accepted set has '+str(data['classifications'])+'. The 28 completed decisions in the explicitly selected repair families, including failed predecessors, are enumerated with exact hashes in report-data.json; that is a scoped history list, not a claim to exhaust every audit in the session.\n\n'
text+='**Canonical placement and reuse.** The exact source-wrapper/producer paths and hashes, search terms, rejected candidates and duplication-avoidance rationale are in '+link(pin(F/'producer-reuse-map.json'))+'. The principal decisions are:\n\n'
for item in mapping:text+=f"- **{item['row'].replace('LEV-CH01-','')}**: {item['rejection_and_duplicate_avoidance']}\n"
text+='\nThe recorded Mathlib searches reuse interval-integral algebra/normalization, limit uniqueness/product topology, derivatives under parameter integrals, norm inequalities and basis/characteristic APIs. Naming/search misses are not claims of global semantic absence. Reused generic mathematics and new source wrappers are not double-counted as separate source closures. The normalized average and local conservation predicates have one canonical owner; the generic sequential-error leaf is outside finite volume.\n\n'
text+='**Actual identity pins.**\n\n| Input | SHA256 |\n|---|---|\n'
for key in ('user_attachment','source','profile','module_audit','unit_index','release','lean_toolchain','lake_manifest','audit_kit_version','selection','high_resolution_user_receipt'):
    v=data['identities'][key];text+=f"| {link(v,key)} | `{v['sha256']}` |\n"
text+=f"\nLean is `{data['lean_version']}`; Mathlib revision is `{data['mathlib']['rev']}`. Release metadata names workflow5.0.1 and its scoped operational maintenance classification; a release file hash is not a new semantic certification. The profile/source/module records are the selected package’s actual bytes.\n\n"
org=data['organization'];text+='**Current organization and native evidence.** '+link(org['receipt'])+f" records {org['counts']['production_modules']} modules: "+', '.join(f"{v} {k}" for k,v in org['counts']['by_role'].items())+f"; {org['counts']['exact_rules']} exact and {org['counts']['prefix_rules']} prefix rules. Its actual tier validation failure list is empty, with zero absent exact-rule targets; one prefix currently decides no module. This is the latest placement census, not the final full layout/duplicate/hygiene scan. The stored gate’s organization counters are zero, but the global organization evidence remains OPEN.\n\n"
text+=f"The actual Chapter01 focused build passed: `{focus_obj['command']}`, exit0, {focus_obj['elapsed_ms']} ms; {link(focus)}. The new DIM placement separately has 16 owners/150 authored declarations, 149 transported native type comparisons, 25 nominal bridges and the complete source-level joint application. {link(pin(D/'directional-high-resolution-production/final-receipt.json'))}. All its native axioms are limited to propext/Classical.choice/Quot.sound or none. The additive expression union is **1,419 constants /167 owners**; {link(data['fingerprints']['receipt'])}. Counts include eligible generated constants and are not source-object counts. Normalization is alpha-canonical structure, not full definitional normal forms. Preserve the gzip archive and exclude the large raw .jsonl from staging.\n\n"
text+='**Remaining local work and final obligations.**\n\n'
text+='1. Finish the fresh DIM audit of `NumStability.leveque01_coordinateHighResolutionMethods_sourceContract`; respond to any real finding without relabeling prior failures. Its complete native joint fixture is evidence of applicability, not source acceptance.\n'
text+='2. Finish and review the information-only Riemann routine’s mandatory exact/approximate solving relation, then freeze its successor, native evidence and fresh audit. The latest unrestricted routine decision is undetermined (unclear/yes); arbitrary information processing is not yet a solved source row.\n'
text+='3. After final leaves/imports/tiers freeze, complete current source coverage, all41 declaration and axiom checks, full/focused build, layout/tiers/compatibility/hygiene, current import/signature/body graphs and manual duplicate/canonical-placement reviews. Rebind all accepted rows preserving interpretations/refinements, stronger classifications and scoped contracts; run the exact complete validator with `--validate --require-all-closed`, bind actual global evidence, then run the released gate `check … --unit 1 --mode default --require-pass`. No final check result is asserted here.\n'
text+='4. Commit the actual final PASS state, refresh the reviewed topology’s legitimate lane pin and a new stopping request; construct the real candidate in the launcher’s disposable workspace. Inventory both merge and inspection lanes from actual Git blobs, retain all prior declarations/proofs/audits, resolve real collisions, and use the explicit Eq1.3 source/type/policy/producer transport backed by full re-audit. The old retained request cannot simply be upgraded to a candidate.\n'
text+='5. Assemble candidate-local affected-book verdicts or named reopenings, six measured organization lists and repository ratchet, and all eight real candidate-tree receipts: source_coverage, import_graph, signature_graph, body_graph, declaration_resolution, focused_build, full_build, pristine_replay. Validate the candidate-status epoch, issue exactly one matching PASS checkpoint, then run terminal/campaign checks. Under prepare/forbid/none, legitimate local completion is VALIDATED/candidate, not PASS with QUEUED/retained.\n'
text+='6. Campaign admission and stable promotion/publication require separately supplied candidate-specific authority evidence under the released route. Do not fabricate those receipts or equate origin/main publication with protected-campaign integration. A local VALIDATED result is not admission or permission for dependent units.\n\n'
text+='Exact reviewed command/templates and constraints: '+', '.join(link(v) for v in obligation_refs)+'. Earlier helper prose inventory totals are historical; final inputs must include all six current fingerprint inventories and any further Info-certified additions.\n\n'
integ=data['integration'];text+=f"**Observed integration state.** Topology lists the unit as checkpointed. The latest stored request `{integ['latest_pointer']['request_id']}` is `{integ['status_state']}/{integ['result_kind']}` and records the historical BLOCKED gate, not this reopened goal. Work/inspection pins are5e3; protected campaign and stable pins remain9e222. No final candidate/epoch, admission or promotion is present in this report. {link(integ['topology'])}; {link(integ['status'])}.\n\n"
text+='**Issue records.** Book/source issues and process/transport limitations stay separate. Snapshot hashes and the latest exact issue IDs are in report-data.json. Recent entries preserve the FV norm-complete acceptance, full DIM quality/joint witness, historical DIM rejection and current routine solving-linkage gap; they do not turn pending audits into acceptance. This report writes neither tracker.\n\n'
text+='**All recorded completed/reused declarations (39).**\n\n| Status | Declaration | Classification |\n|---|---|---|\n'
for row in data['all_accepted_rows']:text+=f"| {row['status']} | `{' ; '.join(row['lean_declarations'])}` | {row['classification']} |\n"
text+='\nNo hard blocker is certified in the current goal. The two mathematical/audit repairs and final evidence work remain actionable. Candidate-specific admission/promotion evidence is an external condition only for those later operations; it does not justify stopping local work now.\n'
with (F/'report-draft.md').open('x',encoding='utf-8',newline='\n') as f:f.write(text)
with (F/'review-supplement.json').open('x',encoding='utf-8',newline='\n') as f:json.dump({'status':'CURRENT REVIEW DRAFT','pending':pending,'gate_defect_count':len(defects),'gate_defect_examples':defects[:6],'extra_evidence':extra,'ledger_snapshots':snapshot_refs,'future_results_not_asserted':['all41PASS','final global validation','candidate epoch','integration','publication']},f,indent=2);f.write('\n')
print(json.dumps({'report':ref(F/'report-draft.md'),'producer_map':ref(F/'producer-reuse-map.json'),'pending':len(pending),'defects':len(defects)}))
