import Mathlib.Probability.Kernel.IonescuTulcea.Traj
import Mathlib.Probability.ProductMeasure
import ComputationalMathematics.HDP.Scalar.IndependentSums.McDiarmid

/-!
# Product-space bounded-differences inequality

A Doob exposure construction for measurable finite-coordinate functions of
independent random variables. This is the product-space bridge from coordinate
oscillation bounds to the reusable conditional-MGF McDiarmid engine.
-/

noncomputable section

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal NNReal ProbabilityTheory Topology

namespace NumStability.HDP.Scalar.IndependentSums.McDiarmid

variable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω}

/-- A pinned-compatibility bridge: the current Mathlib revision predates the
global `StandardBorelSpace -> MeasurableEq` instance available in the archive's
newer revision. -/
noncomputable def measurableEqOfStandardBorel (α : Type*)
    [orig : MeasurableSpace α] [StandardBorelSpace α] : MeasurableEq α := by
  let t := upgradeStandardBorel α
  have heq : t.toMeasurableSpace = orig := rfl
  letI : MeasurableSpace α := t.toMeasurableSpace
  letI : TopologicalSpace α := t.toTopologicalSpace
  letI : BorelSpace α := t.toBorelSpace
  letI : PolishSpace α := t.toPolishSpace
  have h : @MeasurableEq α t.toMeasurableSpace := by infer_instance
  rw [heq] at h
  exact h

universe u

/-- Add a deterministic dummy coordinate before an independent sequence.  This
lets the first genuine random coordinate be generated by a Markov kernel, so
all Doob increments are handled uniformly by `Kernel.condExp_traj'`. -/
abbrev shiftedSeqType (X : ℕ → Type u) : ℕ → Type u
  | 0 => PUnit
  | n + 1 => X n

instance shiftedSeqType.measurableSpace {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] :
    ∀ n, MeasurableSpace (shiftedSeqType X n)
  | 0 => inferInstance
  | _ + 1 => inferInstance

instance shiftedSeqType.standardBorel {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)] :
    ∀ n, StandardBorelSpace (shiftedSeqType X n)
  | 0 => inferInstance
  | _ + 1 => inferInstance

instance shiftedSeqType.nonempty {X : ℕ → Type u} [∀ n, Nonempty (X n)] :
    ∀ n, Nonempty (shiftedSeqType X n)
  | 0 => inferInstance
  | _ + 1 => inferInstance

/-- Drop the deterministic dummy coordinate from a shifted sequence. -/
def shiftedTail {X : ℕ → Type u}
    (z : (n : ℕ) → shiftedSeqType X n) (i : ℕ) : X i :=
  z (i + 1)

/-- Dropping the deterministic dummy coordinate is measurable for the product
measurable structures. -/
lemma measurable_shiftedTail {X : ℕ → Type u} [∀ n, MeasurableSpace (X n)] :
    Measurable (shiftedTail (X := X)) :=
  measurable_pi_lambda _ fun i ↦ measurable_pi_apply (i + 1)

/-- The shifted product measure family: a deterministic dummy coordinate at
time `0`, followed by the original independent coordinate laws. -/
noncomputable def shiftedMeasure {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) :
    (n : ℕ) → Measure (shiftedSeqType X n)
  | 0 => Measure.dirac PUnit.unit
  | n + 1 => μ n

instance shiftedMeasure.isProbabilityMeasure {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)] :
    ∀ n, IsProbabilityMeasure (shiftedMeasure (X := X) μ n)
  | 0 => by dsimp [shiftedMeasure]; infer_instance
  | n + 1 => by dsimp [shiftedMeasure]; infer_instance

/-- The finite product law of the shifted independent coordinates strictly
after `a` and up to `N`. -/
noncomputable abbrev shiftedFutureProductMeasure {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) (a N : ℕ) :
    Measure ((j : Finset.Ioc a N) → shiftedSeqType X (j : ℕ)) :=
  @Measure.pi (Finset.Ioc a N) (fun j => shiftedSeqType X (j : ℕ)) inferInstance
    (fun j => shiftedSeqType.measurableSpace (X := X) (j : ℕ))
    (fun j => shiftedMeasure (X := X) μ (j : ℕ))

instance shiftedFutureProductMeasure.isProbabilityMeasure {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)] (a N : ℕ) :
    IsProbabilityMeasure (shiftedFutureProductMeasure (X := X) μ a N) := by
  dsimp [shiftedFutureProductMeasure]
  infer_instance

/-- Coordinate bounded-differences predicate for a function on the first `N`
coordinates of a sequence. -/
def SeqBoundedDifferences {X : ℕ → Type u}
    (f : ((n : ℕ) → X n) → ℝ) (c : ℕ → ℝ) (N : ℕ) : Prop :=
  ∀ i < N, ∀ x y, (∀ j, j ≠ i → x j = y j) → |f x - f y| ≤ c i

/-- If two inputs agree from coordinate `N` onward, coordinate bounded
differences over the first `N` coordinates control the total oscillation by
the sum of the first `N` constants. -/
lemma seqBoundedDifferences_diff_le_sum_of_eq_from {X : ℕ → Type u}
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {M N : ℕ}
    (hbd : SeqBoundedDifferences f c M) (hNM : N ≤ M)
    {x y : (n : ℕ) → X n}
    (hxy : ∀ j, N ≤ j → x j = y j) :
    |f x - f y| ≤ ∑ i ∈ Finset.range N, c i := by
  induction N generalizing x y with
  | zero =>
      have hfun : x = y := by
        funext j
        exact hxy j (zero_le j)
      simp [hfun]
  | succ N ih =>
      let y' := Function.update y N (x N)
      have hxy' : ∀ j, N ≤ j → x j = y' j := by
        intro j hj
        by_cases hNj : j = N
        · subst hNj
          simp [y']
        · have hsucc : N + 1 ≤ j := by omega
          have htail := hxy j hsucc
          simp [y', hNj, htail]
      have hNltM : N < M := lt_of_lt_of_le (Nat.lt_succ_self N) hNM
      have hy'_diff : ∀ j, j ≠ N → y' j = y j := by
        intro j hj
        simp [y', hj]
      have hstep : |f y' - f y| ≤ c N := hbd N hNltM y' y hy'_diff
      have hprev : |f x - f y'| ≤ ∑ i ∈ Finset.range N, c i :=
        ih (Nat.le_of_succ_le hNM) hxy'
      calc
        |f x - f y| ≤ |f x - f y'| + |f y' - f y| := by
          have hsum : f x - f y = (f x - f y') + (f y' - f y) := by ring
          rw [hsum]
          exact abs_add_le _ _
        _ ≤ (∑ i ∈ Finset.range N, c i) + c N := add_le_add hprev hstep
        _ = ∑ i ∈ Finset.range (N + 1), c i := by
          simp [Finset.sum_range_succ]

/-- A finite-coordinate bounded-differences function has deterministic
diameter at most the sum of its coordinate constants. -/
lemma seqBoundedDifferences_diff_le_sum {X : ℕ → Type u}
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N : ℕ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N)
    (x y : (n : ℕ) → X n) :
    |f x - f y| ≤ ∑ i ∈ Finset.range N, c i := by
  let y' := Function.updateFinset y (Finset.range N) (fun i : Finset.range N => x (i : ℕ))
  have hxy' : f x = f y' := by
    exact hdep fun j hj => by
      have hjmem : j ∈ Finset.range N := by simpa [Finset.mem_range] using hj
      simp [y', Function.updateFinset, hjmem]
  have hy'y_tail : ∀ j, N ≤ j → y' j = y j := by
    intro j hj
    have hjnot : j ∉ Finset.range N := by simpa [Finset.mem_range] using not_lt.mpr hj
    simp [y', Function.updateFinset, hjnot]
  have htail := seqBoundedDifferences_diff_le_sum_of_eq_from
    (X := X) (f := f) (c := c) (M := N) (N := N) hbd le_rfl hy'y_tail
  simpa [hxy'] using htail

/-- A measurable function depending only on the prefix up to `N` is strongly
measurable with respect to the product filtration at level `N`. -/
lemma aestronglyMeasurable_piLE_of_dependsOn {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, Nonempty (X n)]
    {F : ((n : ℕ) → X n) → ℝ} {N : ℕ} {μ : Measure ((n : ℕ) → X n)}
    (hdep : DependsOn F (Set.Iic N))
    (hFmeas : Measurable F) :
    AEStronglyMeasurable[MeasureTheory.Filtration.piLE (X := X) N] F μ := by
  let base : (n : ℕ) → X n := fun n => Classical.ofNonempty
  let g : ((j : Finset.Iic N) → X (j : ℕ)) → ℝ :=
    fun xN => F (Function.updateFinset base (Finset.Iic N) xN)
  have hg : Measurable g := by
    exact hFmeas.comp (by
      simpa [g] using (measurable_updateFinset (x := base) (s := Finset.Iic N)))
  have hgf : @Measurable ((n : ℕ) → X n) ℝ
      (MeasureTheory.Filtration.piLE (X := X) N) (borel ℝ)
      (fun z => g (Preorder.frestrictLe N z)) := by
    rw [MeasureTheory.Filtration.piLE_eq_comap_frestrictLe (X := X) N]
    exact hg.comp (Measurable.of_comap_le le_rfl)
  have hpoint : (fun z => g (Preorder.frestrictLe N z)) = F := by
    funext z
    dsimp [g]
    exact hdep fun j hj => by
      have hjmem : j ∈ Finset.Iic N := by simpa [Finset.mem_Iic] using hj
      simp [Function.updateFinset, hjmem, Preorder.frestrictLe]
  exact hgf.aestronglyMeasurable.congr (ae_of_all _ fun _z => by rw [hpoint])

/-- The constant Markov kernel that generates the next independent coordinate
in the shifted sequence model. -/
noncomputable def shiftedIndependentKernel {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n))
    (n : ℕ) :
    Kernel ((i : Finset.Iic n) → shiftedSeqType X i) (shiftedSeqType X (n + 1)) := by
  cases n with
  | zero => exact Kernel.const _ (μ 0)
  | succ n => exact Kernel.const _ (μ (n + 1))

lemma shiftedIndependentKernel_eq_const_shiftedMeasure {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) (n : ℕ) :
    shiftedIndependentKernel (X := X) μ n =
      Kernel.const _ (shiftedMeasure (X := X) μ (n + 1)) := by
  cases n <;> rfl

instance shiftedIndependentKernel.isMarkovKernel {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)] :
    ∀ n, IsMarkovKernel (shiftedIndependentKernel (X := X) μ n) := by
  intro n
  cases n <;> dsimp [shiftedIndependentKernel] <;> infer_instance

/-- The deterministic initial state on the dummy coordinate. -/
noncomputable def shiftedInitial {X : ℕ → Type u} :
    (i : Finset.Iic 0) → shiftedSeqType X i := fun i => by
  cases i with
  | mk val hval =>
    simp only [Finset.mem_Iic] at hval
    have hzero : val = 0 := Nat.eq_zero_of_le_zero hval
    subst hzero
    exact PUnit.unit

/-- The prefix of a shifted sequence at the deterministic dummy coordinate is
the canonical dummy initial state. -/
lemma frestrictLe_zero_shifted_eq_initial {X : ℕ → Type u}
    (z : (n : ℕ) → shiftedSeqType X n) :
    Preorder.frestrictLe 0 z = shiftedInitial (X := X) := by
  funext i
  cases i with
  | mk val hval =>
    simp only [Finset.mem_Iic] at hval
    have hzero : val = 0 := Nat.eq_zero_of_le_zero hval
    subst hzero
    rfl

/-- The independent product trajectory with a deterministic dummy coordinate
at time `0` and genuine independent coordinates at times `1,2,...`. -/
noncomputable def shiftedIndependentTraj {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)] :
    Measure ((n : ℕ) → shiftedSeqType X n) := by
  exact Kernel.traj (shiftedIndependentKernel (X := X) μ) 0 (shiftedInitial (X := X))

instance shiftedIndependentTraj.isProbabilityMeasure {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)] :
    IsProbabilityMeasure (shiftedIndependentTraj (X := X) μ) := by
  dsimp [shiftedIndependentTraj]
  infer_instance

/-- Lift a function of the genuine coordinates to the shifted trajectory space. -/
noncomputable def shiftedFunction {X : ℕ → Type u}
    (f : ((n : ℕ) → X n) → ℝ) :
    ((n : ℕ) → shiftedSeqType X n) → ℝ :=
  fun z => f (shiftedTail z)

lemma shiftedFunction_measurable {X : ℕ → Type u} [∀ n, MeasurableSpace (X n)]
    {f : ((n : ℕ) → X n) → ℝ} (hf : Measurable f) :
    Measurable (shiftedFunction f) :=
  hf.comp measurable_shiftedTail

lemma shiftedFunction_dependsOn {X : ℕ → Type u}
    {f : ((n : ℕ) → X n) → ℝ} {N : ℕ}
    (hf : DependsOn f (Set.Iio N)) :
    DependsOn (shiftedFunction f) (Set.Iic N) := by
  intro z w hzw
  dsimp [shiftedFunction, shiftedTail]
  exact hf fun j hj => hzw (j + 1) (by simpa [Set.mem_Iic] using Nat.succ_le_of_lt hj)

/-- A finite-coordinate bounded-differences function has an integrable shifted
lift under every probability measure, provided the shifted lift is measurable. -/
lemma shiftedFunction_integrable_of_boundedDifferences {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, Nonempty (X n)]
    {ν : Measure ((n : ℕ) → shiftedSeqType X n)} [IsProbabilityMeasure ν]
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N : ℕ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N)
    (hFmeas : Measurable (shiftedFunction f)) :
    Integrable (shiftedFunction f) ν := by
  let ref : (n : ℕ) → X n := fun n => Classical.ofNonempty
  let S : ℝ := ∑ i ∈ Finset.range N, c i
  let C : ℝ := |f ref| + S
  refine Integrable.of_bound hFmeas.aestronglyMeasurable C ?_
  filter_upwards with z
  rw [Real.norm_eq_abs]
  let x := shiftedTail z
  have hdiff := seqBoundedDifferences_diff_le_sum (X := X) (f := f) (c := c) (N := N)
    hdep hbd x ref
  have htri : |f x| ≤ |f x - f ref| + |f ref| := by
    calc
      |f x| = |(f x - f ref) + f ref| := by ring_nf
      _ ≤ |f x - f ref| + |f ref| :=
        (abs_add_le (f x - f ref) (f ref) :
          |(f x - f ref) + f ref| ≤ |f x - f ref| + |f ref|)
  dsimp [shiftedFunction] at htri ⊢
  change |f x| ≤ C
  dsimp [C, S]
  linarith

/-- A finite-coordinate bounded-differences function is integrable over any
finite shifted future product once its shifted lift is measurable. -/
lemma shiftedFunction_future_integrable_of_boundedDifferences {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, Nonempty (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N a : ℕ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N)
    (hFmeas : Measurable (shiftedFunction f))
    (z : (n : ℕ) → shiftedSeqType X n) :
    Integrable (fun u => shiftedFunction f
      (Function.updateFinset z (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) a N
          (Preorder.frestrictLe a z, u))))
      (shiftedFutureProductMeasure (X := X) μ a N) := by
  let ref : (n : ℕ) → X n := fun n => Classical.ofNonempty
  let S : ℝ := ∑ i ∈ Finset.range N, c i
  let C : ℝ := |f ref| + S
  have hmeas : Measurable (fun u => shiftedFunction f
      (Function.updateFinset z (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) a N
          (Preorder.frestrictLe a z, u)))) := by
    exact hFmeas.comp (by fun_prop)
  refine Integrable.of_bound hmeas.aestronglyMeasurable C ?_
  filter_upwards with u
  rw [Real.norm_eq_abs]
  let x := shiftedTail
      (Function.updateFinset z (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) a N
          (Preorder.frestrictLe a z, u)))
  have hdiff := seqBoundedDifferences_diff_le_sum (X := X) (f := f) (c := c) (N := N)
    hdep hbd x ref
  have htri : |f x| ≤ |f x - f ref| + |f ref| := by
    calc
      |f x| = |(f x - f ref) + f ref| := by ring_nf
      _ ≤ |f x - f ref| + |f ref| :=
        (abs_add_le (f x - f ref) (f ref) :
          |(f x - f ref) + f ref| ≤ |f x - f ref| + |f ref|)
  dsimp [shiftedFunction] at htri ⊢
  change |f x| ≤ C
  dsimp [C, S]
  linarith

/-- If two shifted sequences agree away from shifted coordinate `i + 1`, then
their genuine tails agree away from coordinate `i`. -/
lemma shiftedTail_eq_of_eq_shifted {X : ℕ → Type u}
    {z w : (n : ℕ) → shiftedSeqType X n} {i : ℕ}
    (h : ∀ j, j ≠ i + 1 → z j = w j) :
    ∀ k, k ≠ i → shiftedTail z k = shiftedTail w k := by
  intro k hk
  exact h (k + 1) (by omega)

/-- The shifted lift of a coordinate-bounded-differences function has the same
bounded-differences constant on the corresponding non-dummy coordinate. -/
lemma shiftedFunction_boundedDifference {X : ℕ → Type u}
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N i : ℕ}
    (hbd : SeqBoundedDifferences f c N) (hi : i < N)
    {z w : (n : ℕ) → shiftedSeqType X n}
    (h : ∀ j, j ≠ i + 1 → z j = w j) :
    |shiftedFunction f z - shiftedFunction f w| ≤ c i := by
  exact hbd i hi (shiftedTail z) (shiftedTail w) (shiftedTail_eq_of_eq_shifted h)

lemma updateFinset_eq_away_of_frestrictLe_eq {X : ℕ → Type u}
    {i : ℕ} {z w y : (n : ℕ) → shiftedSeqType X n}
    (hzw : Preorder.frestrictLe i z = Preorder.frestrictLe i w) :
    ∀ j, j ≠ i + 1 →
      Function.updateFinset y (Finset.Iic (i + 1)) (Preorder.frestrictLe (i + 1) z) j =
      Function.updateFinset y (Finset.Iic (i + 1)) (Preorder.frestrictLe (i + 1) w) j := by
  intro j hj
  by_cases hle : j ≤ i + 1
  · have hj_mem : j ∈ Finset.Iic (i + 1) := by simpa [Finset.mem_Iic] using hle
    have hji : j ≤ i := by omega
    have hzwi : z j = w j := by
      have hfun := congrFun hzw ⟨j, by simpa [Finset.mem_Iic] using hji⟩
      simpa [Preorder.frestrictLe] using hfun
    simp [Function.updateFinset, hj_mem, hzwi]
  · have hj_not : j ∉ Finset.Iic (i + 1) := by simpa [Finset.mem_Iic] using hle
    simp [Function.updateFinset, hj_not]

lemma shiftedFunction_updateFinset_diff_le {X : ℕ → Type u}
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N i : ℕ}
    (hbd : SeqBoundedDifferences f c N) (hi : i < N)
    {z w y : (n : ℕ) → shiftedSeqType X n}
    (hzw : Preorder.frestrictLe i z = Preorder.frestrictLe i w) :
    |shiftedFunction f
        (Function.updateFinset y (Finset.Iic (i + 1)) (Preorder.frestrictLe (i + 1) z)) -
      shiftedFunction f
        (Function.updateFinset y (Finset.Iic (i + 1)) (Preorder.frestrictLe (i + 1) w))| ≤ c i := by
  exact shiftedFunction_boundedDifference (X := X) (f := f) (c := c) (N := N) (i := i)
    hbd hi (updateFinset_eq_away_of_frestrictLe_eq (X := X) (i := i) hzw)

lemma shiftedFunction_updateFinset_Iic_diff_le {X : ℕ → Type u}
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N i : ℕ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N) (hi : i < N)
    {base z w : (n : ℕ) → shiftedSeqType X n}
    {xz xw : (j : Finset.Iic N) → shiftedSeqType X j}
    (hxw : ∀ j (hj : j ≤ N), j ≠ i + 1 →
      xz ⟨j, by simpa [Finset.mem_Iic] using hj⟩ =
      xw ⟨j, by simpa [Finset.mem_Iic] using hj⟩) :
    |shiftedFunction f (Function.updateFinset z (Finset.Iic N) xz) -
      shiftedFunction f (Function.updateFinset w (Finset.Iic N) xw)| ≤ c i := by
  let F : ((n : ℕ) → shiftedSeqType X n) → ℝ := shiftedFunction f
  have hFdep : DependsOn F (Set.Iic N) := shiftedFunction_dependsOn (X := X) (f := f) hdep
  have hzbase : F (Function.updateFinset z (Finset.Iic N) xz) =
      F (Function.updateFinset base (Finset.Iic N) xz) := by
    exact hFdep fun j hj => by
      have hj_mem : j ∈ Finset.Iic N := by simpa [Finset.mem_Iic] using hj
      simp [Function.updateFinset, hj_mem]
  have hwbase : F (Function.updateFinset w (Finset.Iic N) xw) =
      F (Function.updateFinset base (Finset.Iic N) xw) := by
    exact hFdep fun j hj => by
      have hj_mem : j ∈ Finset.Iic N := by simpa [Finset.mem_Iic] using hj
      simp [Function.updateFinset, hj_mem]
  change |F (Function.updateFinset z (Finset.Iic N) xz) -
      F (Function.updateFinset w (Finset.Iic N) xw)| ≤ c i
  rw [hzbase, hwbase]
  refine shiftedFunction_boundedDifference (X := X) (f := f) (c := c) (N := N) (i := i)
    hbd hi ?_
  intro j hj
  by_cases hjN : j ≤ N
  · have hj_mem : j ∈ Finset.Iic N := by simpa [Finset.mem_Iic] using hjN
    simp [Function.updateFinset, hj_mem, hxw j hjN hj]
  · have hj_not : j ∉ Finset.Iic N := by simpa [Finset.mem_Iic] using hjN
    simp [Function.updateFinset, hj_not]

lemma IicProdIoc_shifted_prefix_eq_away {X : ℕ → Type u}
    {i N : ℕ}
    {z w : (n : ℕ) → shiftedSeqType X n}
    (hzw : Preorder.frestrictLe i z = Preorder.frestrictLe i w)
    (u : (j : Finset.Ioc (i + 1) N) → shiftedSeqType X j) :
    ∀ j (hj : j ≤ N), j ≠ i + 1 →
      IicProdIoc (X := shiftedSeqType X) (i + 1) N
        (Preorder.frestrictLe (i + 1) z, u)
        ⟨j, by simpa [Finset.mem_Iic] using hj⟩ =
      IicProdIoc (X := shiftedSeqType X) (i + 1) N
        (Preorder.frestrictLe (i + 1) w, u)
        ⟨j, by simpa [Finset.mem_Iic] using hj⟩ := by
  intro j hj hjne
  by_cases hja : j ≤ i + 1
  · have hji : j ≤ i := by omega
    have hzwi : z j = w j := by
      have hfun := congrFun hzw ⟨j, by simpa [Finset.mem_Iic] using hji⟩
      simpa [Preorder.frestrictLe] using hfun
    simp [IicProdIoc, hja, hzwi]
  · simp [IicProdIoc, hja]

lemma shiftedFunction_future_integral_diff_le {X : ℕ → Type u}
    [∀ n, MeasurableSpace (shiftedSeqType X n)]
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N i : ℕ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N) (hi : i < N)
    {z w : (n : ℕ) → shiftedSeqType X n}
    (hzw : Preorder.frestrictLe i z = Preorder.frestrictLe i w)
    {ν : Measure ((j : Finset.Ioc (i + 1) N) → shiftedSeqType X j)}
    [IsProbabilityMeasure ν]
    (hzint : Integrable (fun u => shiftedFunction f
      (Function.updateFinset z (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) (i + 1) N
          (Preorder.frestrictLe (i + 1) z, u)))) ν)
    (hwint : Integrable (fun u => shiftedFunction f
      (Function.updateFinset w (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) (i + 1) N
          (Preorder.frestrictLe (i + 1) w, u)))) ν) :
    |((∫ u, shiftedFunction f
      (Function.updateFinset z (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) (i + 1) N
          (Preorder.frestrictLe (i + 1) z, u))) ∂ν) -
      (∫ u, shiftedFunction f
      (Function.updateFinset w (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) (i + 1) N
          (Preorder.frestrictLe (i + 1) w, u))) ∂ν))| ≤ c i := by
  refine abs_integral_sub_integral_le_of_ae_abs_sub_le hzint hwint ?_
  filter_upwards with u
  exact shiftedFunction_updateFinset_Iic_diff_le (X := X) (f := f) (c := c)
    (N := N) (i := i) hdep hbd hi
    (base := z) (z := z) (w := w)
    (xz := IicProdIoc (X := shiftedSeqType X) (i + 1) N
          (Preorder.frestrictLe (i + 1) z, u))
    (xw := IicProdIoc (X := shiftedSeqType X) (i + 1) N
          (Preorder.frestrictLe (i + 1) w, u))
    (IicProdIoc_shifted_prefix_eq_away (X := X) (i := i) (N := N) hzw u)

/-- Pointwise trajectory-integral representative of the Doob conditional
expectation for the shifted independent product. -/
noncomputable def shiftedTrajM {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    (F : ((n : ℕ) → shiftedSeqType X n) → ℝ) (k : ℕ) :
    ((n : ℕ) → shiftedSeqType X n) → ℝ :=
  fun z => ∫ y, F y
    ∂ProbabilityTheory.Kernel.traj (shiftedIndependentKernel (X := X) μ) k
      (Preorder.frestrictLe k z)

/-- The trajectory representative at time `k` only depends on the observed
prefix up to `k`. -/
lemma shiftedTrajM_dependsOn {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    (F : ((n : ℕ) → shiftedSeqType X n) → ℝ) (k : ℕ) :
    DependsOn (shiftedTrajM μ F k) (Set.Iic k) := by
  intro z w hzw
  dsimp [shiftedTrajM]
  have hp : Preorder.frestrictLe k z = Preorder.frestrictLe k w := by
    funext i
    have hi : (i : ℕ) ≤ k := Finset.mem_Iic.mp i.2
    exact hzw i (by simpa [Set.mem_Iic] using hi)
  rw [hp]

lemma integral_traj_eq_of_dependsOn_Iic {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    {κ : (n : ℕ) → Kernel ((i : Finset.Iic n) → X i) (X (n + 1))}
    [∀ n, IsMarkovKernel (κ n)] {F : ((n : ℕ) → X n) → ℝ} {N : ℕ}
    (hdep : DependsOn F (Set.Iic N))
    {x : (i : Finset.Iic N) → X i} {z : (n : ℕ) → X n}
    (hFsm : AEStronglyMeasurable F (ProbabilityTheory.Kernel.traj κ N x)) :
    ∫ y, F y ∂ProbabilityTheory.Kernel.traj κ N x =
      F (Function.updateFinset z (Finset.Iic N) x) := by
  rw [ProbabilityTheory.Kernel.integral_traj (κ := κ) (a := N) (x₀ := x) hFsm]
  apply integral_eq_const
  filter_upwards with y
  exact hdep fun j hj => by
    have hj_mem : j ∈ Finset.Iic N := by simpa [Finset.mem_Iic] using hj
    simp [Function.updateFinset, hj_mem]

lemma integral_traj_eq_partialTraj_of_dependsOn_Iic {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    {κ : (n : ℕ) → Kernel ((i : Finset.Iic n) → X i) (X (n + 1))}
    [∀ n, IsMarkovKernel (κ n)] {F : ((n : ℕ) → X n) → ℝ} {k N : ℕ}
    (hkN : k ≤ N) (hdep : DependsOn F (Set.Iic N))
    {xk : (i : Finset.Iic k) → X i} {z : (n : ℕ) → X n}
    (hFint : Integrable F (ProbabilityTheory.Kernel.traj κ k xk)) :
    ∫ y, F y ∂ProbabilityTheory.Kernel.traj κ k xk =
      ∫ xN, F (Function.updateFinset z (Finset.Iic N) xN)
        ∂ProbabilityTheory.Kernel.partialTraj κ k N xk := by
  have hdecomp := ProbabilityTheory.Kernel.integral_traj_partialTraj
    (κ := κ) (a := k) (b := N) hkN (x₀ := xk) (f := F) hFint
  rw [← hdecomp]
  have hsm_ae := ProbabilityTheory.Kernel.aestronglyMeasurable_traj
    (κ := κ) (a := k) (b := N) hkN (f := F) (x₀ := xk) hFint.1
  refine integral_congr_ae ?_
  filter_upwards [hsm_ae] with xN hxN
  exact integral_traj_eq_of_dependsOn_Iic (κ := κ) (N := N) hdep (x := xN) (z := z) hxN

/-- For the shifted independent product, a finite partial trajectory integral
from an observed prefix `a` to `N` is the same as integrating over the product
law of the unobserved shifted coordinates `a < j ≤ N`. -/
lemma shifted_partialTraj_integral_eq_future {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {F : ((n : ℕ) → shiftedSeqType X n) → ℝ} {a N : ℕ}
    (haN : a ≤ N)
    {z : (n : ℕ) → shiftedSeqType X n} :
    ∫ xN, F (Function.updateFinset z (Finset.Iic N) xN)
      ∂ProbabilityTheory.Kernel.partialTraj (shiftedIndependentKernel (X := X) μ) a N
        (Preorder.frestrictLe a z)
    = ∫ u, F (Function.updateFinset z (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) a N
          (Preorder.frestrictLe a z, u)))
      ∂shiftedFutureProductMeasure (X := X) μ a N := by
  let ν := shiftedFutureProductMeasure (X := X) μ a N
  let pref := Preorder.frestrictLe a z
  let G := fun xN : (j : Finset.Iic N) → shiftedSeqType X (j : ℕ) =>
    F (Function.updateFinset z (Finset.Iic N) xN)
  let e := fun u : (j : Finset.Ioc a N) → shiftedSeqType X (j : ℕ) =>
    IicProdIoc (X := shiftedSeqType X) a N (pref, u)
  have hemb : MeasurableEmbedding e := by
    dsimp [e, pref]
    exact (MeasurableEquiv.IicProdIoc (X := shiftedSeqType X) haN).measurableEmbedding.comp
      (measurableEmbedding_prodMk_left (Preorder.frestrictLe a z))
  have hκ : shiftedIndependentKernel (X := X) μ =
      fun n => ProbabilityTheory.Kernel.const ((i : Finset.Iic n) → shiftedSeqType X (i : ℕ))
        (shiftedMeasure (X := X) μ (n + 1)) := by
    funext n
    exact shiftedIndependentKernel_eq_const_shiftedMeasure (X := X) μ n
  change ∫ xN, G xN
      ∂ProbabilityTheory.Kernel.partialTraj (shiftedIndependentKernel (X := X) μ) a N pref =
    ∫ u, G (e u) ∂ν
  rw [hκ]
  rw [MeasureTheory.partialTraj_const (X := shiftedSeqType X) (μ := shiftedMeasure (X := X) μ)]
  rw [ProbabilityTheory.Kernel.map_apply]
  rw [ProbabilityTheory.Kernel.prod_apply, ProbabilityTheory.Kernel.id_apply,
    ProbabilityTheory.Kernel.const_apply]
  rw [Measure.dirac_prod]
  rw [Measure.map_map]
  exact MeasurableEmbedding.integral_map hemb G
  all_goals fun_prop

/-- Coordinate bounded differences compare the two `i + 1` trajectory
conditional-expectation representatives when the observed histories agree up
to time `i`; the remaining future is integrated against the same product law. -/
lemma shiftedTrajM_succ_diff_le_of_boundedDifferences {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N i : ℕ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N) (hi : i < N)
    {z w : (n : ℕ) → shiftedSeqType X n}
    (hzw : Preorder.frestrictLe i z = Preorder.frestrictLe i w)
    (hzint : Integrable (shiftedFunction f)
      (ProbabilityTheory.Kernel.traj (shiftedIndependentKernel (X := X) μ) (i + 1)
        (Preorder.frestrictLe (i + 1) z)))
    (hwint : Integrable (shiftedFunction f)
      (ProbabilityTheory.Kernel.traj (shiftedIndependentKernel (X := X) μ) (i + 1)
        (Preorder.frestrictLe (i + 1) w)))
    (hzfuture : Integrable (fun u => shiftedFunction f
      (Function.updateFinset z (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) (i + 1) N
          (Preorder.frestrictLe (i + 1) z, u))))
      (shiftedFutureProductMeasure (X := X) μ (i + 1) N))
    (hwfuture : Integrable (fun u => shiftedFunction f
      (Function.updateFinset w (Finset.Iic N)
        (IicProdIoc (X := shiftedSeqType X) (i + 1) N
          (Preorder.frestrictLe (i + 1) w, u))))
      (shiftedFutureProductMeasure (X := X) μ (i + 1) N)) :
    |shiftedTrajM μ (shiftedFunction f) (i + 1) z -
      shiftedTrajM μ (shiftedFunction f) (i + 1) w| ≤ c i := by
  let κ := shiftedIndependentKernel (X := X) μ
  let F := shiftedFunction f
  have haN : i + 1 ≤ N := Nat.succ_le_of_lt hi
  have hFdep : DependsOn F (Set.Iic N) :=
    shiftedFunction_dependsOn (X := X) (f := f) hdep
  have hz_partial := integral_traj_eq_partialTraj_of_dependsOn_Iic
    (κ := κ) (F := F) (k := i + 1) (N := N) haN hFdep
    (xk := Preorder.frestrictLe (i + 1) z) (z := z) hzint
  have hw_partial := integral_traj_eq_partialTraj_of_dependsOn_Iic
    (κ := κ) (F := F) (k := i + 1) (N := N) haN hFdep
    (xk := Preorder.frestrictLe (i + 1) w) (z := w) hwint
  have hz_future := shifted_partialTraj_integral_eq_future
    (X := X) μ (F := F) (a := i + 1) (N := N) haN (z := z)
  have hw_future := shifted_partialTraj_integral_eq_future
    (X := X) μ (F := F) (a := i + 1) (N := N) haN (z := w)
  change |(∫ y, F y ∂ProbabilityTheory.Kernel.traj κ (i + 1)
        (Preorder.frestrictLe (i + 1) z)) -
      (∫ y, F y ∂ProbabilityTheory.Kernel.traj κ (i + 1)
        (Preorder.frestrictLe (i + 1) w))| ≤ c i
  rw [hz_partial, hw_partial, hz_future, hw_future]
  exact shiftedFunction_future_integral_diff_le (X := X) (f := f) (c := c)
    (N := N) (i := i) hdep hbd hi hzw hzfuture hwfuture

/-- Measurable finite-coordinate bounded-differences functions satisfy the
`i + 1` trajectory comparison without separate integrability hypotheses. -/
lemma shiftedTrajM_succ_diff_le_of_boundedDifferences_measurable {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)] [∀ n, Nonempty (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N i : ℕ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N)
    (hFmeas : Measurable (shiftedFunction f))
    (hi : i < N)
    {z w : (n : ℕ) → shiftedSeqType X n}
    (hzw : Preorder.frestrictLe i z = Preorder.frestrictLe i w) :
    |shiftedTrajM μ (shiftedFunction f) (i + 1) z -
      shiftedTrajM μ (shiftedFunction f) (i + 1) w| ≤ c i := by
  refine shiftedTrajM_succ_diff_le_of_boundedDifferences (X := X) μ
    (f := f) (c := c) (N := N) (i := i) hdep hbd hi hzw ?_ ?_ ?_ ?_
  · exact shiftedFunction_integrable_of_boundedDifferences (X := X)
      (ν := ProbabilityTheory.Kernel.traj (shiftedIndependentKernel (X := X) μ) (i + 1)
        (Preorder.frestrictLe (i + 1) z)) hdep hbd hFmeas
  · exact shiftedFunction_integrable_of_boundedDifferences (X := X)
      (ν := ProbabilityTheory.Kernel.traj (shiftedIndependentKernel (X := X) μ) (i + 1)
        (Preorder.frestrictLe (i + 1) w)) hdep hbd hFmeas
  · exact shiftedFunction_future_integrable_of_boundedDifferences (X := X) μ
      (f := f) (c := c) (N := N) (a := i + 1) hdep hbd hFmeas z
  · exact shiftedFunction_future_integrable_of_boundedDifferences (X := X) μ
      (f := f) (c := c) (N := N) (a := i + 1) hdep hbd hFmeas w

/-- Pointwise trajectory-integral representative of the shifted Doob
martingale differences. -/
noncomputable def shiftedTrajDiff {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    (F : ((n : ℕ) → shiftedSeqType X n) → ℝ) : ℕ →
      ((n : ℕ) → shiftedSeqType X n) → ℝ
  | 0 => fun _ => 0
  | k + 1 => fun z => shiftedTrajM μ F (k + 1) z - shiftedTrajM μ F k z

/-- Non-initial trajectory differences only depend on the prefix up to that
non-initial time. -/
lemma shiftedTrajDiff_succ_dependsOn {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    (F : ((n : ℕ) → shiftedSeqType X n) → ℝ) (i : ℕ) :
    DependsOn (shiftedTrajDiff μ F (i + 1)) (Set.Iic (i + 1)) := by
  intro z w hzw
  dsimp [shiftedTrajDiff]
  have h1 := shiftedTrajM_dependsOn (X := X) μ F (i + 1) hzw
  have h0 : shiftedTrajM μ F i z = shiftedTrajM μ F i w := by
    exact shiftedTrajM_dependsOn (X := X) μ F i
      (fun j hj => hzw j (le_trans hj (Nat.le_succ i)))
  rw [h1, h0]

/-- Coordinate bounded differences give the prefixwise diameter condition for
the shifted trajectory Doob differences. -/
lemma shiftedTrajDiff_diameter_of_boundedDifferences {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)] [∀ n, Nonempty (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N i : ℕ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N)
    (hFmeas : Measurable (shiftedFunction f))
    (hi : i < N)
    {z w : (n : ℕ) → shiftedSeqType X n}
    (hzw : Preorder.frestrictLe i z = Preorder.frestrictLe i w) :
    |shiftedTrajDiff μ (shiftedFunction f) (i + 1) z -
      shiftedTrajDiff μ (shiftedFunction f) (i + 1) w| ≤ c i := by
  have hM1 := shiftedTrajM_succ_diff_le_of_boundedDifferences_measurable (X := X) μ
    (f := f) (c := c) (N := N) (i := i) hdep hbd hFmeas hi hzw
  have hM0 : shiftedTrajM μ (shiftedFunction f) i z =
      shiftedTrajM μ (shiftedFunction f) i w := by
    exact shiftedTrajM_dependsOn (X := X) μ (shiftedFunction f) i
      (fun j hj => by
        have hfun := congrFun hzw ⟨j, by simpa [Finset.mem_Iic] using hj⟩
        simpa [Preorder.frestrictLe] using hfun)
  dsimp [shiftedTrajDiff]
  rw [hM0]
  simpa [sub_eq_add_neg, add_comm, add_left_comm, add_assoc] using hM1

/-- Doob conditional expectation process for a function and filtration. -/
noncomputable def doobM {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (ℱ : Filtration ℕ ‹MeasurableSpace Ω›) (F : Ω → ℝ) (k : ℕ) : Ω → ℝ :=
  μ[F | ℱ k]

/-- For the shifted independent trajectory, the Doob conditional expectation
with respect to the canonical product filtration is represented by integrating
over the future trajectory from the observed prefix. -/
lemma doobM_shifted_ae_eq_traj_integral {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {F : ((n : ℕ) → shiftedSeqType X n) → ℝ}
    (hFint : Integrable F (shiftedIndependentTraj (X := X) μ))
    (k : ℕ) :
    doobM (shiftedIndependentTraj (X := X) μ)
      (MeasureTheory.Filtration.piLE (X := shiftedSeqType X)) F k
      =ᵐ[shiftedIndependentTraj (X := X) μ]
      fun z => ∫ y, F y
        ∂ProbabilityTheory.Kernel.traj (shiftedIndependentKernel (X := X) μ) k
          (Preorder.frestrictLe k z) := by
  dsimp [doobM, shiftedIndependentTraj]
  exact ProbabilityTheory.Kernel.condExp_traj (κ := shiftedIndependentKernel (X := X) μ)
    (a := 0) (b := k) (x₀ := shiftedInitial (X := X)) (f := F) (zero_le k) hFint

/-- The preceding trajectory-integral formula expressed with `shiftedTrajM`. -/
lemma doobM_shifted_ae_eq_trajM {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {F : ((n : ℕ) → shiftedSeqType X n) → ℝ}
    (hFint : Integrable F (shiftedIndependentTraj (X := X) μ))
    (k : ℕ) :
    doobM (shiftedIndependentTraj (X := X) μ)
      (MeasureTheory.Filtration.piLE (X := shiftedSeqType X)) F k
      =ᵐ[shiftedIndependentTraj (X := X) μ]
      shiftedTrajM μ F k := by
  simpa [shiftedTrajM] using
    doobM_shifted_ae_eq_traj_integral (X := X) μ hFint k

/-- Doob martingale differences, with the first term centered by the global
expectation. -/
noncomputable def doobDiff {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (ℱ : Filtration ℕ ‹MeasurableSpace Ω›) (F : Ω → ℝ) : ℕ → Ω → ℝ
  | 0 => fun ω => doobM μ ℱ F 0 ω - ∫ ω, F ω ∂μ
  | k + 1 => fun ω => doobM μ ℱ F (k + 1) ω - doobM μ ℱ F k ω

/-- In the shifted independent product, the dummy first Doob difference is
zero almost surely. -/
lemma doobDiff_shifted_zero_ae_eq_zero {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {F : ((n : ℕ) → shiftedSeqType X n) → ℝ}
    (hFint : Integrable F (shiftedIndependentTraj (X := X) μ)) :
    doobDiff (shiftedIndependentTraj (X := X) μ)
      (MeasureTheory.Filtration.piLE (X := shiftedSeqType X)) F 0
      =ᵐ[shiftedIndependentTraj (X := X) μ] 0 := by
  have hM := doobM_shifted_ae_eq_traj_integral (X := X) μ hFint 0
  filter_upwards [hM] with z hz
  dsimp [doobDiff]
  rw [hz]
  have hprefix : Preorder.frestrictLe 0 z = shiftedInitial (X := X) :=
    frestrictLe_zero_shifted_eq_initial z
  rw [hprefix]
  change (∫ y, F y
        ∂ProbabilityTheory.Kernel.traj (shiftedIndependentKernel (X := X) μ) 0
          (shiftedInitial (X := X))) -
      (∫ y, F y
        ∂ProbabilityTheory.Kernel.traj (shiftedIndependentKernel (X := X) μ) 0
          (shiftedInitial (X := X))) = 0
  ring

/-- The `condExp`-based shifted Doob differences agree almost surely with the
pointwise trajectory representatives. -/
lemma doobDiff_shifted_ae_eq_trajDiff {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {F : ((n : ℕ) → shiftedSeqType X n) → ℝ}
    (hFint : Integrable F (shiftedIndependentTraj (X := X) μ))
    (k : ℕ) :
    doobDiff (shiftedIndependentTraj (X := X) μ)
      (MeasureTheory.Filtration.piLE (X := shiftedSeqType X)) F k
      =ᵐ[shiftedIndependentTraj (X := X) μ]
      shiftedTrajDiff μ F k := by
  cases k with
  | zero =>
      simpa [shiftedTrajDiff] using
        doobDiff_shifted_zero_ae_eq_zero (X := X) μ hFint
  | succ k =>
      have hM1 := doobM_shifted_ae_eq_trajM (X := X) μ hFint (k + 1)
      have hM0 := doobM_shifted_ae_eq_trajM (X := X) μ hFint k
      filter_upwards [hM1, hM0] with z hz1 hz0
      simp [doobDiff, shiftedTrajDiff, hz1, hz0]

/-- Under the regular conditional kernel given the product filtration up to
time `i`, the sampled trajectory has the same prefix up to `i` as the
conditioning trajectory. -/
lemma condExpKernel_piLE_ae_eq_prefix {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    {μ : Measure ((n : ℕ) → X n)} [IsProbabilityMeasure μ] (i : ℕ) :
    ∀ᵐ z ∂(μ.trim ((MeasureTheory.Filtration.piLE (X := X)).le i)),
      ∀ᵐ y ∂((@condExpKernel _ _ inferInstance μ inferInstance
        (MeasureTheory.Filtration.piLE (X := X) i)) z),
        Preorder.frestrictLe i y = Preorder.frestrictLe i z := by
  let Ω := ((n : ℕ) → X n)
  let ℱ : Filtration ℕ (MeasurableSpace.pi : MeasurableSpace Ω) :=
    MeasureTheory.Filtration.piLE (X := X)
  have hfirst : @Measurable Ω Ω (MeasurableSpace.pi : MeasurableSpace Ω) (ℱ i) id :=
    measurable_id'' (ℱ.le i)
  have hsecond : @Measurable Ω Ω (MeasurableSpace.pi : MeasurableSpace Ω)
      (MeasurableSpace.pi : MeasurableSpace Ω) id := measurable_id
  have hpair : @Measurable Ω (Ω × Ω) (MeasurableSpace.pi : MeasurableSpace Ω)
      ((ℱ i).prod (MeasurableSpace.pi : MeasurableSpace Ω)) (fun ω : Ω => (ω, ω)) :=
    hfirst.prodMk hsecond
  have hp : MeasurableSet[(ℱ i).prod (MeasurableSpace.pi : MeasurableSpace Ω)]
      {p : Ω × Ω | Preorder.frestrictLe i p.2 = Preorder.frestrictLe i p.1} := by
    have hprefix : @Measurable Ω ((j : Finset.Iic i) → X j)
        (ℱ i) (MeasurableSpace.pi : MeasurableSpace ((j : Finset.Iic i) → X j))
        (Preorder.frestrictLe i) := by
      rw [MeasureTheory.Filtration.piLE_eq_comap_frestrictLe (X := X) i]
      exact Measurable.of_comap_le le_rfl
    have hfst0 : @Measurable (Ω × Ω) Ω
        ((ℱ i).prod (MeasurableSpace.pi : MeasurableSpace Ω))
        (ℱ i) Prod.fst := measurable_fst
    have hfst : Measurable[(ℱ i).prod (MeasurableSpace.pi : MeasurableSpace Ω)]
        (fun p : Ω × Ω => Preorder.frestrictLe i p.1) := hprefix.comp hfst0
    have hsnd0 : @Measurable (Ω × Ω) Ω
        ((ℱ i).prod (MeasurableSpace.pi : MeasurableSpace Ω))
        (MeasurableSpace.pi : MeasurableSpace Ω) Prod.snd := measurable_snd
    have hsnd : Measurable[(ℱ i).prod (MeasurableSpace.pi : MeasurableSpace Ω)]
        (fun p : Ω × Ω => Preorder.frestrictLe i p.2) := by
      exact (Preorder.measurable_frestrictLe i).comp hsnd0
    letI := measurableEqOfStandardBorel ((j : Finset.Iic i) → X j)
    exact measurableSet_eq_fun hsnd hfst
  have hpair_ae : @AEMeasurable Ω (Ω × Ω)
      ((ℱ i).prod (MeasurableSpace.pi : MeasurableSpace Ω))
      (MeasurableSpace.pi : MeasurableSpace Ω) (fun ω : Ω => (ω, ω)) μ := by
    exact ⟨fun ω : Ω => (ω, ω), hpair, ae_eq_refl _⟩
  have hdiag : ∀ᵐ p ∂(@Measure.map Ω (Ω × Ω) _ ((ℱ i).prod
        (MeasurableSpace.pi : MeasurableSpace Ω)) (fun ω : Ω => (ω, ω)) μ),
      Preorder.frestrictLe i p.2 = Preorder.frestrictLe i p.1 := by
    rw [ae_map_iff hpair_ae hp]
    exact ae_of_all _ (fun ω => rfl)
  have hcomp : ∀ᵐ p ∂(μ.trim (ℱ.le i) ⊗ₘ
      (@condExpKernel Ω _ inferInstance μ inferInstance (ℱ i))),
      Preorder.frestrictLe i p.2 = Preorder.frestrictLe i p.1 := by
    rw [ProbabilityTheory.compProd_trim_condExpKernel (μ := μ) (m := ℱ i) (hm := ℱ.le i)]
    exact hdiag
  simpa [Ω, ℱ] using Measure.ae_ae_of_ae_compProd hcomp

/-- Prefixwise diameter of the pointwise shifted Doob representative yields
the conditional interval hypothesis for the `condExp`-based Doob difference. -/
lemma doobDiff_shifted_conditional_range_of_trajDiff_diameter {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {F : ((n : ℕ) → shiftedSeqType X n) → ℝ}
    (hFint : Integrable F (shiftedIndependentTraj (X := X) μ))
    {c : ℝ} (hc : 0 ≤ c) (i : ℕ)
    (hdiam : ∀ z w,
      Preorder.frestrictLe i z = Preorder.frestrictLe i w →
        |shiftedTrajDiff μ F (i + 1) z - shiftedTrajDiff μ F (i + 1) w| ≤ c) :
    ∀ᵐ z ∂((shiftedIndependentTraj (X := X) μ).trim
        ((MeasureTheory.Filtration.piLE (X := shiftedSeqType X)).le i)),
      ∃ a : ℝ, ∀ᵐ y ∂((@condExpKernel _ _ inferInstance
        (shiftedIndependentTraj (X := X) μ) inferInstance
        (MeasureTheory.Filtration.piLE (X := shiftedSeqType X) i)) z),
        doobDiff (shiftedIndependentTraj (X := X) μ)
          (MeasureTheory.Filtration.piLE (X := shiftedSeqType X)) F (i + 1) y ∈
          Set.Icc a (a + c) := by
  let P := shiftedIndependentTraj (X := X) μ
  let ℱ : Filtration ℕ (MeasurableSpace.pi : MeasurableSpace ((n : ℕ) → shiftedSeqType X n)) :=
    MeasureTheory.Filtration.piLE (X := shiftedSeqType X)
  have hEqGlobal := doobDiff_shifted_ae_eq_trajDiff (X := X) μ hFint (i + 1)
  have hEqCond : ∀ᵐ z ∂(P.trim (ℱ.le i)),
      ∀ᵐ y ∂((@condExpKernel _ _ inferInstance P inferInstance (ℱ i)) z),
        doobDiff P ℱ F (i + 1) y = shiftedTrajDiff μ F (i + 1) y := by
    refine Measure.ae_ae_of_ae_comp ?_
    rw [ProbabilityTheory.condExpKernel_comp_trim (μ := P) (m := ℱ i) (hm := ℱ.le i)]
    exact hEqGlobal
  have hPrefix := condExpKernel_piLE_ae_eq_prefix
    (X := shiftedSeqType X) (μ := P) i
  filter_upwards [hEqCond, hPrefix] with z hEqz hPrefixz
  let α : Type u := {y : ((n : ℕ) → shiftedSeqType X n) //
      Preorder.frestrictLe i y = Preorder.frestrictLe i z}
  haveI : Nonempty α := ⟨⟨z, rfl⟩⟩
  let g : α → ℝ := fun y => shiftedTrajDiff μ F (i + 1) y.1
  have hdiam_g : ∀ x y : α, |g x - g y| ≤ c := by
    intro x y
    exact hdiam x.1 y.1 (x.2.trans y.2.symm)
  rcases exists_Icc_length_of_pairwise_abs_sub_le (α := α) (g := g) hc hdiam_g with ⟨a, ha⟩
  refine ⟨a, ?_⟩
  filter_upwards [hEqz, hPrefixz] with y hy_eq hy_prefix
  rw [hy_eq]
  exact ha ⟨y, hy_prefix⟩

/-- The Doob differences are adapted to the same filtration. -/
lemma doobDiff_stronglyAdapted {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (ℱ : Filtration ℕ ‹MeasurableSpace Ω›) (F : Ω → ℝ) :
    StronglyAdapted ℱ (doobDiff μ ℱ F) := by
  intro k
  cases k with
  | zero =>
      dsimp [doobDiff, doobM]
      exact stronglyMeasurable_condExp.sub stronglyMeasurable_const
  | succ k =>
      dsimp [doobDiff, doobM]
      exact stronglyMeasurable_condExp.sub
        (stronglyMeasurable_condExp.mono (ℱ.mono (Nat.le_succ k)))

/-- Telescoping identity for the sum of the first `N + 1` Doob differences. -/
lemma doobDiff_sum_range_succ {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (ℱ : Filtration ℕ ‹MeasurableSpace Ω›) (F : Ω → ℝ) (N : ℕ) (ω : Ω) :
    ∑ i ∈ Finset.range (N + 1), doobDiff μ ℱ F i ω =
      doobM μ ℱ F N ω - ∫ ω, F ω ∂μ := by
  induction N with
  | zero => simp [doobDiff, doobM]
  | succ N ih =>
      rw [Finset.sum_range_succ]
      change (∑ i ∈ Finset.range (N + 1), doobDiff μ ℱ F i ω) +
          (doobM μ ℱ F (N + 1) ω - doobM μ ℱ F N ω) =
        doobM μ ℱ F (N + 1) ω - ∫ ω, F ω ∂μ
      rw [ih]
      ring

/-- If `F` is measurable with respect to filtration level `N`, its Doob
conditional expectation at time `N` is `F` almost surely. -/
lemma doobM_ae_eq_self_of_aestronglyMeasurable {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (ℱ : Filtration ℕ ‹MeasurableSpace Ω›) {F : Ω → ℝ} {N : ℕ}
    (hFmeas : AEStronglyMeasurable[ℱ N] F μ)
    (hFint : Integrable F μ) :
    doobM μ ℱ F N =ᵐ[μ] F := by
  dsimp [doobM]
  exact condExp_of_aestronglyMeasurable' (ℱ.le N) hFmeas hFint

/-- The first `N + 1` Doob differences telescope to the centered function
whenever the function is measurable at filtration level `N`. -/
lemma doobDiff_sum_range_succ_ae_eq_centered {Ω : Type*} [MeasurableSpace Ω]
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (ℱ : Filtration ℕ ‹MeasurableSpace Ω›) {F : Ω → ℝ} {N : ℕ}
    (hFmeas : AEStronglyMeasurable[ℱ N] F μ)
    (hFint : Integrable F μ) :
    (fun ω => ∑ i ∈ Finset.range (N + 1), doobDiff μ ℱ F i ω)
      =ᵐ[μ] fun ω => F ω - ∫ ω, F ω ∂μ := by
  have hM := doobM_ae_eq_self_of_aestronglyMeasurable (μ := μ) ℱ hFmeas hFint
  filter_upwards [hM] with ω hω
  rw [doobDiff_sum_range_succ]
  rw [hω]

/-- Every non-initial Doob difference has zero conditional mean with respect
to the previous filtration level, expressed through the regular conditional
expectation kernel. -/
lemma doobDiff_cond_integral_eq_zero {Ω : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (ℱ : Filtration ℕ ‹MeasurableSpace Ω›) {F : Ω → ℝ} (i : ℕ) :
    ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
      ∫ ω, doobDiff μ ℱ F (i + 1) ω
        ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
          (ℱ i)) ω') = 0 := by
  let Y : Ω → ℝ := doobDiff μ ℱ F (i + 1)
  have hYint : Integrable Y μ := by
    dsimp [Y, doobDiff]
    exact integrable_condExp.sub integrable_condExp
  have hkernel :=
    condExp_ae_eq_trim_integral_condExpKernel (μ := μ) (m := ℱ i)
      (hm := ℱ.le i) hYint
  have hcond_mu : μ[Y | ℱ i] =ᵐ[μ] 0 := by
    dsimp [Y, doobDiff]
    have hsub := condExp_sub (μ := μ)
      (f := doobM μ ℱ F (i + 1)) (g := doobM μ ℱ F i)
      integrable_condExp integrable_condExp (ℱ i)
    have htower1 := MeasureTheory.Filtration.condExp_condExp (μ := μ) F ℱ (Nat.le_succ i)
    have htower0 := MeasureTheory.Filtration.condExp_condExp (μ := μ) F ℱ (le_rfl : i ≤ i)
    filter_upwards [hsub, htower1, htower0] with ω hs h1 h0
    change μ[doobM μ ℱ F (i + 1) - doobM μ ℱ F i | ℱ i] ω = 0
    rw [hs]
    change μ[μ[F | ℱ (i + 1)] | ℱ i] ω - μ[μ[F | ℱ i] | ℱ i] ω = 0
    have h1' : μ[μ[F | ℱ (i + 1)] | ℱ i] ω = μ[F | ℱ i] ω := by
      simpa using h1
    rw [h1', h0]
    simp
  have hcond_trim : μ[Y | ℱ i] =ᵐ[μ.trim (ℱ.le i)] 0 := by
    exact StronglyMeasurable.ae_eq_trim_of_stronglyMeasurable (ℱ.le i)
      stronglyMeasurable_condExp stronglyMeasurable_zero hcond_mu
  filter_upwards [hkernel, hcond_trim] with ω' hk hz
  rw [← hk, hz]
  simp

/-- Compatibility spelling for the canonical martingale-difference producer
`martingaleDifference_upperTail`. -/
@[deprecated martingaleDifference_upperTail (since := "2026-09-14")]
theorem mcdiarmid_martingale_difference_upper_tail
    [StandardBorelSpace Ω] [IsProbabilityMeasure μ]
    {Y : ℕ → Ω → ℝ} {ℱ : Filtration ℕ ‹MeasurableSpace Ω›}
    {c : ℕ → ℝ} {n : ℕ} {t : ℝ}
    (h_adapted : StronglyAdapted ℱ Y)
    (h0 : HasSubgaussianMGF (Y 0) (boundedDifferencesSubgaussianProxy c 0) μ)
    (h_subG : ∀ i < n - 1,
      HasCondSubgaussianMGF (ℱ i) (ℱ.le i) (Y (i + 1))
        (boundedDifferencesSubgaussianProxy c (i + 1)) μ)
    (ht : 0 ≤ t) :
    μ.real {ω | t ≤ ∑ i ∈ Finset.range n, Y i ω}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c n) := by
  exact martingaleDifference_upperTail h_adapted h0 h_subG ht

/-- Bounded martingale-difference form of HDP Theorem 2.9.1.  If the increments
are adapted, globally bounded in intervals of length `cᵢ`, and have zero
conditional means with respect to the previous filtration level, then the
McDiarmid/Azuma exponent is exactly `exp(-2 t² / ∑ᵢ cᵢ²)`. -/
theorem mcdiarmid_martingale_difference_bounded_upper_tail
    [StandardBorelSpace Ω] [IsProbabilityMeasure μ]
    {Y : ℕ → Ω → ℝ} {ℱ : Filtration ℕ ‹MeasurableSpace Ω›}
    {a c : ℕ → ℝ} {n : ℕ} {t : ℝ}
    (h_adapted : StronglyAdapted ℱ Y)
    (hc : ∀ i, 0 ≤ c i)
    (hYm : ∀ i, AEMeasurable (Y i) μ)
    (hbound : ∀ i, ∀ᵐ ω ∂μ, Y i ω ∈ Set.Icc (a i) (a i + c i))
    (hmean0 : ∫ ω, Y 0 ω ∂μ = 0)
    (hcond_meas : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        AEMeasurable (Y (i + 1))
          ((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance (ℱ i)) ω'))
    (hcond_bound : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∀ᵐ ω ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
          (ℱ i)) ω'),
          Y (i + 1) ω ∈ Set.Icc (a (i + 1)) (a (i + 1) + c (i + 1)))
    (hcond_mean : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∫ ω, Y (i + 1) ω
          ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
            (ℱ i)) ω') = 0)
    (ht : 0 ≤ t) :
    μ.real {ω | t ≤ ∑ i ∈ Finset.range n, Y i ω}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c n) := by
  have proxy_eq (i : ℕ) :
      ((‖(a i + c i) - a i‖₊ / 2) ^ 2 : ℝ≥0) =
        boundedDifferencesSubgaussianProxy c i := by
    ext
    have hdiff : a i + c i - a i = c i := by ring
    rw [hdiff]
    change ((‖c i‖₊ : ℝ) / 2) ^ 2 = c i ^ 2 / 4
    rw [coe_nnnorm, Real.norm_eq_abs, abs_of_nonneg (hc i)]
    ring
  have proxy_eq' (i : ℕ) :
      ((‖c i‖₊ / 2) ^ 2 : ℝ≥0) =
        boundedDifferencesSubgaussianProxy c i := by
    simpa using proxy_eq i
  have h0 :
      HasSubgaussianMGF (Y 0) (boundedDifferencesSubgaussianProxy c 0) μ := by
    have h :=
      ProbabilityTheory.hasSubgaussianMGF_of_mem_Icc_of_integral_eq_zero
        (μ := μ) (X := Y 0) (a := a 0) (b := a 0 + c 0)
        (hYm 0) (hbound 0) hmean0
    simpa [proxy_eq' 0] using h
  have h_subG : ∀ i < n - 1,
      HasCondSubgaussianMGF (ℱ i) (ℱ.le i) (Y (i + 1))
        (boundedDifferencesSubgaussianProxy c (i + 1)) μ := by
    intro i hi
    have h :=
      hasCondSubgaussianMGF_of_cond_mem_Icc_of_cond_integral_eq_zero
        (μ := μ) (m := ℱ i) (hm := ℱ.le i)
        (X := Y (i + 1)) (a := a (i + 1)) (b := a (i + 1) + c (i + 1))
        (hYm (i + 1)) (hbound (i + 1))
        (hcond_meas i hi) (hcond_bound i hi) (hcond_mean i hi)
    simpa [proxy_eq' (i + 1)] using h
  exact martingaleDifference_upperTail
    (μ := μ) (Y := Y) (ℱ := ℱ) (c := c) (n := n) (t := t)
    h_adapted h0 h_subG ht

/-- Bounded martingale-difference McDiarmid form with past-dependent interval
locations.  This is the form naturally produced by the Doob martingale of a
bounded-differences function: after conditioning on the past, the next
increment is centered and lies in some interval of deterministic length `cᵢ`,
but the interval's left endpoint may depend on the past. -/
theorem mcdiarmid_martingale_difference_conditional_range_upper_tail
    [StandardBorelSpace Ω] [IsProbabilityMeasure μ]
    {Y : ℕ → Ω → ℝ} {ℱ : Filtration ℕ ‹MeasurableSpace Ω›}
    {c : ℕ → ℝ} {n : ℕ} {t : ℝ}
    (h_adapted : StronglyAdapted ℱ Y)
    (hc : ∀ i, 0 ≤ c i)
    (hc0 : c 0 = 0)
    (hYm : ∀ i, AEMeasurable (Y i) μ)
    (hglobal_abs : ∀ i, ∀ᵐ ω ∂μ, |Y i ω| ≤ c i)
    (h0_zero : Y 0 =ᵐ[μ] 0)
    (hcond_meas : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        AEMeasurable (Y (i + 1))
          ((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance (ℱ i)) ω'))
    (hcond_bound : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∃ a : ℝ, ∀ᵐ ω ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
          (ℱ i)) ω'),
          Y (i + 1) ω ∈ Set.Icc a (a + c (i + 1)))
    (hcond_mean : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∫ ω, Y (i + 1) ω
          ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
            (ℱ i)) ω') = 0)
    (ht : 0 ≤ t) :
    μ.real {ω | t ≤ ∑ i ∈ Finset.range n, Y i ω}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c n) := by
  have proxy_eq (i : ℕ) :
      ((‖c i‖₊ / 2) ^ 2 : ℝ≥0) =
        boundedDifferencesSubgaussianProxy c i := by
    ext
    change ((‖c i‖₊ : ℝ) / 2) ^ 2 = c i ^ 2 / 4
    rw [coe_nnnorm, Real.norm_eq_abs, abs_of_nonneg (hc i)]
    ring
  have h0 :
      HasSubgaussianMGF (Y 0) (boundedDifferencesSubgaussianProxy c 0) μ := by
    have hzero : HasSubgaussianMGF (0 : Ω → ℝ) 0 μ := by simp
    have hY0 : HasSubgaussianMGF (Y 0) 0 μ :=
      hzero.congr h0_zero.symm
    simpa [boundedDifferencesSubgaussianProxy, hc0] using hY0
  have h_subG : ∀ i < n - 1,
      HasCondSubgaussianMGF (ℱ i) (ℱ.le i) (Y (i + 1))
        (boundedDifferencesSubgaussianProxy c (i + 1)) μ := by
    intro i hi
    have h :=
      hasCondSubgaussianMGF_of_cond_exists_mem_Icc_length_of_cond_integral_eq_zero
        (μ := μ) (m := ℱ i) (hm := ℱ.le i)
        (X := Y (i + 1)) (c := c (i + 1))
        (hc (i + 1)) (hYm (i + 1)) (hglobal_abs (i + 1))
        (hcond_meas i hi) (hcond_bound i hi) (hcond_mean i hi)
    simpa [proxy_eq (i + 1)] using h
  exact martingaleDifference_upperTail
    (μ := μ) (Y := Y) (ℱ := ℱ) (c := c) (n := n) (t := t)
    h_adapted h0 h_subG ht

/-- Conditional-range martingale-difference McDiarmid form with the global
absolute bound derived from measurable increments, conditional interval
ranges, and zero conditional means. -/
theorem mcdiarmid_martingale_difference_conditional_range_upper_tail_of_measurable
    [StandardBorelSpace Ω] [IsProbabilityMeasure μ]
    {Y : ℕ → Ω → ℝ} {ℱ : Filtration ℕ ‹MeasurableSpace Ω›}
    {c : ℕ → ℝ} {n : ℕ} {t : ℝ}
    (h_adapted : StronglyAdapted ℱ Y)
    (hc : ∀ i, 0 ≤ c i)
    (hc0 : c 0 = 0)
    (hYm : ∀ i, Measurable (Y i))
    (h0_zero : Y 0 =ᵐ[μ] 0)
    (hcond_meas : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        AEMeasurable (Y (i + 1))
          ((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance (ℱ i)) ω'))
    (hcond_bound : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∃ a : ℝ, ∀ᵐ ω ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
          (ℱ i)) ω'),
          Y (i + 1) ω ∈ Set.Icc a (a + c (i + 1)))
    (hcond_mean : ∀ i < n - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∫ ω, Y (i + 1) ω
          ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
            (ℱ i)) ω') = 0)
    (ht : 0 ≤ t) :
    μ.real {ω | t ≤ ∑ i ∈ Finset.range n, Y i ω}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c n) := by
  have proxy_eq (i : ℕ) :
      ((‖c i‖₊ / 2) ^ 2 : ℝ≥0) =
        boundedDifferencesSubgaussianProxy c i := by
    ext
    change ((‖c i‖₊ : ℝ) / 2) ^ 2 = c i ^ 2 / 4
    rw [coe_nnnorm, Real.norm_eq_abs, abs_of_nonneg (hc i)]
    ring
  have h0 :
      HasSubgaussianMGF (Y 0) (boundedDifferencesSubgaussianProxy c 0) μ := by
    have hzero : HasSubgaussianMGF (0 : Ω → ℝ) 0 μ := by simp
    have hY0 : HasSubgaussianMGF (Y 0) 0 μ :=
      hzero.congr h0_zero.symm
    simpa [boundedDifferencesSubgaussianProxy, hc0] using hY0
  have h_subG : ∀ i < n - 1,
      HasCondSubgaussianMGF (ℱ i) (ℱ.le i) (Y (i + 1))
        (boundedDifferencesSubgaussianProxy c (i + 1)) μ := by
    intro i hi
    have h :=
      hasCondSubgaussianMGF_of_cond_exists_mem_Icc_length_of_cond_integral_eq_zero_of_measurable
        (μ := μ) (m := ℱ i) (hm := ℱ.le i)
        (X := Y (i + 1)) (c := c (i + 1))
        (hc (i + 1)) (hYm (i + 1))
        (hcond_meas i hi) (hcond_bound i hi) (hcond_mean i hi)
    simpa [proxy_eq (i + 1)] using h
  exact martingaleDifference_upperTail
    (μ := μ) (Y := Y) (ℱ := ℱ) (c := c) (n := n) (t := t)
    h_adapted h0 h_subG ht

/-- Doob-process McDiarmid form.  Once the Doob increments of `F` are known
to have zero first increment and conditionally centered ranges of deterministic
lengths `cᵢ`, the martingale tail bound applies directly to the centered
function `F - E F`. -/
theorem mcdiarmid_doob_conditional_range_upper_tail
    {Ω : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {ℱ : Filtration ℕ ‹MeasurableSpace Ω›} {F : Ω → ℝ}
    {c : ℕ → ℝ} {N : ℕ} {t : ℝ}
    (hFmeas : AEStronglyMeasurable[ℱ N] F μ)
    (hFint : Integrable F μ)
    (hc : ∀ i, 0 ≤ c i)
    (hc0 : c 0 = 0)
    (h0_zero : doobDiff μ ℱ F 0 =ᵐ[μ] 0)
    (hglobal_abs : ∀ i, ∀ᵐ ω ∂μ, |doobDiff μ ℱ F i ω| ≤ c i)
    (hcond_meas : ∀ i < (N + 1) - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        AEMeasurable (doobDiff μ ℱ F (i + 1))
          ((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance (ℱ i)) ω'))
    (hcond_bound : ∀ i < (N + 1) - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∃ a : ℝ, ∀ᵐ ω ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
          (ℱ i)) ω'),
          doobDiff μ ℱ F (i + 1) ω ∈ Set.Icc a (a + c (i + 1)))
    (hcond_mean : ∀ i < (N + 1) - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∫ ω, doobDiff μ ℱ F (i + 1) ω
          ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
            (ℱ i)) ω') = 0)
    (ht : 0 ≤ t) :
    μ.real {ω | t ≤ F ω - ∫ ω, F ω ∂μ}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c (N + 1)) := by
  let Y : ℕ → Ω → ℝ := doobDiff μ ℱ F
  have h_adapted : StronglyAdapted ℱ Y := doobDiff_stronglyAdapted μ ℱ F
  have hYm : ∀ i, AEMeasurable (Y i) μ := by
    intro i
    exact ((h_adapted i).mono (ℱ.le i)).aemeasurable (μ := μ)
  have htail :=
    mcdiarmid_martingale_difference_conditional_range_upper_tail
      (μ := μ) (Y := Y) (ℱ := ℱ) (c := c) (n := N + 1) (t := t)
      h_adapted hc hc0 hYm hglobal_abs h0_zero
      hcond_meas hcond_bound hcond_mean ht
  have hsum := doobDiff_sum_range_succ_ae_eq_centered (μ := μ) ℱ hFmeas hFint
  have hevent : {ω | t ≤ ∑ i ∈ Finset.range (N + 1), Y i ω}
      =ᵐ[μ] {ω | t ≤ F ω - ∫ ω, F ω ∂μ} := by
    filter_upwards [hsum] with ω hω
    dsimp [Y] at hω ⊢
    change (t ≤ ∑ i ∈ Finset.range (N + 1), doobDiff μ ℱ F i ω) =
      (t ≤ F ω - ∫ ω, F ω ∂μ)
    rw [hω]
  rw [← MeasureTheory.measureReal_congr hevent]
  exact htail

/-- Doob-process McDiarmid form with the zero conditional means supplied by
the Doob tower property.  It remains only to provide the conditional interval
locations and global absolute bounds for the increments. -/
theorem mcdiarmid_doob_conditional_range_upper_tail_of_ranges
    {Ω : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {ℱ : Filtration ℕ ‹MeasurableSpace Ω›} {F : Ω → ℝ}
    {c : ℕ → ℝ} {N : ℕ} {t : ℝ}
    (hFmeas : AEStronglyMeasurable[ℱ N] F μ)
    (hFint : Integrable F μ)
    (hc : ∀ i, 0 ≤ c i)
    (hc0 : c 0 = 0)
    (h0_zero : doobDiff μ ℱ F 0 =ᵐ[μ] 0)
    (hglobal_abs : ∀ i, ∀ᵐ ω ∂μ, |doobDiff μ ℱ F i ω| ≤ c i)
    (hcond_meas : ∀ i < (N + 1) - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        AEMeasurable (doobDiff μ ℱ F (i + 1))
          ((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance (ℱ i)) ω'))
    (hcond_bound : ∀ i < (N + 1) - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∃ a : ℝ, ∀ᵐ ω ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
          (ℱ i)) ω'),
          doobDiff μ ℱ F (i + 1) ω ∈ Set.Icc a (a + c (i + 1)))
    (ht : 0 ≤ t) :
    μ.real {ω | t ≤ F ω - ∫ ω, F ω ∂μ}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c (N + 1)) := by
  refine mcdiarmid_doob_conditional_range_upper_tail
    (μ := μ) (ℱ := ℱ) (F := F) (c := c) (N := N) (t := t)
    hFmeas hFint hc hc0 h0_zero hglobal_abs hcond_meas hcond_bound ?_ ht
  intro i _hi
  exact doobDiff_cond_integral_eq_zero (μ := μ) ℱ i

/-- Doob-process McDiarmid form with global absolute bounds derived from
conditional interval ranges and zero conditional means. -/
theorem mcdiarmid_doob_conditional_range_upper_tail_of_ranges_measurable
    {Ω : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {ℱ : Filtration ℕ ‹MeasurableSpace Ω›} {F : Ω → ℝ}
    {c : ℕ → ℝ} {N : ℕ} {t : ℝ}
    (hFmeas : AEStronglyMeasurable[ℱ N] F μ)
    (hFint : Integrable F μ)
    (hc : ∀ i, 0 ≤ c i)
    (hc0 : c 0 = 0)
    (h0_zero : doobDiff μ ℱ F 0 =ᵐ[μ] 0)
    (hcond_meas : ∀ i < (N + 1) - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        AEMeasurable (doobDiff μ ℱ F (i + 1))
          ((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance (ℱ i)) ω'))
    (hcond_bound : ∀ i < (N + 1) - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∃ a : ℝ, ∀ᵐ ω ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
          (ℱ i)) ω'),
          doobDiff μ ℱ F (i + 1) ω ∈ Set.Icc a (a + c (i + 1)))
    (ht : 0 ≤ t) :
    μ.real {ω | t ≤ F ω - ∫ ω, F ω ∂μ}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c (N + 1)) := by
  let Y : ℕ → Ω → ℝ := doobDiff μ ℱ F
  have h_adapted : StronglyAdapted ℱ Y := doobDiff_stronglyAdapted μ ℱ F
  have hYm : ∀ i, Measurable (Y i) := by
    intro i
    exact ((h_adapted i).mono (ℱ.le i)).measurable
  have hcond_mean : ∀ i < (N + 1) - 1,
      ∀ᵐ ω' ∂(μ.trim (ℱ.le i)),
        ∫ ω, Y (i + 1) ω
          ∂((@condExpKernel Ω ‹MeasurableSpace Ω› inferInstance μ inferInstance
            (ℱ i)) ω') = 0 := by
    intro i _hi
    exact doobDiff_cond_integral_eq_zero (μ := μ) ℱ i
  have htail := mcdiarmid_martingale_difference_conditional_range_upper_tail_of_measurable
    (μ := μ) (Y := Y) (ℱ := ℱ) (c := c) (n := N + 1) (t := t)
    h_adapted hc hc0 hYm h0_zero hcond_meas hcond_bound hcond_mean ht
  have hsum := doobDiff_sum_range_succ_ae_eq_centered (μ := μ) ℱ hFmeas hFint
  have hevent : {ω | t ≤ ∑ i ∈ Finset.range (N + 1), Y i ω}
      =ᵐ[μ] {ω | t ≤ F ω - ∫ ω, F ω ∂μ} := by
    filter_upwards [hsum] with ω hω
    dsimp [Y] at hω ⊢
    change (t ≤ ∑ i ∈ Finset.range (N + 1), doobDiff μ ℱ F i ω) =
      (t ≤ F ω - ∫ ω, F ω ∂μ)
    rw [hω]
  rw [← MeasureTheory.measureReal_congr hevent]
  exact htail

/-- Shifted independent-product McDiarmid form reduced to a pointwise diameter
condition for the trajectory Doob representatives.  The remaining
book-specific step is to prove this diameter condition from the coordinate
bounded-differences hypothesis on the original function. -/
theorem mcdiarmid_shifted_doob_of_trajDiff_diameter {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {F : ((n : ℕ) → shiftedSeqType X n) → ℝ}
    {c : ℕ → ℝ} {N : ℕ} {t : ℝ}
    (hFmeas : AEStronglyMeasurable[MeasureTheory.Filtration.piLE (X := shiftedSeqType X) N]
      F (shiftedIndependentTraj (X := X) μ))
    (hFint : Integrable F (shiftedIndependentTraj (X := X) μ))
    (hc : ∀ i, 0 ≤ c i)
    (hglobal_abs : ∀ i, ∀ᵐ z ∂(shiftedIndependentTraj (X := X) μ),
      |doobDiff (shiftedIndependentTraj (X := X) μ)
        (MeasureTheory.Filtration.piLE (X := shiftedSeqType X)) F i z| ≤
        shiftedBoundedDifferenceConstants c i)
    (hcond_meas : ∀ i < N,
      ∀ᵐ z ∂((shiftedIndependentTraj (X := X) μ).trim
        ((MeasureTheory.Filtration.piLE (X := shiftedSeqType X)).le i)),
        AEMeasurable
          (doobDiff (shiftedIndependentTraj (X := X) μ)
            (MeasureTheory.Filtration.piLE (X := shiftedSeqType X)) F (i + 1))
          ((@condExpKernel _ _ inferInstance (shiftedIndependentTraj (X := X) μ)
            inferInstance (MeasureTheory.Filtration.piLE (X := shiftedSeqType X) i)) z))
    (hdiam : ∀ i < N, ∀ z w,
      Preorder.frestrictLe i z = Preorder.frestrictLe i w →
        |shiftedTrajDiff μ F (i + 1) z - shiftedTrajDiff μ F (i + 1) w| ≤ c i)
    (ht : 0 ≤ t) :
    (shiftedIndependentTraj (X := X) μ).real
        {z | t ≤ F z - ∫ z, F z ∂(shiftedIndependentTraj (X := X) μ)}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c N) := by
  let P := shiftedIndependentTraj (X := X) μ
  let ℱ : Filtration ℕ (MeasurableSpace.pi : MeasurableSpace ((n : ℕ) → shiftedSeqType X n)) :=
    MeasureTheory.Filtration.piLE (X := shiftedSeqType X)
  let c' := shiftedBoundedDifferenceConstants c
  have hc' : ∀ i, 0 ≤ c' i := shiftedBoundedDifferenceConstants_nonneg hc
  have hc0 : c' 0 = 0 := rfl
  have h0_zero : doobDiff P ℱ F 0 =ᵐ[P] 0 := by
    simpa [P, ℱ] using doobDiff_shifted_zero_ae_eq_zero (X := X) μ hFint
  have hcond_bound : ∀ i < (N + 1) - 1,
      ∀ᵐ z ∂(P.trim (ℱ.le i)),
        ∃ a : ℝ, ∀ᵐ y ∂((@condExpKernel _ _ inferInstance P inferInstance (ℱ i)) z),
          doobDiff P ℱ F (i + 1) y ∈ Set.Icc a (a + c' (i + 1)) := by
    intro i hi
    have hiN : i < N := by omega
    have h := doobDiff_shifted_conditional_range_of_trajDiff_diameter
      (X := X) μ hFint (hc i) i (hdiam i hiN)
    simpa [P, ℱ, c'] using h
  have hcond_meas' : ∀ i < (N + 1) - 1,
      ∀ᵐ z ∂(P.trim (ℱ.le i)),
        AEMeasurable (doobDiff P ℱ F (i + 1))
          ((@condExpKernel _ _ inferInstance P inferInstance (ℱ i)) z) := by
    intro i hi
    have hiN : i < N := by omega
    simpa [P, ℱ] using hcond_meas i hiN
  have htail := mcdiarmid_doob_conditional_range_upper_tail_of_ranges
    (μ := P) (ℱ := ℱ) (F := F) (c := c') (N := N) (t := t)
    hFmeas hFint hc' hc0 h0_zero hglobal_abs hcond_meas' hcond_bound ht
  simpa [P, c', boundedDifferencesVarianceSum_shifted_succ] using htail

/-- HDP Theorem 2.9.1 in the shifted independent-product model.  A
measurable function of the first `N` genuine independent coordinates satisfying
coordinate bounded differences obeys McDiarmid's upper-tail bound with the
book exponent `exp (-2 t² / ∑ᵢ cᵢ²)`. -/
theorem mcdiarmid_shifted_boundedDifferences {X : ℕ → Type u}
    [∀ n, MeasurableSpace (X n)] [∀ n, StandardBorelSpace (X n)]
    (μ : (n : ℕ) → Measure (X n)) [∀ n, IsProbabilityMeasure (μ n)]
    {f : ((n : ℕ) → X n) → ℝ} {c : ℕ → ℝ} {N : ℕ} {t : ℝ}
    (hdep : DependsOn f (Set.Iio N))
    (hbd : SeqBoundedDifferences f c N)
    (hFmeas : Measurable (shiftedFunction f))
    (hc : ∀ i, 0 ≤ c i)
    (ht : 0 ≤ t) :
    (shiftedIndependentTraj (X := X) μ).real
        {z | t ≤ shiftedFunction f z - ∫ z, shiftedFunction f z ∂(shiftedIndependentTraj (X := X) μ)}
      ≤ Real.exp (-2 * t ^ 2 / boundedDifferencesVarianceSum c N) := by
  haveI : ∀ n, Nonempty (X n) := fun n => nonempty_of_isProbabilityMeasure (μ n)
  let P := shiftedIndependentTraj (X := X) μ
  let ℱ : Filtration ℕ (MeasurableSpace.pi : MeasurableSpace ((n : ℕ) → shiftedSeqType X n)) :=
    MeasureTheory.Filtration.piLE (X := shiftedSeqType X)
  let F : ((n : ℕ) → shiftedSeqType X n) → ℝ := shiftedFunction f
  let c' := shiftedBoundedDifferenceConstants c
  have hFdep : DependsOn F (Set.Iic N) := shiftedFunction_dependsOn (X := X) (f := f) hdep
  have hFmeasN : AEStronglyMeasurable[ℱ N] F P := by
    dsimp [ℱ, F]
    exact aestronglyMeasurable_piLE_of_dependsOn (X := shiftedSeqType X)
      (F := shiftedFunction f) (N := N) (μ := P) hFdep hFmeas
  have hFint : Integrable F P := by
    dsimp [F, P]
    exact shiftedFunction_integrable_of_boundedDifferences (X := X)
      (ν := shiftedIndependentTraj (X := X) μ) hdep hbd hFmeas
  have hc' : ∀ i, 0 ≤ c' i := shiftedBoundedDifferenceConstants_nonneg hc
  have hc0 : c' 0 = 0 := rfl
  have h0_zero : doobDiff P ℱ F 0 =ᵐ[P] 0 := by
    dsimp [P, ℱ, F]
    simpa using doobDiff_shifted_zero_ae_eq_zero (X := X) μ hFint
  have hcond_meas : ∀ i < (N + 1) - 1,
      ∀ᵐ z ∂(P.trim (ℱ.le i)),
        AEMeasurable (doobDiff P ℱ F (i + 1))
          ((@condExpKernel _ _ inferInstance P inferInstance (ℱ i)) z) := by
    intro i _hi
    have hYmeas : Measurable (doobDiff P ℱ F (i + 1)) := by
      exact (((doobDiff_stronglyAdapted P ℱ F) (i + 1)).mono (ℱ.le (i + 1))).measurable
    filter_upwards with z
    exact hYmeas.aemeasurable
  have hcond_bound : ∀ i < (N + 1) - 1,
      ∀ᵐ z ∂(P.trim (ℱ.le i)),
        ∃ a : ℝ, ∀ᵐ y ∂((@condExpKernel _ _ inferInstance P inferInstance (ℱ i)) z),
          doobDiff P ℱ F (i + 1) y ∈ Set.Icc a (a + c' (i + 1)) := by
    intro i hi
    have hiN : i < N := by omega
    have hdiam : ∀ z w,
      Preorder.frestrictLe i z = Preorder.frestrictLe i w →
        |shiftedTrajDiff μ F (i + 1) z - shiftedTrajDiff μ F (i + 1) w| ≤ c i := by
      intro z w hzw
      dsimp [F]
      exact shiftedTrajDiff_diameter_of_boundedDifferences (X := X) μ
        (f := f) (c := c) (N := N) (i := i) hdep hbd hFmeas hiN hzw
    have h := doobDiff_shifted_conditional_range_of_trajDiff_diameter
      (X := X) μ hFint (hc i) i hdiam
    simpa [P, ℱ, F, c'] using h
  have htail := mcdiarmid_doob_conditional_range_upper_tail_of_ranges_measurable
    (μ := P) (ℱ := ℱ) (F := F) (c := c') (N := N) (t := t)
    hFmeasN hFint hc' hc0 h0_zero hcond_meas hcond_bound ht
  simpa [P, F, c', boundedDifferencesVarianceSum_shifted_succ] using htail


end NumStability.HDP.Scalar.IndependentSums.McDiarmid
