import Mathlib.Analysis.CStarAlgebra.CStarMatrix
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Order
import Mathlib.Analysis.Matrix.Order
import Mathlib.Data.Matrix.Block
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.BlockDiagonal
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.BlockDiagonalCompression
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPair
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairPinching
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeProjection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeReflection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteDimensional
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteMatrixOrder
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealEmbedding
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealOrder
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ProjectionReflection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.RectangularCompression
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.RectangularMultiplication
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ReflectionAverage
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.StrictPositivity

/-!
# Analysis.CStarMatrices.Basic.RealMatrixBridge (compatibility wrapper)

Import-only historical R07 path. Its declaration block moved to `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.BlockDiagonal`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.BlockDiagonalCompression`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPair`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairPinching`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeProjection`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeReflection`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteDimensional`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteMatrixOrder`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealEmbedding`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealOrder`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.ProjectionReflection`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.RectangularCompression`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.RectangularMultiplication`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.ReflectionAverage`, `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra.StrictPositivity`, imported above. The exact C0005 direct import sequence remains available so existing imports preserve their supported public surface. This module declares nothing.
-/
