import Mathlib.Data.Real.Basic
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.MatrixSpectral
import ComputationalMathematics.Analysis.Perturbation.LeastSquares.Basic
import ComputationalMathematics.Analysis.Perturbation.LeastSquares.Wedin
import ComputationalMathematics.Analysis.SingularValues.Realification
import ComputationalMathematics.Source.Higham.Chapter20.Lemma11.Support
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.MinimumNorm.Pseudoinverse.UnderdeterminedSpec
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.MinimumNorm.Solvers.UnderdeterminedSpec
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.MinimumNorm.Specifications.UnderdeterminedSpec
import ComputationalMathematics.Source.Higham.Chapter21.Equation04.UnderdeterminedSpec
import ComputationalMathematics.Source.Higham.Chapter21.Equation05.UnderdeterminedSpec
import ComputationalMathematics.Source.Higham.Chapter21.Lemma02.Symmetrization.UnderdeterminedSpec
import ComputationalMathematics.Source.Higham.Chapter21.Theorem01.ComponentwisePerturbation.UnderdeterminedSpec
import ComputationalMathematics.Analysis.Perturbation.LeastSquares.Projection
import ComputationalMathematics.Source.Higham.Chapter20.Lemma12

/-!
# Higham20Lemma20_12 (historical compatibility wrapper)

Import-only wrapper retained so historical imports of
`NumStability.Algorithms.LeastSquares.Higham20Lemma20_12`
keep resolving. Its declarations moved unchanged to the canonical
modules imported above. Its own historical imports are re-stated so
consumers that reached an identifier transitively through this module
still see the same surface.
-/
