/-
SPDX-License-Identifier: MIT
-/

import ComputationalMathematics.Source.LeVeque.Chapter01.AcousticsConservationForm
import ComputationalMathematics.Source.LeVeque.Chapter01.AcousticsEigenvalues
import ComputationalMathematics.Source.LeVeque.Chapter01.AcousticsLeftSolutionDomains
import ComputationalMathematics.Source.LeVeque.Chapter01.AcousticsModes
import ComputationalMathematics.Source.LeVeque.Chapter01.AcousticsRightModeAlgebraic
import ComputationalMathematics.Source.LeVeque.Chapter01.AdvectionLinearFlux
import ComputationalMathematics.Source.LeVeque.Chapter01.AdvectionWaveIdentity
import ComputationalMathematics.Source.LeVeque.Chapter01.CoordinateDirectionalMethods
import ComputationalMathematics.Source.LeVeque.Chapter01.CoordinateHighResolutionMethods
import ComputationalMathematics.Source.LeVeque.Chapter01.CoordinateSplittingBalance
import ComputationalMathematics.Source.LeVeque.Chapter01.DimensionalSplitting
import ComputationalMathematics.Source.LeVeque.Chapter01.DiscontinuityGeneralComparison
import ComputationalMathematics.Source.LeVeque.Chapter01.DiscontinuityWitnesses
import ComputationalMathematics.Source.LeVeque.Chapter01.EigenbasisDecoupling
import ComputationalMathematics.Source.LeVeque.Chapter01.EigenvaluePropagation
import ComputationalMathematics.Source.LeVeque.Chapter01.EigenvalueWaveSpeeds
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation01
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation02
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation02SolutionDomains
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation02UniformTransport
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation03
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation03AdvectedProfile
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation03SolutionDomains
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation03TransportSolution
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation04
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation04AcousticModel
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation04Model
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation05
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation05Definition
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation06
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation07
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation08
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation09
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation10
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation10Definition
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation10RectangleConservation
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation11
import ComputationalMathematics.Source.LeVeque.Chapter01.FiniteVolumeCellAverage
import ComputationalMathematics.Source.LeVeque.Chapter01.FiniteVolumeFluxUpdate
import ComputationalMathematics.Source.LeVeque.Chapter01.FiniteVolumeLocalFluxUpdate
import ComputationalMathematics.Source.LeVeque.Chapter01.FiniteVolumeUpdateError
import ComputationalMathematics.Source.LeVeque.Chapter01.FluxJacobianHyperbolicity
import ComputationalMathematics.Source.LeVeque.Chapter01.HeterogeneousCellAveraging
import ComputationalMathematics.Source.LeVeque.Chapter01.Hyperbolicity
import ComputationalMathematics.Source.LeVeque.Chapter01.IntegralToDifferential
import ComputationalMathematics.Source.LeVeque.Chapter01.LinearFluxSpecialization
import ComputationalMathematics.Source.LeVeque.Chapter01.LinearRiemannEigensolution
import ComputationalMathematics.Source.LeVeque.Chapter01.MaterialCellVolumeAveraging
import ComputationalMathematics.Source.LeVeque.Chapter01.MaterialInterfaceLocalRiemannData
import ComputationalMathematics.Source.LeVeque.Chapter01.MaterialInterfaceRiemannData
import ComputationalMathematics.Source.LeVeque.Chapter01.NonconservationSourceTerms
import ComputationalMathematics.Source.LeVeque.Chapter01.NonlinearShockFormation
import ComputationalMathematics.Source.LeVeque.Chapter01.OneStepCurrentData
import ComputationalMathematics.Source.LeVeque.Chapter01.OneStepMethod
import ComputationalMathematics.Source.LeVeque.Chapter01.RectangleRiemannInterfaceFlux
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannCertifiedRoutineInterface
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannHyperbolicProblem
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannInformationInterfaceFlux
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannInitialConfiguration
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannInterfaceFlux
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannLocalInformationInterface
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannLocalRoutineInterface
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannProblemDataClassification
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannRayZero
import ComputationalMathematics.Source.LeVeque.Chapter01.ScalarHyperbolicity
import ComputationalMathematics.Source.LeVeque.Chapter01.SecondOrderHyperbolicity
import ComputationalMathematics.Source.LeVeque.Chapter01.SourceTermsRectangleBalance
import ComputationalMathematics.Source.LeVeque.Chapter01.VariableCoefficientConservationForm

/-!
# LeVeque, Chapter 1

Source-local wrappers for Chapter 1 of LeVeque's *Finite Volume Methods for
Hyperbolic Problems*.
-/
