/-
SPDX-License-Identifier: MIT
-/

import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionCauchyTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionConverseTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionDiffusion
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionLocalProfileTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionProfileTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionRectangleConverseTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionWithinProfile
import ComputationalMathematics.Source.LeVeque.Chapter02.AutonomousIntegralFluxLocalTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AutonomousIntegralFluxTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.CharacteristicDerivative
import ComputationalMathematics.Source.LeVeque.Chapter02.CharacteristicTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.ConstantDiffusion
import ComputationalMathematics.Source.LeVeque.Chapter02.ConstantFluxAdvection
import ComputationalMathematics.Source.LeVeque.Chapter02.ConstantTracerFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.EndpointFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.Equation01
import ComputationalMathematics.Source.LeVeque.Chapter02.FickFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.GenericCharacteristic
import ComputationalMathematics.Source.LeVeque.Chapter02.HeatCapacityTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.InitialProfile
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralFluxDerivative
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralFluxDerivativeTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralResidual
import ComputationalMathematics.Source.LeVeque.Chapter02.MaterialDerivative
import ComputationalMathematics.Source.LeVeque.Chapter02.NonconservativeCharacteristic
import ComputationalMathematics.Source.LeVeque.Chapter02.PointwiseConservation
import ComputationalMathematics.Source.LeVeque.Chapter02.ScalarAdvectionCauchyTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerConstantFluxTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerDensity
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerMass
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerStateFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.VariableDiffusion
import ComputationalMathematics.Source.LeVeque.Chapter02.VariableVelocityCharacteristic

/-!
# LeVeque Chapter 2: Conservation Laws and Differential Equations

Source correspondences currently available for Chapter 2. This entry point
does not assert that the chapter's formalization is complete.
-/
