/-
SPDX-License-Identifier: MIT
-/

import ComputationalMathematics.Source.LeVeque.Chapter01.AcousticsConservationForm
import ComputationalMathematics.Source.LeVeque.Chapter01.AcousticsEigenvalues
import ComputationalMathematics.Source.LeVeque.Chapter01.AcousticsModes
import ComputationalMathematics.Source.LeVeque.Chapter01.AdvectionLinearFlux
import ComputationalMathematics.Source.LeVeque.Chapter01.AdvectionWaveIdentity
import ComputationalMathematics.Source.LeVeque.Chapter01.DimensionalSplitting
import ComputationalMathematics.Source.LeVeque.Chapter01.EigenvalueWaveSpeeds
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation01
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation02
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation03
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation03AdvectedProfile
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation04
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation04Model
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation05
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation06
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation07
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation08
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation09
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation10
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation11
import ComputationalMathematics.Source.LeVeque.Chapter01.FiniteVolumeCellAverage
import ComputationalMathematics.Source.LeVeque.Chapter01.FiniteVolumeFluxUpdate
import ComputationalMathematics.Source.LeVeque.Chapter01.HeterogeneousCellAveraging
import ComputationalMathematics.Source.LeVeque.Chapter01.Hyperbolicity
import ComputationalMathematics.Source.LeVeque.Chapter01.IntegralToDifferential
import ComputationalMathematics.Source.LeVeque.Chapter01.LinearFluxSpecialization
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannInterfaceFlux
import ComputationalMathematics.Source.LeVeque.Chapter01.ScalarHyperbolicity

/-!
# LeVeque, Chapter 1

Source-local wrappers for Chapter 1 of LeVeque's *Finite Volume Methods for
Hyperbolic Problems*.
-/
