/-
SPDX-License-Identifier: MIT
-/

import ComputationalMathematics.Source.LeVeque.Chapter02.AcousticsMatrixTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.ActualPressureSlopeTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionCauchyTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionConverseTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionDiffusion
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionLocalProfileTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionProfileTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionRectangleConverseTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AdvectionWithinProfile
import ComputationalMathematics.Source.LeVeque.Chapter02.AutonomousIntegralFluxLocalTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.AutonomousIntegralFluxTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.BarotropicPressureTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.BathHeat
import ComputationalMathematics.Source.LeVeque.Chapter02.CapacityBalance
import ComputationalMathematics.Source.LeVeque.Chapter02.CapacityConservationTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.CapacityCoordinatesTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.CapacityIntegralTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.CapacityRealizationTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.CharacteristicDerivative
import ComputationalMathematics.Source.LeVeque.Chapter02.CharacteristicTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.ClassicalExternalHeat
import ComputationalMathematics.Source.LeVeque.Chapter02.ClassicalFluidCauchyTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.ConservativeVariableAdvection
import ComputationalMathematics.Source.LeVeque.Chapter02.ConservativeVariableAdvectionTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.ConservedAcousticsComponents
import ComputationalMathematics.Source.LeVeque.Chapter02.ConstantDiffusion
import ComputationalMathematics.Source.LeVeque.Chapter02.ConstantFluidDensityTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.ConstantFluxAdvection
import ComputationalMathematics.Source.LeVeque.Chapter02.ConstantSystem
import ComputationalMathematics.Source.LeVeque.Chapter02.ConstantTracerFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.DomainFluidJacobianTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.DomainFluidPerturbation
import ComputationalMathematics.Source.LeVeque.Chapter02.DomainPressure
import ComputationalMathematics.Source.LeVeque.Chapter02.DomainStateFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.EndpointFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.Equation01
import ComputationalMathematics.Source.LeVeque.Chapter02.ExternalHeatSourceTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.FickFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.FirstVariationTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.FluidContinuityTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.FluidJacobianTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.FluidPerturbationTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.FluidStateFluxTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.FourierFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.GenericCharacteristic
import ComputationalMathematics.Source.LeVeque.Chapter02.HeatCapacity
import ComputationalMathematics.Source.LeVeque.Chapter02.HeatEnergy
import ComputationalMathematics.Source.LeVeque.Chapter02.HeatEquationTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.InitialProfile
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralFluxDerivative
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralFluxDerivativeTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralMassBalanceCumulativeTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralMassBalanceProductionTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralMassBalanceTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.IntegralResidual
import ComputationalMathematics.Source.LeVeque.Chapter02.IsentropicPressureTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.MassFluxContinuity
import ComputationalMathematics.Source.LeVeque.Chapter02.MaterialDerivative
import ComputationalMathematics.Source.LeVeque.Chapter02.MomentumDensityTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.MomentumFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.NonconservativeCharacteristic
import ComputationalMathematics.Source.LeVeque.Chapter02.PointwiseConservation
import ComputationalMathematics.Source.LeVeque.Chapter02.PressureSlopeTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.PrintedHeatBalanceTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.QuasilinearMatrix
import ComputationalMathematics.Source.LeVeque.Chapter02.ReactingFlow
import ComputationalMathematics.Source.LeVeque.Chapter02.ReactionDiffusion
import ComputationalMathematics.Source.LeVeque.Chapter02.ReactionMatrix
import ComputationalMathematics.Source.LeVeque.Chapter02.ScalarAdvectionCauchyTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.SystemComponents
import ComputationalMathematics.Source.LeVeque.Chapter02.ThermalDiffusionComparison
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerConstantFluxTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerDensity
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerMass
import ComputationalMathematics.Source.LeVeque.Chapter02.TracerStateFlux
import ComputationalMathematics.Source.LeVeque.Chapter02.UnitHeatCapacityTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.VariableDiffusion
import ComputationalMathematics.Source.LeVeque.Chapter02.VariableVelocityCharacteristic
import ComputationalMathematics.Source.LeVeque.Chapter02.VariableVelocityCharacteristicEquationTarget
import ComputationalMathematics.Source.LeVeque.Chapter02.VariableVelocityCharacteristicExistenceTarget

/-!
# LeVeque Chapter 2: Conservation Laws and Differential Equations

Source correspondences currently available for Chapter 2. This entry point
does not assert that the chapter's formalization is complete.
-/
