import ComputationalMathematics.Analysis.TestMatrices.Cauchy.Basic
import ComputationalMathematics.Analysis.TestMatrices.Cauchy.Cauchy
import ComputationalMathematics.Analysis.TestMatrices.Cauchy.Contracts
import ComputationalMathematics.Analysis.TestMatrices.Companion.Basic
import ComputationalMathematics.Analysis.TestMatrices.Companion.Companion
import ComputationalMathematics.Analysis.TestMatrices.Companion.CompanionSpectral
import ComputationalMathematics.Analysis.TestMatrices.Companion.Contracts
import ComputationalMathematics.Analysis.TestMatrices.Gaussian.GaussianDirection
import ComputationalMathematics.Analysis.TestMatrices.Gaussian.GaussianOrthogonal
import ComputationalMathematics.Analysis.TestMatrices.Hilbert.Asymptotics
import ComputationalMathematics.Analysis.TestMatrices.Hilbert.Basic
import ComputationalMathematics.Analysis.TestMatrices.Hilbert.Exact
import ComputationalMathematics.Analysis.TestMatrices.Hilbert.HilbertAsymptotic
import ComputationalMathematics.Analysis.TestMatrices.Hilbert.ShiftedHilbert
import ComputationalMathematics.Analysis.TestMatrices.Orthogonal.Basic
import ComputationalMathematics.Analysis.TestMatrices.Orthogonal.HaarFiberMeasure
import ComputationalMathematics.Analysis.TestMatrices.Orthogonal.OrthogonalCoordinates
import ComputationalMathematics.Analysis.TestMatrices.Orthogonal.OrthogonalFibers
import ComputationalMathematics.Analysis.TestMatrices.Orthogonal.OrthogonalHaar
import ComputationalMathematics.Analysis.TestMatrices.Orthogonal.OrthogonalSphere
import ComputationalMathematics.Analysis.TestMatrices.Pascal.Basic
import ComputationalMathematics.Analysis.TestMatrices.Pascal.Contracts
import ComputationalMathematics.Analysis.TestMatrices.Pascal.Exact
import ComputationalMathematics.Analysis.TestMatrices.Pascal.PascalDualFlag
import ComputationalMathematics.Analysis.TestMatrices.Pascal.PascalOscillation
import ComputationalMathematics.Analysis.TestMatrices.Pascal.PascalOscillationCore
import ComputationalMathematics.Analysis.TestMatrices.Pascal.PascalSpectral
import ComputationalMathematics.Analysis.TestMatrices.Pascal.PascalTotalPositivity
import ComputationalMathematics.Analysis.TestMatrices.RandomSVD.Basic
import ComputationalMathematics.Analysis.TestMatrices.RandomSVD.GroupLawRecursion
import ComputationalMathematics.Analysis.TestMatrices.RandomSVD.Stewart
import ComputationalMathematics.Analysis.TestMatrices.RandomSVD.StewartHaar
import ComputationalMathematics.Analysis.TestMatrices.RandomSVD.StewartMeasurability
import ComputationalMathematics.Analysis.TestMatrices.RandomSVD.StewartRecursion
import ComputationalMathematics.Analysis.TestMatrices.RealGinibre.GinibreRoots
import ComputationalMathematics.Analysis.TestMatrices.RealGinibre.ProjectiveWeightIntegral
import ComputationalMathematics.Analysis.TestMatrices.Toeplitz.Basic
import ComputationalMathematics.Analysis.TestMatrices.Toeplitz.Contracts

/-!
# Named test matrices

Declaration-free aggregate for the Named test matrices subtree.
-/
