import ComputationalMathematics.Source.Higham.Chapter01.FloatingPointArithmetic.CancellationOfRoundingErrors
import ComputationalMathematics.Source.Higham.Chapter01.FloatingPointArithmetic.IncreasingPrecision
import ComputationalMathematics.Source.Higham.Chapter01.FloatingPointArithmetic.InstabilityWithoutCancellation
import ComputationalMathematics.Source.Higham.Chapter01.Problem01.RelativeError.All
import ComputationalMathematics.Source.Higham.Chapter01.Problem02.NearIntegerTable.Basic
import ComputationalMathematics.Source.Higham.Chapter01.Problem03.CancellationRewrites.All
import ComputationalMathematics.Source.Higham.Chapter01.Problem05.CompensatedLogarithm.Basic
import ComputationalMathematics.Source.Higham.Chapter01.Problem06.CalculatorWords.Basic
import ComputationalMathematics.Source.Higham.Chapter01.Problem07.SampleVarianceConditioning.All
import ComputationalMathematics.Source.Higham.Chapter01.Problem08.MullerRecurrence.Basic
import ComputationalMathematics.Source.Higham.Chapter01.Problem09.CramersRule.All
import ComputationalMathematics.Source.Higham.Chapter01.Problem10.TwoPassSampleVariance.All
import ComputationalMathematics.Source.Higham.Chapter01.Problem10.TwoPassSampleVariance.RemainderBound.Theorem
import ComputationalMathematics.Source.Higham.Chapter01.Section02.ErrorMeasures.All
import ComputationalMathematics.Source.Higham.Chapter01.Section03.ErrorSources.All
import ComputationalMathematics.Source.Higham.Chapter01.Section04.AccuracyAndPrecision.All
import ComputationalMathematics.Source.Higham.Chapter01.Section07.Cancellation.All
import ComputationalMathematics.Source.Higham.Chapter01.Section07.TrigonometricCancellation.All
import ComputationalMathematics.Source.Higham.Chapter01.Section09.SampleVariance.All
import ComputationalMathematics.Source.Higham.Chapter01.Section09.SampleVariance.IeeeSingleOnePassCounterexample.Results
import ComputationalMathematics.Source.Higham.Chapter01.Section10.CramersRule.All
import ComputationalMathematics.Source.Higham.Chapter01.Section11.Accumulation.Basic
import ComputationalMathematics.Source.Higham.Chapter01.Section12.InstabilityWithoutCancellation.PivotingExample
import ComputationalMathematics.Source.Higham.Chapter01.Section13.IncreasingPrecision.BinaryStorageExamples
import ComputationalMathematics.Source.Higham.Chapter01.Section14.CancellationOfRoundingErrors.Algorithm02RoundedCore
import ComputationalMathematics.Source.Higham.Chapter01.Section16.ProblemDependentStability.All
import ComputationalMathematics.Source.Higham.Chapter01.Section17

/-!
# Higham Chapter 1

Source correspondence for introductory principles of finite-precision
computation. The current formalization covers cancellation, increasing
precision, instability without cancellation, and the nonrandom-rounding
example from Section 1.17.
-/
