import ComputationalMathematics.Source.Higham.Chapter14.Theorem05.ForwardError.GaussJordanQConstruction
import ComputationalMathematics.Source.Higham.Chapter14.Theorem05.ForwardError.GJEAsymptoticFamilies
import ComputationalMathematics.Source.Higham.Chapter14.Theorem05.ForwardError.GJEFinalDivisionClosure
import ComputationalMathematics.Source.Higham.Chapter14.Theorem05.ForwardError.GJEPrintedEnvelopeClosure
import ComputationalMathematics.Source.Higham.Chapter14.Theorem05.ForwardError.GJETheorem145SourceClosure

/-!
# NumStability.Source.Higham.Chapter14.Theorem05.ForwardError

Declaration-free W08 discovery aggregate.
-/
