import ComputationalMathematics.Algorithms.PolynomialEvaluation.DerivativeEvaluation.ErrorBounds
import ComputationalMathematics.Algorithms.PolynomialEvaluation.ElementaryErrorBounds
import ComputationalMathematics.Algorithms.PolynomialEvaluation.MatrixNorms
import ComputationalMathematics.Algorithms.PolynomialEvaluation.RootProduct
import ComputationalMathematics.Source.Higham.Chapter05.Algorithm01.ComplexHorner.ErrorBounds.Theorems
import ComputationalMathematics.Source.Higham.Chapter05.Section02.BidiagonalDerivativeAnalysis.Results.Theorems
import ComputationalMathematics.Source.Higham.Chapter05.Section02.DerivativeError.Results.Theorems
import ComputationalMathematics.Source.Higham.Chapter05.Section04.PatersonStockmeyer.Results.Theorems
import ComputationalMathematics.Source.Higham.Chapter05.Section05.FastPolynomialEvaluation.Results.Theorems

/-!
# Polynomial evaluation algorithms

Semantic aggregate for reusable polynomial-evaluation infrastructure and
the current Higham Chapter 5 theorem providers represented by checkpoint C2.
-/
