import ComputationalMathematics.Algorithms.FastMatMul

/-! Canonical import regression for `ComputationalMathematics.Algorithms.FastMatMul`. -/

#check NumStability.BilinearAlgorithmError
#check NumStability.StrassenErrorBound
#check NumStability.StrassenRecurrence
#check NumStability.ThreeMMethodError
#check NumStability.WinogradInnerProductError
#check NumStability.WinogradStrassenErrorBound
#check NumStability.WinogradStrassenRecurrence
#check NumStability.conventional_componentwise_implies_cubic
#check NumStability.higham23_biniLotti_scaledRemainder_isBigO_u_sq
#check NumStability.higham23_eq23_11_miller_normwise
#check NumStability.higham23_problem23_8_power_exponent
#check NumStability.higham23_theorem23_2_strassen_closedCoefficient_firstOrder
#check NumStability.higham23_threeMStrassen_sourceCoefficient
#check NumStability.higham23_winogradStrassen_error_step
#check NumStability.strassen_recurrence_monotone
