import ComputationalMathematics.Algorithms.LinearSystems.Iterative.Stationary.Semiconvergence.Projectors.FixedRange

/-! Canonical import regression for `ComputationalMathematics.Algorithms.LinearSystems.Iterative.Stationary.Semiconvergence.Projectors.FixedRange`. -/

#check NumStability.stationaryDrazinFixedProjector_fixed_by_G
#check NumStability.stationaryDrazinFixedProjector_idempotent
#check NumStability.stationaryDrazinFixedProjector_matMulVec_fixed
#check NumStability.stationaryDrazinFixedProjector_matPow_fixed
#check NumStability.stationaryDrazinRangeProjector_commutes_with_G
#check NumStability.stationaryDrazinRangeProjector_commutes_with_matPow
#check NumStability.stationaryDrazinRangeProjector_matPow_sandwich
#check NumStability.stationaryDrazinRangeProjector_null_component_fixed
#check NumStability.stationaryDrazin_matPow_vec_split
#check NumStability.stationaryDrazin_matPow_vec_tendsto_fixedProjector_of_range_tendsto_zero
