import ComputationalMathematics.Algorithms.LinearSystems.Iterative.Stationary.Semiconvergence.Execution.RoundedCertificates

/-! Canonical import regression for `ComputationalMathematics.Algorithms.LinearSystems.Iterative.Stationary.Semiconvergence.Execution.RoundedCertificates`. -/

#check NumStability.RoundedStationarySolveCertificate
#check NumStability.flStationaryIterationLower
#check NumStability.flStationaryIterationLower_solveCertificate
#check NumStability.flStationaryIterationUpper
#check NumStability.flStationaryIterationUpper_solveCertificate
#check NumStability.stationaryLocalError
#check NumStability.stationaryRoundedRhs
#check NumStability.stationaryRoundedRhs_error_bound
