import ComputationalMathematics.Algorithms.LinearSystems.LU.BlockLU

/-! Canonical import regression for `ComputationalMathematics.Algorithms.LinearSystems.LU.BlockLU`. -/

#check NumStability.BlockLUBackwardError
#check NumStability.BlockLUFactSpec
#check NumStability.DiagonalBlockSolveFirstOrderSpec
#check NumStability.Higham13BlockSolveFamilySpec
#check NumStability.Higham13CLMBlockNonsingular
#check NumStability.Higham13PositiveBlockOrders
#check NumStability.Higham13VaryingBlockLUExistsUnique
#check NumStability.Higham13VaryingBlockLUFactSpec.eq_step_of_tail_unique
#check NumStability.Higham13VaryingLeadingPrincipalNonsingular.of_det_of_schur
#check NumStability.IsBlockDiagDomCol
#check NumStability.MatMulFirstOrderBound
#check NumStability.MatMulFirstOrderSpec
#check NumStability.blockLUOneStepL_firstSplit_fromBlocks
#check NumStability.blockMatrixNonsingular_of_posDef_flat
#check NumStability.blockMaxNorm
#check NumStability.blockMaxNorm_le_blockInfNorm
#check NumStability.blockSchur
#check NumStability.block_lu_one_step
#check NumStability.dhsBlockForwardConventionalSolution
#check NumStability.growthFactorEntry_sq_kappa_budget_le_of_growth_le_inv_ratio
#check NumStability.higham13VaryingBlockUnitLower_fromBlocks
#check NumStability.higham13_abs_entry_le_opNorm2
#check NumStability.higham13_maxNorm_vecResidual_lift
#check NumStability.idBlock
#check NumStability.matrix_posDef_to_isSymPosDef
