import ComputationalMathematics.Algorithms.LinearSystems.LU.BlockLU.FirstOrderModels

/-! Canonical import regression for `ComputationalMathematics.Algorithms.LinearSystems.LU.BlockLU.FirstOrderModels`. -/

#check NumStability.BlockSolveFirstOrderBound
#check NumStability.BlockSolveFirstOrderSpec
#check NumStability.DiagonalBlockSolveFirstOrderBound
#check NumStability.DiagonalBlockSolveFirstOrderSpec
#check NumStability.LocalLUFirstOrderBound
#check NumStability.LocalLUFirstOrderSpec
#check NumStability.MatMulFirstOrderBound
#check NumStability.MatMulFirstOrderSpec
#check NumStability.PartitionedLUFirstOrderSpec
#check NumStability.RightTriangularSolveFirstOrderSpec
#check NumStability.SubtractionFirstOrderSpec
#check NumStability.TriangularSolveFirstOrderBound
#check NumStability.TriangularSolveFirstOrderSpec
