import ComputationalMathematics.Algorithms.LinearSystems.LU.BlockLU.RecursiveFactorization

/-! Canonical import regression for `ComputationalMathematics.Algorithms.LinearSystems.LU.BlockLU.RecursiveFactorization`. -/

#check NumStability.blockLUOneStepL
#check NumStability.blockLUOneStepL_blockMaxNorm_le_of_firstSplit_tail
#check NumStability.blockLUOneStepU
#check NumStability.blockLUOneStepU_blockMaxNorm_le_of_firstRow_tail
#check NumStability.blockLUOneStep_blockMaxNorm_product_le_of_firstSplit_tail
#check NumStability.block_lu_one_step
