import ComputationalMathematics.Algorithms.LinearSystems.LeastSquares.GramBasis

/-! Canonical import regression for `ComputationalMathematics.Algorithms.LinearSystems.LeastSquares.GramBasis`. -/

#check NumStability.rectRightGramBasisOrderedEquiv
#check NumStability.rectRightGramBasisSingularValue_pos_of_rectMatMulVec_injective
#check NumStability.rectRightGramLeftSingularFromEigenbasis_transpose_action_of_pos
