import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.ComplexSchur.VectorizedSolvability

/-! Canonical import regression for `ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.ComplexSchur.VectorizedSolvability`. -/

#check NumStability.existsUnique_isSylvesterSolutionRect_of_sylvesterVecCoeff_det_ne_zero
