import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.BoydDomain

/-! Canonical import regression for `ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.BoydDomain`. -/

#check NumStability.Ch15.boydSmoothRectDerivative_apply_directional_chain_of_two_le
#check NumStability.Ch15.boydSmoothRectDerivative_apply_eq_inv_projectedLemma3B_of_two_le
#check NumStability.Ch15.boydSmoothRectUpdate_hasFDerivAt_of_two_le
#check NumStability.Ch15.differentiableAt_realLpGradient_of_two_le
#check NumStability.Ch15.fderiv_realLpGradient_apply_of_two_le
#check NumStability.Ch15.realLpGradient_line_hasDerivAt_of_two_le
