import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.BoydLocal

/-! Canonical import regression for `ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.BoydLocal`. -/

#check NumStability.Ch15.boydSmoothRectDerivative_apply_directional_chain
#check NumStability.Ch15.boydSmoothRectDerivative_apply_eq_inv_projectedLemma3B
#check NumStability.Ch15.boydSmoothRectUpdate_hasFDerivAt
#check NumStability.Ch15.boyd_inner_directional_eq_weighted_projectedLemma3B
#check NumStability.Ch15.boyd_outer_directional_weighted_tangent
#check NumStability.Ch15.boyd_transpose_inner_directional_expansion
#check NumStability.Ch15.differentiableAt_realLpGradientCoordinateFactor
#check NumStability.Ch15.differentiableAt_realLpGradient_of_all_ne
#check NumStability.Ch15.differentiableAt_realLpPowerSum
#check NumStability.Ch15.fderiv_realLpGradient_apply
#check NumStability.Ch15.realLpGradient_line_hasDerivAt
