import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.RowwiseDomain.Basic

/-! Canonical import regression for `ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.RowwiseDomain.Basic`. -/

#check NumStability.Ch15.IsBoydInnerRowwiseSmoothDomain
#check NumStability.Ch15.IsBoydRowwiseCompositionSmooth
#check NumStability.Ch15.boydRectActionCLM_apply_eq_zero_of_row_zero
#check NumStability.Ch15.boydRectInnerNormalMap
#check NumStability.Ch15.boydRectInnerNormalMap_coordinateFactor_eq_zero_of_row_zero
#check NumStability.Ch15.boydRectInnerNormalMap_line_hasDerivAt_of_rowwise
#check NumStability.Ch15.boydRectNormalMap
#check NumStability.Ch15.boydRectNormalMap_line_hasDerivAt_of_rowwise
#check NumStability.Ch15.boydSmoothRectDerivative_apply_directional_chain_of_rowwise_lt_two
#check NumStability.Ch15.boydSmoothRectDerivative_apply_eq_inv_projectedLemma3B_of_rowwise_lt_two
#check NumStability.Ch15.boydSmoothRectUpdate_hasFDerivAt_of_rowwise_lt_two
#check NumStability.Ch15.differentiableAt_boydRectInnerNormalMap_of_rowwise
#check NumStability.Ch15.differentiableAt_boydRectNormalMap_of_rowwise
#check NumStability.Ch15.fderiv_boydRectInnerNormalMap_apply_of_rowwise
#check NumStability.Ch15.fderiv_boydRectNormalMap_apply_of_rowwise
