import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.LocalStability.BoydLocalStability

/-! Canonical import regression for `ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.LocalStability.BoydLocalStability`. -/

#check NumStability.Ch15.IsLocalSeminormContractionTo
#check NumStability.Ch15.eventually_norm_pow_le_of_spectralRadius_lt
#check NumStability.Ch15.exists_isLocalContractionTo_iterate_of_hasFDerivAt_pow_norm_lt
#check NumStability.Ch15.exists_local_powerAdaptedSeminormContraction
#check NumStability.Ch15.exists_pos_norm_pow_le_of_spectralRadius_lt
#check NumStability.Ch15.iterate_seminorm_le_geometric_of_localSeminormContraction
#check NumStability.Ch15.norm_le_powerAdaptedSeminorm
#check NumStability.Ch15.powerAdaptedBound
#check NumStability.Ch15.powerAdaptedSeminorm
#check NumStability.Ch15.powerAdaptedSeminorm_apply
#check NumStability.Ch15.powerAdaptedSeminorm_le_bound_mul_norm
#check NumStability.Ch15.powerAdaptedSeminorm_map_identity
#check NumStability.Ch15.powerAdaptedSeminorm_map_le
#check NumStability.Ch15.powerAdaptedSeminorm_succ
#check NumStability.Ch15.tendsto_iterate_of_localSeminormContraction
