import ComputationalMathematics.Algorithms.NormEstimation.TwoNorm.Dixon.PowerBounds.DixonCompletion

/-! Canonical import regression for `ComputationalMathematics.Algorithms.NormEstimation.TwoNorm.Dixon.PowerBounds.DixonCompletion`. -/

#check NumStability.ch15Closure_dixon_left_power_inequality
#check NumStability.ch15Closure_exists_dixon_sphere_direction_power_lower
#check NumStability.ch15Closure_opNorm2Le_matPow
#check NumStability.ch15Closure_quadForm_power_lower_of_unit_eigenvector
