import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.UniformRows

/-! Canonical import regression for `ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.UniformRows`. -/

#check NumStability.finiteComplexCStarMatrix
#check NumStability.finiteComplexCStarMatrix_add
#check NumStability.finiteComplexCStarMatrix_finiteIdMatrix
#check NumStability.finiteComplexCStarMatrix_finset_sum
#check NumStability.finiteComplexCStarMatrix_isSelfAdjoint_of_symmetric
#check NumStability.finiteComplexCStarMatrix_le_of_finiteLoewnerLe
#check NumStability.finiteComplexCStarMatrix_mul
#check NumStability.finiteComplexCStarMatrix_smul
#check NumStability.finiteComplexCStarMatrix_smul_finiteIdMatrix
#check NumStability.finiteComplexCStarMatrix_zero
#check NumStability.uniformRowOuterGramSample_centered_cstar_selfAdjoint
