import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.HashCollisionProbabilities

/-! Canonical import regression for `ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.HashCollisionProbabilities`. -/

#check NumStability.countSketchHashProbability_eventProb_pairCollision_eq_inv
#check NumStability.countSketchHashProbability_eventProb_pairNoCollision_eq_one_sub_inv
#check NumStability.countSketchHashProbability_expectationReal_collision_coeff_sq_eq_inv_mul
#check NumStability.countSketchHashProbability_expectationReal_pairCollisionIndicator_eq_inv
