import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.GramMoments

/-! Canonical import regression for `ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.GramMoments`. -/

#check NumStability.uniformRowTraceProbMass_marginal_two_ne
#check NumStability.uniformRowTraceProbability_eventProb_pair_collision_eq_inv
#check NumStability.uniformRowTraceProbability_eventProb_uniformRowSampleGram_frob_error_le_ge_one_sub
#check NumStability.uniformRowTraceProbability_eventProb_uniformRowSampleGram_frob_error_le_ge_one_sub_frobNorm
#check NumStability.uniformRowTraceProbability_expectationReal_centered_sum_sq
#check NumStability.uniformRowTraceProbability_expectationReal_sampleAverage_sub_mean_sq
#check NumStability.uniformRowTraceProbability_expectationReal_uniformRowSampleGram_entry_error_sq
#check NumStability.uniformRowTraceProbability_expectationReal_uniformRowSampleGram_frob_error_sq_le
#check NumStability.uniformRowTraceProbability_expectationReal_uniformRowSampleGram_frob_error_sq_le_frobNorm
