import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.GramDotFloatingPoint

/-! Canonical import regression for `ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.GramDotFloatingPoint`. -/

#check NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDotWithComputedDen_rowGram_frob_error_le_ge_one_sub
#check NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDotWithComputedDen_rowGram_frob_error_le_ge_one_sub_frobNorm
#check NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDot_rowGram_frob_error_le_ge_one_sub
#check NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDot_rowGram_frob_error_le_ge_one_sub_frobNorm
