import ComputationalMathematics.Algorithms.Summation

/-! Canonical import regression for `ComputationalMathematics.Algorithms.Summation`. -/

#check NumStability.FastTwoSumFiniteCertificate
#check NumStability.finiteKahanTrace_tail_direct_sub_finiteNormalRange_not_finiteSystem_counterexample
#check NumStability.fl_alternativeCompensatedSum_backward_error_source_bound_of_exact_steps_higham_cap
#check NumStability.fl_alternativeCompensatedSum_exactWithUnitRoundoff
#check NumStability.fl_insertionPowersFour_eq_recursiveSum
#check NumStability.fl_insertionSumList
#check NumStability.fl_kahanModifiedNoGuardCorrection_exactWithUnitRoundoff
#check NumStability.fl_pairwiseSum
#check NumStability.fl_pairwiseSumSixDisplayed
#check NumStability.fl_recursiveSum
#check NumStability.highamCh4_equation48_modelStrengthCorrection_bareFPModel
#check NumStability.highamCh4_equation49_modelStrengthCorrection_bareFPModel
#check NumStability.kahanFF_alternativeCompensatedSum_backward_error
#check NumStability.kahanFF_kahanSum_backward_error
#check NumStability.kahanFF_kahanSum_forward_error
#check NumStability.kahanFF_kahan_correctionSub_exact
#check NumStability.kahanFF_model
#check NumStability.kahanNoGuardStepTrace
#check NumStability.noGuardCorrectionFormulaCounterexample_not_exact
#check NumStability.not_forall_finiteKahanTrace_tail_abs_order
#check NumStability.problem410PriestInput_sum_eq_two
#check NumStability.recursiveSum_problem43_abs_error_bound
