import ComputationalMathematics.Algorithms.Summation.Compensated.Kahan.LocalCoefficients

/-! Canonical import regression for `ComputationalMathematics.Algorithms.Summation.Compensated.Kahan.LocalCoefficients`. -/

#check NumStability.KahanPrefixCorrectionSubExact
#check NumStability.KahanPrefixDeltaWitnessFamily
#check NumStability.KahanStepDeltaWitness
#check NumStability.kahanCorrectionStateCoeff
#check NumStability.kahanPrefixDeltaWitnessFamilyOfExactSub
#check NumStability.kahanStepDeltaWitness_e_abs_le_split
#check NumStability.kahanStepDeltaWitness_total_compensated_total_coefficients
#check NumStability.kahanStepTrace_deltaWitness
#check NumStability.kahanStepTrace_deltaWitnessOfExactSub
#check NumStability.kahanTotalInputCoeff
#check NumStability.kahanTotalStateCoeff
#check NumStability.kahanTrace_deltaWitness
#check NumStability.kahanTrace_deltaWitness_deltaE_bound
#check NumStability.kahanTrace_deltaWitness_deltaS_bound
#check NumStability.kahanTrace_deltaWitness_deltaSub_bound
#check NumStability.kahanTrace_deltaWitness_deltaY_bound
#check NumStability.kahanTrace_deltaWitness_total_compensated_total_coefficients
