import ComputationalMathematics.Algorithms.Summation.Compensated.Kahan.ErrorBounds

/-! Canonical import regression for `ComputationalMathematics.Algorithms.Summation.Compensated.Kahan.ErrorBounds`. -/

#check NumStability.fl_kahanCompensatedTotal_backward_error_source_bound
#check NumStability.fl_kahanFinalCorrectedSum_forward_error_bound_of_backward
#check NumStability.fl_kahanFinalCorrectedSum_relError_le_of_backward_oneSigned
#check NumStability.fl_kahanSum_backward_error_source_bound_of_affine_residualBudget
#check NumStability.fl_kahanSum_backward_error_source_bound_of_exactSubTrace
#check NumStability.fl_kahanSum_backward_error_source_bound_of_exactSubWitnesses
#check NumStability.fl_kahanSum_backward_error_source_bound_of_sourceCoeff_s_bound
#check NumStability.fl_kahanSum_backward_error_source_bound_of_witnessSourceCoeff_s_bound
#check NumStability.fl_kahanSum_forward_error_bound_of_backward
#check NumStability.fl_kahanSum_relError_le_of_backward_oneSigned
#check NumStability.kahanAffineCoeffSteps_prefixSum_exists_mu_abs_le_of_productRadius_and_residualBudget
#check NumStability.kahanAffineCoeffSteps_prefixSum_exists_mu_abs_le_productRadius
#check NumStability.kahanAffineCoeffSteps_prefixSum_exists_mu_inputCoeffResidual
#check NumStability.kahanAffineCoeffSteps_prefixTotal_exists_mu_inputCoeffResidual
#check NumStability.kahan_backward_error_forward_bound_core
