import ComputationalMathematics.Algorithms.Summation.Compensated.Kahan.FiniteErrorBounds

/-! Canonical import regression for `ComputationalMathematics.Algorithms.Summation.Compensated.Kahan.FiniteErrorBounds`. -/

#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_base2_abs_gt
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_base2_abs_gt_of_order_range
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_base2_tail_order_range
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_fastTwoSumCertificates
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_fergusonLe
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_sterbenzLe
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_sub_finite
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_tail_fergusonLe
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_tail_sterbenzLe
#check NumStability.fl_kahanSum_backward_error_source_bound_of_finiteRoundToEven_tail_sub_finite
