import ComputationalMathematics.Algorithms.Summation.Compensated.Kahan.Finite

/-! Canonical import regression for `ComputationalMathematics.Algorithms.Summation.Compensated.Kahan.Finite`. -/

#check NumStability.FiniteKahanPrefixCorrectionSubFinite
#check NumStability.FiniteKahanPrefixCorrectionSubFinite.of_fastTwoSumCertificates
#check NumStability.KahanAddSubFiniteRoundToEvenRealization
#check NumStability.KahanPrefixCorrectionSubExact.of_finiteRoundToEven_fastTwoSumCertificates
#check NumStability.KahanPrefixFastTwoSumFiniteCertificates
#check NumStability.finiteKahanCorrection
#check NumStability.finiteKahanPrefixState
#check NumStability.finiteKahanPrefixState_finiteSystem
#check NumStability.finiteKahanPrefixState_one_of_finiteSystem
#check NumStability.finiteKahanState
#check NumStability.finiteKahanStep
#check NumStability.finiteKahanStepTrace
#check NumStability.finiteKahanStepTrace_e
#check NumStability.finiteKahanStep_zero_of_finiteSystem
#check NumStability.finiteKahanSum
#check NumStability.finiteKahanTrace
#check NumStability.kahanTrace_eq_finiteKahanTrace_of_addSubFiniteRoundToEven
