import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPair

/-! Canonical import regression for `ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPair`. -/

#check NumStability.cstarMatrixColumnPair
#check NumStability.cstarMatrixColumnPair_conjTranspose_mul_columnPair
#check NumStability.cstarMatrixColumnPair_conjTranspose_mul_self
#check NumStability.cstarMatrixColumnPair_conjTranspose_mul_self_eq_one_of_sum
#check NumStability.cstarMatrixColumnPair_inl
#check NumStability.cstarMatrixColumnPair_inr
