import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairPinching

/-! Canonical import regression for `ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairPinching`. -/

#check NumStability.cstarMatrixColumnPair_conjTranspose_mul_eq_compression_mul_conjTranspose_of_commute
#check NumStability.cstarMatrixColumnPair_conjTranspose_mul_reflectionAverage_of_sum
#check NumStability.cstarMatrixColumnPair_mul_columnPair_eq_columnPair_compression_of_commute
#check NumStability.cstarMatrixColumnPair_reflectionAverage_commute_rangeProjection_of_sum
#check NumStability.cstarMatrixColumnPair_reflectionAverage_commute_rangeReflection_of_sum
#check NumStability.cstarMatrixColumnPair_reflectionAverage_compression_of_sum
#check NumStability.cstarMatrixColumnPair_reflectionAverage_conj_rangeReflection_of_sum
#check NumStability.cstarMatrixColumnPair_reflectionAverage_mul_columnPair_of_sum
