import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeReflection

/-! Canonical import regression for `ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeReflection`. -/

#check NumStability.cstarMatrixColumnPairRangeReflection
#check NumStability.cstarMatrixColumnPairRangeReflection_conj_isStrictlyPositive_of_sum
#check NumStability.cstarMatrixColumnPairRangeReflection_isSelfAdjoint
#check NumStability.cstarMatrixColumnPairRangeReflection_isUnit_of_sum
#check NumStability.cstarMatrixColumnPairRangeReflection_mem_unitary_of_sum
#check NumStability.cstarMatrixColumnPairRangeReflection_mul_columnPair_of_sum
#check NumStability.cstarMatrixColumnPairRangeReflection_mul_self_of_sum
#check NumStability.cstarMatrixColumnPair_conjTranspose_mul_rangeReflection_of_sum
