import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealEmbedding

/-! Canonical import regression for `ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealEmbedding`. -/

#check NumStability.finiteComplexCStarMatrix
#check NumStability.finiteComplexCStarMatrix_add
#check NumStability.finiteComplexCStarMatrix_apply
#check NumStability.finiteComplexCStarMatrix_finiteIdMatrix
#check NumStability.finiteComplexCStarMatrix_finset_sum
#check NumStability.finiteComplexCStarMatrix_isSelfAdjoint_of_symmetric
#check NumStability.finiteComplexCStarMatrix_mul
#check NumStability.finiteComplexCStarMatrix_neg
#check NumStability.finiteComplexCStarMatrix_smul
#check NumStability.finiteComplexCStarMatrix_smul_finiteIdMatrix
#check NumStability.finiteComplexCStarMatrix_sub
#check NumStability.finiteComplexCStarMatrix_zero
