import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Spijker.PlanarCrossingBounds.Polynomial

/-! Canonical import regression for `ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Spijker.PlanarCrossingBounds.Polynomial`. -/

#check NumStability.RationalOrderCertificate.arcLength_le_of_planar_analyticBridge
#check NumStability.RationalOrderCertificate.projection_crossing_finset_card_le_two_mul
#check NumStability.spijkerProjectionCrossingPolynomial_natDegree_le
#check NumStability.spijker_projection_crossing_finset_card_le_two_mul
