import ComputationalMathematics.Analysis.MatrixNorms.EntrywiseMaximum

/-! Canonical import regression for `ComputationalMathematics.Analysis.MatrixNorms.EntrywiseMaximum`. -/

#check NumStability.inv_infNorm_le_maxEntryNorm_of_isRightInverse
#check NumStability.maxEntryNorm
#check NumStability.maxEntryNormRect
#check NumStability.maxEntryNormRect_invOf_reindex_equiv_nonsingInv_entry_bound
#check NumStability.maxEntryNormRect_rectMatMul_le
#check NumStability.maxEntryNorm_matrix_mul_le_infNorm_mul_maxEntryNorm
#check NumStability.maxEntryNorm_submatrix_le
