import ComputationalMathematics.Analysis.Perturbation.LeastSquares.GramBasis

/-! Canonical import regression for `ComputationalMathematics.Analysis.Perturbation.LeastSquares.GramBasis`. -/

#check NumStability.exists_lsScaledAugmentedMatrix_kappa2_bounds_of_rightGram_basis_of_rectMatMulVec_injective
#check NumStability.lsScaledAugmentedMatrix_kappa2_bounds_of_rightGram_basis_branch_data
#check NumStability.lsScaledAugmentedMatrix_kappa2_bounds_of_rightGram_basis_branch_data_of_rectMatMulVec_injective
