import ComputationalMathematics.Analysis.SingularValues.WeylMirsky

/-! Canonical import regression for `ComputationalMathematics.Analysis.SingularValues.WeylMirsky`. -/

#check NumStability.Ch14Ext.ch14ext_singularValue_abs_sub_le_of_euclideanLin_diff_bound
#check NumStability.Ch14Ext.ch14ext_singularValue_mul_norm_le_norm_euclideanLin_of_mem_leadSpan
