import ComputationalMathematics.Analysis.Statistics.SampleVariance.RoundingErrorBounds.Theorems

/-! Canonical import regression for `ComputationalMathematics.Analysis.Statistics.SampleVariance.RoundingErrorBounds.Theorems`. -/

#check NumStability.flPrefixCorrectedSumSquaresStep_abs_error_le
#check NumStability.flPrefixCorrectedSumSquaresStep_abs_error_le_prefix_succ
#check NumStability.flPrefixCorrectedSumSquaresTrajectory_abs_error_le_budget
#check NumStability.flPrefixMeanStep_abs_error_le
#check NumStability.flPrefixMeanStep_abs_error_le_prefixMean_succ
#check NumStability.flPrefixMeanTrajectory_abs_error_le_budget
#check NumStability.flSampleVarianceUpdate_abs_error_le_budget
