import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation02.SpectralApproximation.ResidualMomentBounds

/-! Canonical import regression for `ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation02.SpectralApproximation.ResidualMomentBounds`. -/

#check NumStability.sqMagTraceProbability_eventProb_algorithm1ExactEntrywiseEvent_ge_one_sub
#check NumStability.sqMagTraceProbability_eventProb_elementwiseTraceResidual_entry_abs_le_ge_one_sub
#check NumStability.sqMagTraceProbability_eventProb_fl_vecNorm2_rectMatMulVec_elementwiseTraceResidual_le_ge_one_sub
#check NumStability.sqMagTraceProbability_eventProb_forall_fl_vecNorm2_rectMatMulVec_elementwiseTraceResidual_le_ge_one_sub_sum
#check NumStability.sqMagTraceProbability_eventProb_forall_vecNorm2_rectMatMulVec_elementwiseTraceResidual_le_ge_one_sub_sum
#check NumStability.sqMagTraceProbability_eventProb_vecNorm2_rectMatMulVec_elementwiseTraceResidual_le_ge_one_sub
#check NumStability.sqMagTraceProbability_expectationReal_elementwiseTraceResidual_entry_sq_le
#check NumStability.sqMagTraceProbability_expectationReal_elementwiseTraceResidual_frob_sq_le
#check NumStability.sqMagTraceProbability_expectationReal_vecNorm2Sq_rectMatMulVec_elementwiseTraceResidual_le
