import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm03.RandomProjectionPreconditioning.Preconditioning

/-! Canonical import regression for `ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm03.RandomProjectionPreconditioning.Preconditioning`. -/

#check NumStability.rademacherTraceProbability_eventProb_abs_sum_mul_sign_le_ge_one_sub_two_mul_exp_neg_sq_div
