import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.RowNormTraceMGF

/-! Canonical import regression for `ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.RowNormTraceMGF`. -/

#check NumStability.finiteComplexCStarMatrix
#check NumStability.finiteComplexCStarMatrix_add
#check NumStability.finiteComplexCStarMatrix_finset_sum
#check NumStability.finiteComplexCStarMatrix_isSelfAdjoint_of_symmetric
#check NumStability.finiteComplexCStarMatrix_zero
