import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation08.LeastSquaresSketch.FloatingPointObjectiveBounds

/-! Canonical import regression for `ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation08.LeastSquaresSketch.FloatingPointObjectiveBounds`. -/

#check NumStability.leverageTraceProbability_eventProb_fl_lsObjective_le_one_add_eta_of_augmentedSpan
#check NumStability.leverageTraceProbability_eventProb_fl_lsObjective_le_one_add_eta_of_coordinate_quadratic_error
#check NumStability.leverageTraceProbability_eventProb_fl_lsObjective_le_one_add_eta_of_idBasis
