import ComputationalMathematics.Source.Higham.Chapter01.Section12.InstabilityWithoutCancellation.PivotingExample

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter01.Section12.InstabilityWithoutCancellation.PivotingExample`. -/

#check NumStability.noPivotIeeeSinglePartialPivotRoundedLUBackwardError
#check NumStability.noPivotPartialPivotLUBackwardError_zero
#check NumStability.noPivotPartialPivotLUFactSpec
#check NumStability.noPivotPartialPivotPrimitiveRoundedLUBackwardError_of_rounds
#check NumStability.noPivotPartialPivotRoundedLUBackwardError
#check NumStability.noPivotPartialPivotSwap_bijective
