import ComputationalMathematics.Source.Higham.Chapter02.Problem12.ReciprocalProduct.Results.Theorems

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter02.Problem12.ReciprocalProduct.Results.Theorems`. -/

#check NumStability.FloatingPointFormat.problem2_12_ieeeDouble_final_rounding_options_of_mem_window
#check NumStability.FloatingPointFormat.problem2_12_ieeeDouble_reciprocal_finiteNormalRange_of_one_lt_x_lt_two
#check NumStability.FloatingPointFormat.problem2_12_ieeeDouble_reciprocal_product_mem_window_of_one_lt_x_lt_two
#check NumStability.FloatingPointFormat.problem2_12_ieeeDouble_reciprocal_product_rounding_options
#check NumStability.FloatingPointFormat.problem2_12_ieeeDouble_rounds_to_one_of_mem_upper_half_cell
#check NumStability.FloatingPointFormat.problem2_12_ieeeDouble_upper_midpoint_rounds_to_one
