import ComputationalMathematics.Source.Higham.Chapter02.Problem21.HypotenuseNormalization.StandardModelCounterexample.Results

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter02.Problem21.HypotenuseNormalization.StandardModelCounterexample.Results`. -/

#check NumStability.problem2_20_computed_witness_ratio_gt_one
#check NumStability.problem2_20_standard_model_counterexample
#check NumStability.problem2_20_standard_model_counterexample_with_decimal_finite_inputs
