import ComputationalMathematics.Source.Higham.Chapter02.Problem28.IterativeDivisionTermination.UnderflowAwareConvergence.Results

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter02.Problem28.IterativeDivisionTermination.UnderflowAwareConvergence.Results`. -/

#check NumStability.FloatingPointFormat.problem2_27_convergenceTest_eq_div_of_additive_model_normal_branch
#check NumStability.FloatingPointFormat.problem2_27_convergenceTest_eq_div_or_strict_underflow_bound_of_strict_model
#check NumStability.FloatingPointFormat.problem2_27_convergenceTest_eq_div_or_underflow_bound_of_additive_model
#check NumStability.FloatingPointFormat.problem2_27_convergenceTest_fullAccuracy_of_additive_model_normal_branch
#check NumStability.FloatingPointFormat.problem2_27_convergenceTest_fullAccuracy_or_strict_underflow_bound_of_strict_model
#check NumStability.FloatingPointFormat.problem2_27_convergenceTest_fullAccuracy_or_underflow_bound_of_additive_model
#check NumStability.FloatingPointFormat.problem2_27_convergenceTest_iff_eq_div_of_additive_model_normal_branch
#check NumStability.FloatingPointFormat.problem2_27_convergenceTest_iff_fullAccuracy_of_additive_model_normal_branch
#check NumStability.problem2_27_fullAccuracy_of_zero_residual_normal_branch
#check NumStability.problem2_27_fullAccuracy_or_underflow_bound_of_zero_residual_model
#check NumStability.problem2_27_zero_exact_residual_of_additive_model_normal_branch
#check NumStability.problem2_27_zero_exact_residual_or_strict_underflow_bound_of_strict_model
#check NumStability.problem2_27_zero_exact_residual_or_underflow_bound_of_additive_model
