import ComputationalMathematics.Source.Higham.Chapter02.Section06.Discriminant.StandardModel.Counterexample.Results

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter02.Section06.Discriminant.StandardModel.Counterexample.Results`. -/

#check NumStability.problem2_17_computed_discriminant_negative
#check NumStability.problem2_17_standard_model_counterexample
#check NumStability.problem2_17_standard_model_counterexample_with_decimal_finite_inputs
#check NumStability.problem2_17_standard_model_witness_exact_values
