import ComputationalMathematics.Source.Higham.Chapter04

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter04`. -/

#check NumStability.correctionFormulaAbstractCounterexample_not_exact
#check NumStability.finiteKahanTrace_tail_direct_sub_finiteNormalRange_not_finiteSystem_counterexample
#check NumStability.fl_alternativeCompensatedSum_backward_error_source_bound_of_exact_steps_higham_cap
#check NumStability.fl_insertionPowersFour_eq_recursiveSum
#check NumStability.fl_pairwiseSumSixDisplayed
#check NumStability.highamCh4_equation48_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation48_modelStrengthCorrection_bareFPModel
#check NumStability.highamCh4_equation49_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation49_modelStrengthCorrection_bareFPModel
#check NumStability.kahanFF_alternativeCompensatedSum_backward_error
#check NumStability.kahanFF_kahanSum_backward_error
#check NumStability.kahanFF_kahanSum_forward_error
#check NumStability.kahanNoGuardCounterexample_relError_eq_one
#check NumStability.kahanStep_abstractCounterexample_zero_ne_exact
#check NumStability.not_exists_higham48BareFPModelTwoTermSecondOrderBound
#check NumStability.not_exists_higham49BareFPModelTwoTermSecondOrderBound
#check NumStability.not_forall_alternativeCompensated_globalGammaRadius_le_two_u_add_n_sq_u_sq_of_nu_le_tenth
#check NumStability.problem410PriestInput_sum_eq_two
#check NumStability.recursiveSum_problem43_abs_error_bound
