import ComputationalMathematics.Source.Higham.Chapter04.Equation09

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter04.Equation09`. -/

#check NumStability.Higham49BareFPModelTwoTermSecondOrderBound
#check NumStability.fl_kahanSum_forward_error_bound_correctedReturnedMajorant
#check NumStability.highamCh4_equation48_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation49_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation49_modelStrengthCorrection_bareFPModel
#check NumStability.kahanFF_kahanSum_forward_error
#check NumStability.not_exists_higham49BareFPModelTwoTermSecondOrderBound
#check NumStability.not_fl_kahanSum_biasedSmallCounterexample_twoStep_forward_bound_of_Cu_le_half
