import ComputationalMathematics.Source.Higham.Chapter04.Equation08.FiniteRouteLimitations

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter04.Equation08.FiniteRouteLimitations`. -/

#check NumStability.finiteKahanTrace_decimal_tail_direct_sub_eq_neg_eightynine
#check NumStability.finiteKahanTrace_tail_direct_sub_finiteNormalRange_not_finiteSystem_counterexample
#check NumStability.not_forall_finiteKahanTrace_tail_abs_order
#check NumStability.not_forall_finiteKahanTrace_tail_direct_sub_finite
#check NumStability.not_forall_finiteKahanTrace_tail_fergusonLe
#check NumStability.not_forall_finiteKahanTrace_tail_sterbenzLe
