import ComputationalMathematics.Source.Higham.Chapter04.Equation08

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter04.Equation08`. -/

#check NumStability.finiteKahanTrace_tail_direct_sub_finiteNormalRange_not_finiteSystem_counterexample
#check NumStability.fl_kahanSum_backward_error_source_bound_correctedReturnedMajorant
#check NumStability.highamCh4KahanReturnedCounterexampleP5_no_source_bound_one_sixteenth_actual
#check NumStability.highamCh4_equation48_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation48_modelStrengthCorrection_bareFPModel
#check NumStability.highamCh4_equation49_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.kahanBiasedSmallCounterexampleFPModel
#check NumStability.kahanFF_kahanSum_backward_error
#check NumStability.not_exists_higham48BareFPModelTwoTermSecondOrderBound
#check NumStability.not_forall_finiteKahanTrace_tail_abs_order
#check NumStability.not_forall_fl_kahanSum_backward_error_source_bound_bare_fpmodel_exactSubConstants
#check NumStability.not_kahanAffine_residualBudget_inputMajorant_one_of_Cu_le_one
