import ComputationalMathematics.Source.Higham.Chapter04.Equation10

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter04.Equation10`. -/

#check NumStability.fl_alternativeCompensatedSum_backward_error_source_bound_of_exact_steps_higham_cap
#check NumStability.fl_alternativeCompensatedSum_relError_le_of_backward_oneSigned
#check NumStability.kahanFF_alternativeCompensatedSum_backward_error
