import ComputationalMathematics.Source.Higham.Chapter04.Section03

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter04.Section03`. -/

#check NumStability.correctionFormulaAbstractCounterexample_not_exact
#check NumStability.fl_alternativeCompensatedSum_backward_error_source_bound_of_exact_steps_higham_cap
#check NumStability.highamCh4_equation48_modelStrengthCorrection_bareFPModel
#check NumStability.highamCh4_equation49_modelStrengthCorrection_bareFPModel
#check NumStability.kahanFF_alternativeCompensatedSum_backward_error
#check NumStability.kahanFF_kahanSum_backward_error
#check NumStability.kahanFF_kahanSum_forward_error
#check NumStability.kahanNoGuardCounterexample_relError_eq_one
#check NumStability.kahanStep_abstractCounterexample_zero_ne_exact
