import ComputationalMathematics.Source.Higham.Chapter06.Asides

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter06.Asides`. -/

#check NumStability.ch6aside_blockAntidiag_op2_eq
#check NumStability.ch6aside_conditionF_ge_sqrt_n
#check NumStability.ch6aside_maxNorm_not_consistent
#check NumStability.ch6aside_op2_two_sided_unitary_invariant
#check NumStability.higham6_euclideanNorm_hasFDerivAt_of_ne_zero
#check NumStability.higham6_holder_equality_of_powerProfile_sameRay
