import ComputationalMathematics.Source.Higham.Chapter08.Problem08.SingleEntrySingularity.Results.Theorems

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter08.Problem08.SingleEntrySingularity.Results.Theorems`. -/

#check NumStability.higham8_8_bestRankOneSingularUpdate_exists
#check NumStability.higham8_8_bestRankOneSingularUpdate_of_maxInverseEntry
#check NumStability.higham8_8_rankOne_singular_update_abs_eq_inv_abs_inverse_entry
#check NumStability.higham8_8_rankOne_singular_update_den_eq_zero
#check NumStability.higham8_8_rankOne_singular_update_iff
