import ComputationalMathematics.Source.Higham.Chapter08.Problem09.KahanSingularValues.Results.Theorems

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter08.Problem09.KahanSingularValues.Results.Theorems`. -/

#check NumStability.higham8_problem8_9_kahanGram_interlacing
#check NumStability.higham8_problem8_9_kahan_candidate_hasGramEigenvalue
#check NumStability.higham8_problem8_9_kahan_candidate_mem_gramEigenvalues
#check NumStability.higham8_problem8_9_kahan_gram_witness
#check NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_of_interlacing
#check NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_of_lower_bound
#check NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_of_s_eq_one
#check NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_of_s_eq_zero
#check NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_two
#check NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_zero_three_le
#check NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_eq_candidate_zero_two
#check NumStability.higham8_problem8_9_kahan_secondSmallestGramEigenvalue_le_candidate
#check NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue
#check NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_interior_lower_bound
#check NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_interlacing
#check NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_kahanGram_interlacing
#check NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_lower_bound
#check NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_s_eq_one
#check NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_of_s_eq_zero
#check NumStability.higham8_problem8_9_kahan_secondSmallestSingularValue_two
#check NumStability.higham8_problem8_9_kahan_witness_forward
#check NumStability.higham8_problem8_9_kahan_witness_transpose
#check NumStability.higham8_problem8_9_kahan_zero_one_gramEigenvalues_eq_one
