import ComputationalMathematics.Source.Higham.Chapter08.Section03.TriangularSystems.ComparisonConditioningResults.Theorems

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter08.Section03.TriangularSystems.ComparisonConditioningResults.Theorems`. -/

#check NumStability.higham8_4_upperTriangularMMatrix_condAtSolution_le
#check NumStability.higham8_9_comparisonMatrix_condAtSolution_eq
#check NumStability.higham8_9_condAtSolution_le_comparisonMatrix
#check NumStability.higham8_9_lowerTriangular_condAtSolution_le_comparison_eq
#check NumStability.higham8_9_upperTriangular_condAtSolution_le_comparison_eq
