import ComputationalMathematics.Source.Higham.Chapter08.Section03.TriangularSystems.InverseNormResults.Theorems

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter08.Section03.TriangularSystems.InverseNormResults.Theorems`. -/

#check NumStability.higham8_12_WInv_le_ZInvFormula
#check NumStability.higham8_12_absolute_norm_vector_chain
#check NumStability.higham8_12_comparisonInv_le_WInv
#check NumStability.higham8_12_infNorm_chain
#check NumStability.higham8_12_oneNorm_chain
#check NumStability.higham8_12_opNorm2_chain
#check NumStability.higham8_14_full_norm_chain
#check NumStability.higham8_14_oneNorm_upperBound
#check NumStability.higham8_14_opNorm2_upperBound
#check NumStability.higham8_6_comparisonInverseAbsVecInfNorm_le_WInverseAbsVecInfNorm
#check NumStability.higham8_6_comparisonInverseAbsVec_le_WInverseAbsVec
