import ComputationalMathematics.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.ActualComputation.ErrorBounds

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.ActualComputation.ErrorBounds`. -/

#check NumStability.higham10_14_actual_componentwise
#check NumStability.higham10_14_completePivotedPSD_actual_of_noTies
#check NumStability.higham10_14_completePivotedPSD_actual_source_closed
#check NumStability.higham10_23_25_actual_trailing_from_stop
#check NumStability.higham10_25_actual_backwardError_opNorm2
#check NumStability.higham10_28_implies_10_27_actual_residualNorm
