import ComputationalMathematics.Source.Higham.Chapter11.BunchKaufman.Rounded.Factors

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter11.BunchKaufman.Rounded.Factors`. -/

#check NumStability.Higham11RoundedBunchKaufmanExecution.flatAbsProduct
#check NumStability.Higham11RoundedBunchKaufmanExecution.flatD
#check NumStability.Higham11RoundedBunchKaufmanExecution.flatL
#check NumStability.Higham11RoundedBunchKaufmanExecution.flatProduct
#check NumStability.Higham11RoundedBunchKaufmanExecution.permutation
#check NumStability.Higham11RoundedBunchKaufmanExecution.permutedInput
#check NumStability.higham11_2_liftPermOne
#check NumStability.higham11_2_liftPermOne_succ
#check NumStability.higham11_2_liftPermOne_zero
#check NumStability.higham11_2_liftPermTwo
#check NumStability.higham11_2_liftPermTwo_one
#check NumStability.higham11_2_liftPermTwo_succ_succ
#check NumStability.higham11_2_liftPermTwo_zero
