import ComputationalMathematics.Source.Higham.Chapter11.Rook.ExecutorAdapter

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter11.Rook.ExecutorAdapter`. -/

#check NumStability.Higham11RookExecutorAdapter.flMixedD_rookBlockDiagonalSupport
#check NumStability.Higham11RookExecutorAdapter.higham11_5_rook_theorem11_4_product_bound_of_mixedExecutor
#check NumStability.Higham11RookExecutorAdapter.mixedSchedulePartner
#check NumStability.Higham11RookExecutorAdapter.mixedSchedulePartner_consOne_succ
#check NumStability.Higham11RookExecutorAdapter.mixedSchedulePartner_consOne_zero
#check NumStability.Higham11RookExecutorAdapter.mixedSchedulePartner_consTwo_one
#check NumStability.Higham11RookExecutorAdapter.mixedSchedulePartner_consTwo_succ_succ
#check NumStability.Higham11RookExecutorAdapter.mixedSchedulePartner_consTwo_zero
