import ComputationalMathematics.Source.Higham.Chapter13

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13`. -/

#check NumStability.Algorithm13_3Implementation1LocalSpec
#check NumStability.BlockLUFactSpec.eq_of_schurTail_unique_of_right_inverse
#check NumStability.activeBlockIndices13_8
#check NumStability.blockErrorDelta
#check NumStability.blockErrorTheta_le_cubic_of_quadratic_constants
#check NumStability.block_diag_dom_growth_bound_step
#check NumStability.block_diag_dom_schur_inherit
#check NumStability.block_lu_solve_backward_error
#check NumStability.growthFactorEntry_blockMatrixFirstSplitFlat_eq_blockMatrixFlatFin
#check NumStability.higham13_algorithm13_3_firstSplitStageHistoryGrowthFactor_le_two_of_product_bound_diag_update
#check NumStability.higham13_demmel_sharp_multiplier_of_spectral_interval
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_multiplier_bounds_exact_kappa
#check NumStability.higham13_eq13_25_implementation1_spd_family_from_partitioned_computation
#check NumStability.higham13_lemma13_10_conditional_bound
#check NumStability.higham13_table13_1_col_bdd_product_family_from_source_norms
#check NumStability.higham13_theta_conventional_isBigO_cubic
