import ComputationalMathematics.Source.Higham.Chapter13.DemmelSharpMultiplier

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.DemmelSharpMultiplier`. -/

#check NumStability.higham13DemmelLeadingBlock
#check NumStability.higham13_demmel_sharp_multiplier_of_spectral_interval
#check NumStability.higham13_notes_demmel_sharp_multiplier
#check NumStability.higham13_notes_demmel_sharp_multiplier_attained
