import ComputationalMathematics.Source.Higham.Chapter13.Problem04.ActiveStageProducts

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Problem04.ActiveStageProducts`. -/

#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_stage_local_budgets_exact_kappa_of_pivot_right_inverse
