import ComputationalMathematics.Source.Higham.Chapter13.Problem04

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Problem04`. -/

#check NumStability.BlockLUFactSpec.blockMatrixFlatFin_product_eq
#check NumStability.Higham13Eq1322BaseInverseSourceChain
#check NumStability.Higham13Eq1322InverseRatioSourceChain
#check NumStability.Higham13Eq1322LowerComparisonSourceChain
#check NumStability.growthFactorEntry_blockMatrixFirstSplitFlat_eq_blockMatrixFlatFin
#check NumStability.higham13_activeSuffix_dimension_budget_of_global_bound
#check NumStability.higham13_algorithm13_3_activeSuffixStageTailBlock
#check NumStability.higham13_algorithm13_3_firstSplitStageHistoryGrowthFactor_le_two_of_product_bound_diag_update
#check NumStability.higham13_algorithm13_3_first_schur_tail_all_leadingBlockPrefixes_nonsingular_of_all_leadingBlockPrefixes_blockDiagDomCol_diagBound_nonpos
#check NumStability.higham13_algorithm13_3_matrix_infNorm_active_column_dominance_of_first_schur_tail_pivot_right_inverse_pivotInv_eq_nonsingInv_all_leadingBlockPrefixes_blockDiagDomCol_infNorm_diagBound_nonpos_of_pos_dim
#check NumStability.higham13_algorithm13_3_multiplier_bounds_from_source_lblock_budgets_exact_kappa
#check NumStability.higham13_algorithm13_3_multiplier_bounds_from_stageLocalGrowth_base_comparisons_exact_kappa
#check NumStability.higham13_algorithm13_3_schurStageTailBlock
#check NumStability.higham13_algorithm13_3_upperFromMatrixStages_eq13_21_and_matrixStageHistoryGrowthFactor_le_two_of_global_tableau_activeSuffix_matrix_stage_history_final_nonsingInv_mixed_column_mass
#check NumStability.higham13_blockMatrixFirstSplitFlat_nonsingInv_rightInverse_of_det_ne_zero
#check NumStability.higham13_eq13_22_blockLUBudgetChain_succ_from_tail_local_chain_inverse_ratio_matrix_stage_history_exact_kappa_of_det_ne_zero
#check NumStability.higham13_eq13_22_blockLUOneStep_norms_from_matrix_stage_history_first_split_tail_exact_kappa
#check NumStability.higham13_eq13_22_exists_blockLUFact_active_tail_product_from_global_tableau_matrix_stage_history_with_derived_tail_inverse_entry_exact_kappa
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_multiplier_bounds_exact_kappa
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_multiplier_bounds_exact_kappa_of_pivot_right_inverse_of_det_ne_zero
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_stageLocalGrowth_base_comparisons_exact_kappa_of_first_schur_tail_pivot_right_inverse_pivotInv_eq_nonsingInv_all_leadingBlockPrefixes_blockDiagDomCol_infNorm_diagBound_nonpos_of_det_ne_zero
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_stageLocalGrowth_base_comparisons_exact_kappa_of_pivot_right_inverse
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_stageLocalGrowth_inverse_bound_exact_kappa_of_first_schur_tail_pivot_right_inverse_pivotInv_eq_nonsingInv_all_leadingBlockPrefixes_blockDiagDomCol_infNorm_diagBound_nonpos_of_det_ne_zero
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_stage_local_budgets_exact_kappa_of_pivot_right_inverse
#check NumStability.higham13_eq13_22_exists_blockLUFact_succ_product_from_global_tableau_activeSuffix_matrix_stage_history_exact_kappa
#check NumStability.higham13_eq13_22_exists_blockLUFact_succ_product_from_global_tableau_tail_chain_matrix_stage_history_exact_kappa_of_det_ne_zero
#check NumStability.higham13_eq13_22_lower_diagonal_budget_from_right_inverse_growth
#check NumStability.higham13_problem13_4_A11inv_maxEntryNormRect_from_entrywise_bound
#check NumStability.higham13_problem13_4_activeSuffix_A11_det_ne_zero_of_pivot_right_inverse
#check NumStability.higham13_problem13_4_localGrowthEnvelope
