import ComputationalMathematics.Source.Higham.Chapter13.Problem04.ActiveTailProducts

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Problem04.ActiveTailProducts`. -/

#check NumStability.higham13_eq13_22_exists_blockLUFact_active_tail_product_from_global_tableau_matrix_stage_history_with_derived_tail_inverse_entry_exact_kappa
