import ComputationalMathematics.Source.Higham.Chapter13.Problem04.FactorizationProducts.LowerBlockBudgets

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Problem04.FactorizationProducts.LowerBlockBudgets`. -/

#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_multiplier_bounds_exact_kappa
