import ComputationalMathematics.Source.Higham.Chapter13.Problem04.FactorizationProducts.InverseBounds

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Problem04.FactorizationProducts.InverseBounds`. -/

#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_stageLocalGrowth_inverse_bound_exact_kappa_of_first_schur_tail_pivot_right_inverse_pivotInv_eq_nonsingInv_all_leadingBlockPrefixes_blockDiagDomCol_infNorm_diagBound_nonpos_of_det_ne_zero
