import ComputationalMathematics.Source.Higham.Chapter13.Problem04.DeterminantChainProducts

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Problem04.DeterminantChainProducts`. -/

#check NumStability.higham13_eq13_22_blockLUBudgetChain_succ_from_tail_local_chain_inverse_ratio_matrix_stage_history_exact_kappa_of_det_ne_zero
