import ComputationalMathematics.Source.Higham.Chapter13.Problem04.GlobalTableauProducts.ActiveSuffix

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Problem04.GlobalTableauProducts.ActiveSuffix`. -/

#check NumStability.higham13_eq13_22_exists_blockLUFact_succ_product_from_global_tableau_activeSuffix_matrix_stage_history_exact_kappa
