import ComputationalMathematics.Source.Higham.Chapter13.Section03

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Section03`. -/

#check NumStability.activeBlockIndices13_8
#check NumStability.higham13_algorithm13_3_exists_pivotInv_right_inverse_of_blockMatrixNonsingular_blockDiagDomCol_opNorm2_lowerNorm2
#check NumStability.higham13_algorithm13_3_exists_pivotInv_right_inverse_of_blockMatrixNonsingular_blockDiagDomRow_opNorm2_lowerNorm2
#check NumStability.higham13_algorithm13_3_schurStageBlock_tail_shift_generic
#check NumStability.higham13_algorithm13_3_spd_factor_norm_certificates
