import ComputationalMathematics.Source.Higham.Chapter13.Theorem06

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter13.Theorem06`. -/

#check NumStability.block_lu_solve_backward_error
#check NumStability.demmelHighamSchreiber13_6_solve_result_from_forward_back_substitution_specs
#check NumStability.dhs_block_back_substitution_rows_linear_bound_from_conventional_recursive_block_solution
