import ComputationalMathematics.Source.Higham.Chapter14

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14`. -/

#check NumStability.Ch14Ext.ch14ext_hyman_flDet_backward_error_original
#check NumStability.Ch14Ext.ch14ext_problem14_15_det_add_rel_le_of_kappa2_opNorm2_inv_card_guard
#check NumStability.Ch14Ext.ch14ext_rectSchulzStep
#check NumStability.Ch14Ext.ch14ext_schulzIter_tendsto_inverse_of_lt_two_div_norm_sq
#check NumStability.ch14ext_problem14_13_gej_bound_fin_one
#check NumStability.higham14SchulzStep
#check NumStability.higham14_hadamardConditionNumberRaw_negative_one_counterexample
