import ComputationalMathematics.Source.Higham.Chapter14.Algorithm04.FinalDivisionStage.FinalizedErrorFamilies

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Algorithm04.FinalDivisionStage.FinalizedErrorFamilies`. -/

#check NumStability.Ch14Ext.ch14ext_cor146FinalizedForwardAbsoluteRemainder_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor146FinalizedForwardRelativeRemainder_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor146FinalizedForwardTerminal_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor146FinalizedResidualExactNormCorrection_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor146FinalizedResidualPrintedRemainder_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor146FinalizedResidualRemainder_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor146FinalizedResidualTerminal_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor146Finalized_output_error_family_isBigO_u
#check NumStability.Ch14Ext.ch14ext_cor146Finalized_vanishing_family_endpoint
#check NumStability.Ch14Ext.ch14ext_gjeFinalizedFamily_stage2_error_isBigO_unit
#check NumStability.Ch14Ext.ch14ext_gjeFinalizedFamily_theorem14_5_endpoint
#check NumStability.Ch14Ext.ch14ext_gjeForwardFinalDivisionHigherOrder_family_isBigO
#check NumStability.Ch14Ext.ch14ext_gjeResidualFinalDivisionHigherOrder_family_isBigO
#check NumStability.Ch14Ext.ch14ext_gjeResidualFinalizedPrintedHigherOrder_family_isBigO
