import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.FinalizedRunFamilies.ResidualAndForwardEnvelopes

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Corollary07.FinalizedRunFamilies.ResidualAndForwardEnvelopes`. -/

#check NumStability.Ch14Ext.ch14ext_cor147FinalizedForwardPrintedRemainder_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor147FinalizedForwardRelativeRemainder_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor147FinalizedForwardRelativeTerminal_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor147FinalizedForwardVectorRemainder_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor147FinalizedResidualLeadingCorrection_family_isBigO_u
#check NumStability.Ch14Ext.ch14ext_cor147FinalizedResidualRemainder_family_isBigO_u_sq
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_factorProximity_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_forwardCore_difference_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_forwardT1_difference_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_forwardT2_difference_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_forward_bound
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_forward_printed_bound_of_coefficient_lt_one
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_forward_printed_eventually
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_forward_vanishing_family_endpoint
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_inverseProximity_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_printedResidualLeading_difference_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_printedX_difference_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_residual_bound
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_residual_vanishing_family_endpoint
#check NumStability.Ch14Ext.ch14ext_cor147Finalized_vanishing_family_endpoint
