import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.RowDominantCertificates.CumulativeProductBounds

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Corollary07.RowDominantCertificates.CumulativeProductBounds`. -/

#check NumStability.gje_rowDiagDominantUpper_forward_error_relative_infNorm_kappaInf_of_cumulative_product_certificates_c3_cap
#check NumStability.gje_rowDiagDominantUpper_forward_error_relative_infNorm_kappaInf_rowsum_of_cumulative_product_certificates_c3_cap
#check NumStability.gje_rowDiagDominantUpper_forward_error_relative_infNorm_of_cumulative_product_certificates_c3_cap
#check NumStability.gje_rowDiagDominantUpper_residual_of_cumulative_product_certificates
#check NumStability.gje_rowDiagDominantUpper_residual_relative_infNorm_of_cumulative_product_certificates_c3_cap
#check NumStability.gje_rowDiagDominantUpper_residual_relative_infNorm_rowsum_of_cumulative_product_certificates_c3_cap
