import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.WeakDominanceFamilies.ResidualAndForwardBounds

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Corollary07.WeakDominanceFamilies.ResidualAndForwardBounds`. -/

#check NumStability.Ch14Ext.ch14ext_cor147WeakForwardPrintedRemainder_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147WeakForwardRelativeRemainder_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147WeakForwardVectorRemainder_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147WeakResidualRemainder_isBigO
#check NumStability.Ch14Ext.ch14ext_cor147Weak_forward_bound
#check NumStability.Ch14Ext.ch14ext_cor147Weak_forward_printed_bound_of_coefficient_lt_one
#check NumStability.Ch14Ext.ch14ext_cor147Weak_forward_printed_eventually
#check NumStability.Ch14Ext.ch14ext_cor147Weak_forward_vanishing_family_endpoint
#check NumStability.Ch14Ext.ch14ext_cor147Weak_residual_bound
#check NumStability.Ch14Ext.ch14ext_cor147Weak_residual_vanishing_family_endpoint
#check NumStability.Ch14Ext.ch14ext_cor147Weak_vanishing_family_endpoint
