import ComputationalMathematics.Source.Higham.Chapter14.Problem02.TriangularInversion.TwoBlockFirstOrder.Derivations

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Problem02.TriangularInversion.TwoBlockFirstOrder.Derivations`. -/

#check NumStability.Ch14Ext.Higham14Problem142Method1BDerivation.right_residual_firstOrder
#check NumStability.Ch14Ext.Higham14Problem142Method2CDerivation.left_residual_firstOrder
#check NumStability.Ch14Ext.higham14_problem14_2_lowerBlock_mul_sub_one
#check NumStability.Ch14Ext.higham14_problem14_2_lowerBlock_one
#check NumStability.Ch14Ext.higham14_problem14_2_method1B_twoBlock_right_firstOrder
#check NumStability.Ch14Ext.higham14_problem14_2_method2C_twoBlock_left_firstOrder
