import ComputationalMathematics.Source.Higham.Chapter14.Problem05.InverseBasedSolve.ForwardErrorEndpoint

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Problem05.InverseBasedSolve.ForwardErrorEndpoint`. -/

#check NumStability.Ch14Ext.ch14ext_problem14_5_left_quadraticRemainder
#check NumStability.Ch14Ext.ch14ext_problem14_5_left_quadraticRemainder_at_fp
#check NumStability.Ch14Ext.ch14ext_problem14_5_right_quadraticRemainder
