import ComputationalMathematics.Source.Higham.Chapter14.Problem15.SingularValueGuards.DeterminantSignAndRelativeBounds

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Problem15.SingularValueGuards.DeterminantSignAndRelativeBounds`. -/

#check NumStability.Ch14Ext.ch14ext_euclideanLin_realRect_diff_bound
#check NumStability.Ch14Ext.ch14ext_problem14_15_abs_det_add_rel_le_of_kappa2_opNorm2_inv_card_guard
#check NumStability.Ch14Ext.ch14ext_problem14_15_all_index_singularValue_abs_sub_le_opNorm2
#check NumStability.Ch14Ext.ch14ext_problem14_15_det_add_rel_le_of_kappa2_opNorm2_inv_card_guard
#check NumStability.Ch14Ext.ch14ext_problem14_15_det_add_rel_le_of_kappa2_opNorm2_inv_card_guard_of_det_pos
#check NumStability.Ch14Ext.ch14ext_problem14_15_det_add_same_sign_of_kappa2_opNorm2_inv_card_guard
#check NumStability.Ch14Ext.ch14ext_problem14_15_printed_guard_scalar_counterexample
