import ComputationalMathematics.Source.Higham.Chapter14.Section01.InverseErrorAnalysis.ScaledPerturbationEndpoints.ForwardError

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Section01.InverseErrorAnalysis.ScaledPerturbationEndpoints.ForwardError`. -/

#check NumStability.Ch14Ext.ch14ext_eq14_3_quadraticRemainder_isBigO
#check NumStability.Ch14Ext.ch14ext_eq14_6_method1_forward_error_endpoint
#check NumStability.Ch14Ext.ch14ext_eq14_6_method1_quadraticRemainder_isBigO
#check NumStability.Ch14Ext.ch14ext_problem14_5_left_inverse_solve_forward_error_endpoint
#check NumStability.Ch14Ext.ch14ext_problem14_5_left_quadraticRemainder_isBigO
#check NumStability.Ch14Ext.ch14ext_problem14_5_right_inverse_solve_forward_error_endpoint
#check NumStability.Ch14Ext.ch14ext_problem14_5_right_quadraticRemainder_isBigO
