import ComputationalMathematics.Source.Higham.Chapter14.Section02.TriangularInversion.Method1.ForwardErrorEndpoint

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Section02.TriangularInversion.Method1.ForwardErrorEndpoint`. -/

#check NumStability.Ch14Ext.ch14ext_eq14_6_method1_abs_Xhat_envelope
#check NumStability.Ch14Ext.ch14ext_eq14_6_method1_quadraticRemainder
#check NumStability.Ch14Ext.ch14ext_eq14_6_method1_quadraticRemainder_at_fp
