import ComputationalMathematics.Source.Higham.Chapter14.Section05.SpectralConvergence

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Section05.SpectralConvergence`. -/

#check NumStability.Ch14Ext.ch14ext_rectSchulzIter_tendsto_canonicalMoorePenrose_of_lt_two_div_norm_sq
#check NumStability.Ch14Ext.ch14ext_schulzIter_tendsto_inverse_of_lt_two_div_norm_sq
