import ComputationalMathematics.Source.Higham.Chapter15.Lemma02.PNormPowerMethod.PNormRectangular

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter15.Lemma02.PNormPowerMethod.PNormRectangular`. -/

#check NumStability.RectPNormPair.gammaSeq_mono
#check NumStability.RectPNormPair.higham15_lemma15_2_rectangular
#check NumStability.RectPNormPair.higham15_lemma15_2_rectangular_infinity
#check NumStability.RectPNormPair.higham15_lemma15_2_rectangular_one
#check NumStability.RectPNormPair.higham15_lemma15_2_rectangular_strict
#check NumStability.RectPNormPair.higham15_lemma15_2a_rectangular
#check NumStability.RectPNormPair.higham15_lemma15_2b_rectangular
