import ComputationalMathematics.Source.Higham.Chapter15.Problem06.TridiagonalInverseNorm.Recurrences.FactorizationAndNorm

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter15.Problem06.TridiagonalInverseNorm.Recurrences.FactorizationAndNorm`. -/

#check NumStability.Higham15Problem15_6.H15_Problem15_6_of_irreducible_rightInverse
#check NumStability.Higham15Problem15_6.absInvMul_correct
#check NumStability.Higham15Problem15_6.backward_column_scaled
#check NumStability.Higham15Problem15_6.backward_row_scaled
#check NumStability.Higham15Problem15_6.forward_column_scaled
#check NumStability.Higham15Problem15_6.forward_row_scaled
#check NumStability.Higham15Problem15_6.infNorm_correct
#check NumStability.Higham15Problem15_6.lower_factorization
#check NumStability.Higham15Problem15_6.p_correct
#check NumStability.Higham15Problem15_6.qResidual_ne
#check NumStability.Higham15Problem15_6.qResidual_scaled
#check NumStability.Higham15Problem15_6.q_correct
#check NumStability.Higham15Problem15_6.upper_factorization
#check NumStability.Higham15Problem15_6.x_correct
#check NumStability.Higham15Problem15_6.yResidual_ne
#check NumStability.Higham15Problem15_6.yResidual_scaled
#check NumStability.Higham15Problem15_6.y_correct
