import ComputationalMathematics.Source.Higham.Chapter15.Problem06.TridiagonalInverseNorm.Recurrences.ArrayExecution

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter15.Problem06.TridiagonalInverseNorm.Recurrences.ArrayExecution`. -/

#check NumStability.Higham15Problem15_6.H15_Problem15_6_operational_of_irreducible_rightInverse
#check NumStability.Higham15Problem15_6.problem15_6_absInvMulOperational_correct
#check NumStability.Higham15Problem15_6.problem15_6_infNormOperational_correct
