import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.Corrections.ConvergenceStatements

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.Corrections.ConvergenceStatements`. -/

#check NumStability.Ch15.rankOneZeroStartFactor
#check NumStability.Ch15.rankOneZeroStartMatrix
#check NumStability.Ch15.rankOneZeroStartX
#check NumStability.Ch15.rankOneZeroStart_factor_norm_product
#check NumStability.Ch15.rankOneZeroStart_gamma_eq_zero
#check NumStability.Ch15.rankOneZeroStart_xnext_fixed
#check NumStability.Ch15.rankOneZeroStart_xseq_fixed
#check NumStability.Ch15.rankOneZeroStart_y_eq_zero
#check NumStability.Ch15.rankOneZeroStart_z_eq_zero
#check NumStability.Ch15.rankOne_second_step_whatever_x0_false
#check NumStability.Ch15.rankOne_second_step_whatever_x0_unit_opNorm_counterexample
#check NumStability.Ch15.rankOne_two_converges_second_step_of_pairing_ne_zero
