import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.SourceDomain.BoydDomain

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.SourceDomain.BoydDomain`. -/

#check NumStability.Ch15.IsBoydInnerSmoothDomain
#check NumStability.Ch15.rect_general_fderiv_xnext_apply_eq_inv_projectedLemma3B_source_domain
#check NumStability.Ch15.rect_general_fderiv_xnext_eq_boydSmoothRectDerivative_of_two_le
#check NumStability.Ch15.rect_general_xnext_eq_of_stationarity_source_domain
#check NumStability.Ch15.rect_general_xnext_hasFDerivAt_boyd_of_two_le
