import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.SourceDomain.StrongLocalMaximum.Convergence

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.SourceDomain.StrongLocalMaximum.Convergence`. -/

#check NumStability.Ch15.IsBoydConcreteSourceStrongLocalMaximum.hasActualSecondDerivativeGap
#check NumStability.Ch15.higham15_boyd_source_linear_of_strongLocalMaximum_subsequentialLimit
#check NumStability.Ch15.rect_general_boyd_concrete_source_local_linear
#check NumStability.Ch15.rect_general_boyd_concrete_source_local_linear_uniform
