import ComputationalMathematics.Source.Higham.Chapter16.Spectrum.Minimizers

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter16.Spectrum.Minimizers`. -/

#check NumStability.H16_eq16_29_sylvester_practical_error_bound_fl_of_realQuasiSchur_strictBlockMap
#check NumStability.H16_eq16_29_sylvester_practical_error_bound_fl_of_realQuasiSchur_strictBlockMap_mono
#check NumStability.H16_eq16_29_sylvester_practical_error_bound_fl_of_realQuasiSchur_strictBlockMap_mono_scalar
#check NumStability.H16_eq16_29_sylvester_practical_error_bound_fl_of_realQuasiSchur_strictBlockMap_scalar
#check NumStability.H16_eq16_29_sylvester_practical_error_bound_fl_of_schurTriangular
#check NumStability.H16_eq16_29_sylvester_practical_error_bound_fl_of_schurTriangular_mono
#check NumStability.H16_eq16_29_sylvester_practical_error_bound_fl_of_schurTriangular_mono_scalar
#check NumStability.H16_eq16_29_sylvester_practical_error_bound_fl_of_schurTriangular_scalar
#check NumStability.sylvester_practical_error_bound_fl_of_realQuasiSchur_strictBlockMap
#check NumStability.sylvester_practical_error_bound_fl_of_realQuasiSchur_strictBlockMap_mono
#check NumStability.sylvester_practical_error_bound_fl_of_realQuasiSchur_strictBlockMap_mono_scalar
#check NumStability.sylvester_practical_error_bound_fl_of_realQuasiSchur_strictBlockMap_scalar
#check NumStability.sylvester_practical_error_bound_fl_of_schurTriangular
#check NumStability.sylvester_practical_error_bound_fl_of_schurTriangular_mono
#check NumStability.sylvester_practical_error_bound_fl_of_schurTriangular_mono_scalar
#check NumStability.sylvester_practical_error_bound_fl_of_schurTriangular_scalar
