import ComputationalMathematics.Source.Higham.Chapter19.StoredLoop

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter19.StoredLoop`. -/

#check NumStability.H19_Theorem19_13_firstPivot_storedLoopPerturbation_frobNorm_le
#check NumStability.H19_Theorem19_13_firstPivot_storedPanelStep_eq_applyMatrixRect_add_perturbation
#check NumStability.H19_Theorem19_13_storedLoopPerturbation_entry
#check NumStability.H19_Theorem19_13_storedLoopPerturbation_frobNorm_le
#check NumStability.H19_Theorem19_13_storedLoopPerturbation_support
#check NumStability.H19_Theorem19_13_storedPanelStep_eq_applyMatrixRect_add_perturbation
#check NumStability.storageDiscardComparison
#check NumStability.storedLoopPerturbation
