import ComputationalMathematics.Source.Higham.Chapter20.Lemma11

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter20.Lemma11`. -/

#check NumStability.higham20_lemma20_11_equalPositiveRank_pseudoinverse_op2_le
#check NumStability.higham20_lemma20_11_equalRank_pseudoinverse_op2_le
#check NumStability.higham20_lemma20_11_pseudoinverse_op2_eq_recip_rankSingular
