import ComputationalMathematics.Source.Higham.Chapter20.Theorem07.ActualGrowth

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter20.Theorem07.ActualGrowth`. -/

#check NumStability.Theorem20_7.sourceConstructedPivotedStoredQRActiveInput_succ_eq_zero_of_input_eq_zero
#check NumStability.Theorem20_7.sourceConstructedPivotedStoredQRActiveInput_succ_vecNorm2_le_appliedColumn
#check NumStability.Theorem20_7.sourceConstructedPivotedStoredQRSigma_succ_le
