import ComputationalMathematics.Source.Higham.Chapter21

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter21`. -/

#check NumStability.higham21Cond2With_row_scaling
#check NumStability.higham21RowScale
#check NumStability.higham21RowwiseBackwardErrorOmegaR
#check NumStability.higham21_rowScaled_moorePenrose
#check NumStability.higham21_theorem21_3_exact_attainment_or_pairing_obstruction
#check NumStability.higham21_theorem21_4_computed_qhat_omegaR_le_gamma
