import ComputationalMathematics.Source.Higham.Chapter21.Attainability.Results

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter21.Attainability.Results`. -/

#check NumStability.higham21_theorem21_1_dataSource_vecNorm2_le_firstOrder
#check NumStability.higham21_theorem21_1_firstOrder_eq_sources
#check NumStability.higham21_theorem21_1_holder_firstOrder_attainability
#check NumStability.higham21_theorem21_1_holder_firstOrder_upper_and_attainment
#check NumStability.higham21_theorem21_1_holder_firstOrder_upper_bound
#check NumStability.higham21_theorem21_1_nullspaceSource_vecNorm2_le_firstOrder
