import ComputationalMathematics.Source.Higham.Chapter21.Equation09.Results.Core

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter21.Equation09.Results.Core`. -/

#check NumStability.higham21_eq21_9_firstOrder_numerator_le
#check NumStability.higham21_eq21_9_firstOrder_numerator_le_canonical
#check NumStability.higham21_eq21_9_firstOrder_twoTermCoefficient_le
#check NumStability.higham21_eq21_9_firstOrder_twoTermCoefficient_le_operatorCertificate
#check NumStability.higham21_eq21_9_operatorCertificateCoefficient_le_dimensionCoefficient
#check NumStability.higham21_eq21_9_relative_asymptotic_bound
#check NumStability.higham21_eq21_9_relative_bound_with_fixed_radius_remainder
#check NumStability.higham21_eq21_9_relative_firstOrder
