import ComputationalMathematics.Source.Higham.Chapter21.Theorem03.Attainment

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter21.Theorem03.Attainment`. -/

#check NumStability.higham21_theorem21_3_etaF_is_attained_of_pairing_ne_zero
#check NumStability.higham21_theorem21_3_exact_attainment_or_pairing_obstruction
#check NumStability.higham21_theorem21_3_scalar_attainable_costs_not_closed
