import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.RowwiseBackwardError

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter21.Theorem04.RowwiseBackwardError`. -/

#check NumStability.Higham21RowwiseBackwardErrorFeasible
#check NumStability.higham21RowwiseBackwardErrorOmegaR_le_of_fixed_b_certificate
#check NumStability.higham21_theorem21_4_computed_qhat_omegaR_le_gamma
