import ComputationalMathematics.Source.Higham.Chapter22

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter22`. -/

#check NumStability.Ch22B.ch22bComplexConfluent_theorem12_3_exact_q_bound
#check NumStability.Ch22B.ch22b_refinement_converges_via_ch12
#check NumStability.higham22_corollary22_7_monomial_residual
#check NumStability.higham22_corollary22_7_monomial_residual_closed
#check NumStability.higham22_problem22_7_extrema_kappa2_le_two
