import ComputationalMathematics.Source.Higham.Chapter26.MultidirectionalSearch.RegularSimplex

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter26.MultidirectionalSearch.RegularSimplex`. -/

#check NumStability.higham26RegularA
#check NumStability.higham26RegularB
#check NumStability.higham26RegularSimplex
#check NumStability.higham26RegularSimplex_base
#check NumStability.higham26RegularSimplex_base_edge_length
#check NumStability.higham26RegularSimplex_base_edge_sq
#check NumStability.higham26RegularSimplex_other_edge_length
#check NumStability.higham26RegularSimplex_other_edge_sq
#check NumStability.higham26Regular_coeff_base_sq
#check NumStability.higham26Regular_coeff_pair_sq
