import ComputationalMathematics.Source.Higham.Chapter28.Section04.Pascal.SingularizingPerturbation

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter28.Section04.Pascal.SingularizingPerturbation`. -/

#check NumStability.opNorm2_pascalInverseMatrix_eq_inv_smallestEigenvalue
#check NumStability.opNorm2_pascalOptimalSingularizingPerturbation
#check NumStability.pascalOptimalPerturbation_is_operator2_minimal
#check NumStability.pascal_singularizing_perturbation_norm_lower_bound
