import ComputationalMathematics.Source.Higham.Chapter28.Section05.TridiagonalToeplitz.SineEigenpairs

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter28.Section05.TridiagonalToeplitz.SineEigenpairs`. -/

#check NumStability.complexSymmetricToeplitz_sine_eigenpair
#check NumStability.generalToeplitzSineVector_ne_zero
#check NumStability.generalToeplitz_complex_sine_eigenpair_of_super_ne_zero
#check NumStability.generalToeplitz_sine_eigenpair
#check NumStability.generalToeplitz_unrestricted_complex_eigenpair
#check NumStability.tridiagonalToeplitz_p522_unrestricted_eigenvalue
