import ComputationalMathematics.Algorithms.LinearSystems.LeastSquares

/-! Canonical import regression for `ComputationalMathematics.Algorithms.LinearSystems.LeastSquares`. -/

#check NumStability.Higham20DirectLSRefinementRun.step
#check NumStability.Higham20EliminationActual.exactPivotedQRSwapSeq_fix_prefix
#check NumStability.LSEKKTSystem.iff_linearMap_eq
#check NumStability.MGSAugmentedLSFactorization.A_eq
#check NumStability.RectLSNormalEquations.of_permuteCols
#check NumStability.Theorem20_7.applyProd_sub
#check NumStability.gqrBQBlock_add
#check NumStability.lsQRTallBlock_zero
#check NumStability.lsScaledAugmentedMatrix_mulVec
#check NumStability.lsVecNorm2Sq_append
#check NumStability.rectRightGramBasisSingularValue_pos_of_rectMatMulVec_injective
#check NumStability.rectTopBlock_add
#check NumStability.storedHouseholderQRRhsSeq_zero
#check NumStability.storedQRActiveMaxPivotColumn_pivotMax
