import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra

/-! Canonical import regression for `ComputationalMathematics.Algorithms.RandomizedLinearAlgebra`. -/

#check NumStability.countSketchHashProbability_eventProb_injective_ge_one_sub_pair_sum
#check NumStability.countSketchHashProbability_eventProb_pairCollision_eq_inv
#check NumStability.countSketchProbability_eventProb_flSparseGramDot_rowGram_frob_error_le_ge_one_sub
#check NumStability.countSketchProbability_expectationReal_rowGram_frob_error_sq_le
#check NumStability.countSketchUniformRowTraceProbability
#check NumStability.countSketchUniformRowTraceProbability_eventProb_uniformRowSampleGram_rowGram_frob_error_le_ge_one_sub
#check NumStability.euclideanVec_apply
#check NumStability.finCardIndex_le
#check NumStability.frobNormRect_const_square
#check NumStability.hitCount_eq_sum_indicator
#check NumStability.leverageRightGramCongruence_neg
#check NumStability.rademacherSign_sq
#check NumStability.rectRightGram_finitePSD
#check NumStability.rightGramCongruence_add
#check NumStability.rowGram_eq_id_of_orthonormal_columns
#check NumStability.rowNormSq_nonneg
#check NumStability.rowNormSq_sq_eq_sum_pair
#check NumStability.rowOuterGramSample_symmetric
#check NumStability.rowSampleLSResidualWithBasisScale_eq_coord
#check NumStability.rowSqNormTraceProbMass_snoc
#check NumStability.sqMagProb_nonneg
#check NumStability.sqMagTraceProbMass_snoc
#check NumStability.uniformRowProb_nonneg
#check NumStability.uniformRowTraceProbMass_marginal_two_ne
#check NumStability.uniformRowTraceProbMass_snoc
#check NumStability.uniformRowTraceProbability_eventProb_fl_uniformRowSampleGramDot_rowGram_frob_error_le_ge_one_sub
