import ComputationalMathematics.Algorithms.PolynomialEvaluation

/-! Canonical import regression for `ComputationalMathematics.Algorithms.PolynomialEvaluation`. -/

#check NumStability.ch5deriv_pair_forward_error_bound
#check NumStability.flHighamBidiagonalSolve_succ
#check NumStability.fl_add_abs_error_bound
#check NumStability.fl_complexHornerRunningBound_nonneg
#check NumStability.fl_hornerDerivativeDesc_first_derivative_error_bound
#check NumStability.higham5_exists_fast_scheme_degree_gt_four
#check NumStability.higham5_patersonStockmeyer_eq_P1
#check NumStability.infNorm_add_le
#check NumStability.rootProductEvalFrom_smul
