import ComputationalMathematics.Source.Higham.Chapter07

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter07`. -/

#check NumStability.Higham7PropertyA.diagCongr
#check NumStability.ch7SymmetricDiagEquilibratingScale2
#check NumStability.ch7_inverseLinearizedRatio_le
#check NumStability.eq_7_17_kahan_symbolic_example
#check NumStability.eq_7_26_relative_distance_to_singularity_eq_inv_condition_number
#check NumStability.eq_7_31_componentwise_bound
#check NumStability.higham7_25_inverseSensitivity_nonneg
#check NumStability.higham7_26_abs_entrySign
#check NumStability.higham7_26_exists_functionalCycle
#check NumStability.higham7_26_spectralRadius_ne_top
#check NumStability.higham7_3_rectangular
#check NumStability.theorem7_5_literal_printed_row_inf_scale_counterexample
