import ComputationalMathematics.Source.Higham.Chapter05

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter05`. -/

#check NumStability.Ch5LejaListTrace.drop
#check NumStability.Higham5QuinticData.mk.inj
#check NumStability.beginnerPowerEvalAsc_eq_polyAsc
#check NumStability.ch5deriv_value_forward_error_bound
#check NumStability.ch5newton_conj_pred
#check NumStability.dividedDifferenceStep_of_gt
#check NumStability.flDividedDifferenceUnwindStep_abs_error
#check NumStability.flHighamBidiagonalSolve_last
#check NumStability.fl_complexHornerRunningFold_fst_eq
#check NumStability.higham5_ps_powerTable_succ
#check NumStability.highamBidiagonalU_diag
#check NumStability.hornerSyntheticDivisionDesc_spec
#check NumStability.lejaPrefixProduct_succ
#check NumStability.matrixHornerP3Step_infNorm_lipschitz
#check NumStability.matrixPolyP3InfNormMajorant_nonneg
#check NumStability.newtonForm_eq_newtonFormNested
#check NumStability.polyAsc_evenOdd_split
#check NumStability.polyDescAbs_nonneg
#check NumStability.polyDescDerivAbs_nonneg
#check NumStability.relErrorCounter_one
