import ComputationalMathematics.Source.Higham.Chapter09

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter09`. -/

#check NumStability.Higham9Theorem99Direct.upperTailMass_succ
#check NumStability.higham9_11_bohteBound_pos
#check NumStability.higham9_12_cos_sum_odd
#check NumStability.higham9_14_absLU_diag_sum
#check NumStability.higham9_14_completePivotTrace_to_rookTrace
#check NumStability.higham9_14_exactPivot_succ
#check NumStability.higham9_14_exists_threshold_actual_diagDominant_growth_bound_16
#check NumStability.higham9_14_f_le_h
#check NumStability.higham9_15_barrlund_normwise_source_ratio_without_min_premise
#check NumStability.higham9_15_chi_nonneg
#check NumStability.higham9_15_sun_mixed_resolvent_normalized_bounds
#check NumStability.higham9_16_log3_ge
#check NumStability.higham9_1_exists_rookPivotChoice
#check NumStability.higham9_24_scaled_system_equiv
#check NumStability.higham9_26_stage_entry_abs_le
#check NumStability.higham9_2_rectRoundedLoopSourceCertificate
#check NumStability.higham9_5_computedMultiplier_infNorm
#check NumStability.higham9_7_extremal_step_descent
#check NumStability.higham9_7_wilkinsonGrowth_lu
#check NumStability.higham9_8_complex_source_theorem
#check NumStability.higham9_9_complex_reducedEntry_eq_upper
#check NumStability.higham9_LUBackwardError_mono
