import ComputationalMathematics.Source.Higham.Chapter14.Corollary07

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter14.Corollary07`. -/

#check NumStability.Ch14Ext.ch14ext_cor147Finalized_forward_bound
#check NumStability.Ch14Ext.ch14ext_cor147Weak_forward_bound
#check NumStability.Ch14Ext.ch14ext_cor147_absLU_rowSum_le
#check NumStability.Ch14Ext.ch14ext_luBackward_factorProximity_isBigO
#check NumStability.gje_rowDiagDominantUpper_residual_of_cumulative_product_certificates
