import ComputationalMathematics.Source.Higham.Chapter16.Section03.PerturbationAndConditioning

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter16.Section03.PerturbationAndConditioning`. -/

#check NumStability.H16_eq16_22_sylvester_perturbation_equation
#check NumStability.H16_eq16_26_isLeast_sylvesterSepRatios
#check NumStability.H16_eq16_27_lyapunov_condition_of_sigmaMin
