import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError`. -/

#check NumStability.H16_eq16_17_sylvester_eta_residual_amplification_of_svd
#check NumStability.H16_eq16_9_sylvesterResidualRect_eq
