import ComputationalMathematics.Source.Higham.Chapter16.Section04.PracticalErrorBounds

/-! Canonical import regression for `ComputationalMathematics.Source.Higham.Chapter16.Section04.PracticalErrorBounds`. -/

#check NumStability.H16_eq16_28_lyapunov_aposteriori_bound_diagonal
#check NumStability.H16_eq16_29_lyapunov_relative_error_le_of_sepLowerBound_computed_residual_budget
#check NumStability.NormEstimator.sylvester_practical_error_bound_with_norm1_estimator
