import NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra

/-! Isolated API witness for `NumStability.Analysis.CStarMatrices.FiniteMatrixAlgebra`; authored declaration names are retained. -/

#check @NumStability.cstarMatrixBlockDiagonal_add
#check @NumStability.cstarMatrixBlockDiagonal_mul_columnPair
#check @NumStability.cstarMatrixColumnPair_inl
#check @NumStability.cstarMatrixColumnPair_reflectionAverage_compression_of_sum
#check @NumStability.cstarMatrixColumnPairRangeProjection_isSelfAdjoint
#check @NumStability.cstarMatrixColumnPairRangeReflection_isSelfAdjoint
#check @NumStability.cstarMatrix_complex_finiteDimensional
#check @NumStability.cstarMatrix_le_of_matrix_le
#check @NumStability.finiteComplexCStarMatrix_add
#check @NumStability.finiteComplexCStarMatrix_nonneg_of_finitePSD
#check @NumStability.cstarMatrixProjectionReflection_mul_of_mul_eq_self
#check @NumStability.cstarMatrix_compression_add
#check @NumStability.cstarMatrix_add_mul_rect
#check @NumStability.cstarMatrix_reflectionAverage_conj_of_involutive
#check @NumStability.cstarMatrix_unitary_conj_isStrictlyPositive
