import NumStability.Analysis.TestMatrices

/-! Isolated API witness for `NumStability.Analysis.TestMatrices`; authored declaration names are retained. -/

#check @NumStability.cauchyMatrix_apply
#check @NumStability.prod_Ioi_succ_fin
#check @NumStability.cauchyLower_diagonal
#check @NumStability.companionMatrix_mulVec_companionEigenvector
#check @NumStability.Matrix.IsSimilar.rank_eq
#check @NumStability.companionExceptionalQuadratic_eq_mul
#check @NumStability.companionRankMinor_det
#check @NumStability.gaussianUnitDirectionValue_mem
#check @NumStability.standardGaussianVectorMeasure_mean
#check @NumStability.shiftedHilbertMatrix
#check @NumStability.altChooseShift_eq
#check @NumStability.hilbert_gram_sum
#check @NumStability.log_hilbertRNat_diag_sq
#check @NumStability.arctan_le_self_of_nonneg
#check @NumStability.matrixListProduct_isOrthogonal
#check @NumStability.measurable_stewartFirstSection
#check @NumStability.orthogonalSphereNonempty
#check @NumStability.orthogonalTailBlockMatrix_mem
#check @NumStability.realSquareMatrixBorelSpace
#check @NumStability.orthogonalGroup_action_pretransitive
#check @NumStability.pascalLower_det
#check @NumStability.pascalLastKernel_last
#check @NumStability.pascalMatrix_quadratic_pos
#check @NumStability.pascalOscillationFRange_card
#check @NumStability.compoundMatrix_one
#check @NumStability.boolSignChangeCount_not
#check @NumStability.pascalMatrix_isSymmetricFiniteMatrix
#check @NumStability.compoundMatrix_mul
#check @NumStability.randsvdMatrix
#check @NumStability.measurable_stewartTailRotation
#check @NumStability.measurable_householderSign
#check @NumStability.stewartInputSplitEquiv_fst
#check @NumStability.measurable_stewartSignDiagonal
#check @NumStability.split_succ
#check @NumStability.GinibreRawMatrix
#check @NumStability.integral_ginibreProjectiveRadial
#check @NumStability.tridiagonalToeplitz_diag
#check @NumStability.tridiagonalToeplitz_mulVec_apply
