import NumStability.Source.Higham.Chapter15

/-! Isolated API witness for `NumStability.Source.Higham.Chapter15`; authored declaration names are retained. -/

#check @NumStability.Ch15.PNormPair.gammaSeq_bddAbove
#check @NumStability.Ch15.gammaSeq_one_mono
#check @NumStability.RectPNormPair.higham15_algorithm15_1_rectangular_step
#check @NumStability.Higham15.H15_Algorithm15_3_spec
#check @NumStability.Higham15.H15_Algorithm15_4_gamma
#check @NumStability.Higham15.H15_Algorithm15_4_lower_bound
#check @NumStability.Ch15.linpackY_solves
#check @NumStability.Ch15.linpackD_isPlusMinusOne
#check @NumStability.Ch15.eq15_2_subdifferential_singleton_general
#check @NumStability.Ch15.PNormPair.eq15_2_zof_isSubgradient
#check @NumStability.Ch15.eq15_3_gradient_two_eq_zero_of_fixed
#check @NumStability.Ch15.eq15_3_directional_general_of_full_rank
#check @NumStability.Ch15.eq15_3_directional_two
#check @NumStability.Ch15.eq15_4_normalize2_one
#check @NumStability.Ch15.PNormPair.eq15_5_subgradient_inequality
#check @NumStability.Higham15.H15_eq15_6_A_mul_b
#check @NumStability.Ch15.dixon_sqrt_quadForm_le_opNorm2
#check @NumStability.Ch15.rect_gammaSeq_monotone
#check @NumStability.Ch15.boydCarrier_fixedPoint_unique
#check @NumStability.Ch15.lemma152_one
#check @NumStability.RectPNormPair.gammaSeq_mono
#check @NumStability.Ch15.ch15p4_Ainv_eq
#check @NumStability.Higham15Problem15_6.problem15_6_infNormOperational_correct
#check @NumStability.Higham15Problem15_6.tridiag_mulVec_entry
#check @NumStability.Higham15Problem15_6.p_correct
#check @NumStability.Higham15Problem15_6.subAt_of_lt
#check @NumStability.Higham15Problem15_6.finVectorAt_of_lt
#check @NumStability.Higham15Problem15_6.rowArrayOperational_get
#check @NumStability.argmaxAbs_spec
#check @NumStability.Higham15.H15_kappaOne_nonneg
#check @NumStability.Ch15.IsBoydConcreteStrongLocalMaximum
#check @NumStability.Ch15.strictMaximum_does_not_imply_negative_quadratic_term
#check @NumStability.Ch15.higham15TransientNilpotent_sq
#check @NumStability.Ch15.rankOneZeroStart_y_eq_zero
#check @NumStability.Ch15.pNormPair_inf_terminates_by_n_plus_one
#check @NumStability.RectPNormPair.higham15_rectangular_infinity_counterexample_stops_at_four
#check @NumStability.RectPNormPair.one_terminates_by_n_plus_one_rect
#check @NumStability.Ch15.rect_gammaSeq_tendsto_ciSup
#check @NumStability.Ch15.higham15_boyd_global_of_nonnegative_irreducibleGram
#check @NumStability.Ch15.PNormPair.exists_gammaSeq_limit
#check @NumStability.Ch15.boydScalar_xseq_basis_eq
#check @NumStability.Ch15.higham15_boyd_concrete_linear_of_strongLocalMaximum_subsequentialLimit
#check @NumStability.Ch15.higham15_boyd_local_linear_of_fderiv_norm_lt
#check @NumStability.Ch15.higham15_boyd_local_corrected_of_actual_derivative_power_stable
#check @NumStability.Ch15.higham15_boyd_local_linear_of_fderiv_power_stable
#check @NumStability.Ch15.boydConstrainedLagrangianLine_hasDerivAt
#check @NumStability.Ch15.boyd_inner_rowwise_domain_zero_row_example
#check @NumStability.Ch15.rect_general_boyd_concrete_local_linear
#check @NumStability.Ch15.rect_general_xnext_hasFDerivAt_boyd_of_two_le
#check @NumStability.Ch15.rect_general_xnext_hasFDerivAt_boyd
#check @NumStability.Ch15.rect_general_xnext_hasFDerivAt_boyd_of_rowwise_lt_two
#check @NumStability.Ch15.boydConstrainedLagrangianFirst_hasDerivAt_rowwise_source_domain
#check @NumStability.Ch15.rect_general_boyd_concrete_source_local_linear
#check @NumStability.Ch15Closure.H15_Theorem15_7_of_absLU_eq
#check @NumStability.higham15_6_dixon_closed
#check @NumStability.Ch15.H15_Theorem15_7
#check @NumStability.Ch15.H15_Theorem15_8
#check @NumStability.Ch15.H15_Theorem15_9
#check @NumStability.Ch15IkebeClosure.H15_Theorem15_9_of_irreducible_rightInverse
