import NumStability.Source.LeVeque.Chapter01

/-! Isolated API witness for `NumStability.Source.LeVeque.Chapter01`; authored declaration names are retained. -/

#check @NumStability.leveque01_acoustics_hasConservationForm
#check @NumStability.leveque01_acousticsMatrixEigenvalues
#check @NumStability.leveque01_acousticsLeftMode
#check @NumStability.leveque01_advectionLinearFlux
#check @NumStability.leveque01_advectionWaveIdentity
#check @NumStability.leveque01_dimensionalSplitting
#check @NumStability.leveque01_eigenvaluesAreWaveSpeeds
#check @NumStability.leveque01_equation01_constantLinearSystem
#check @NumStability.leveque01_equation02_isOneDimensionalSpecialization
#check @NumStability.leveque01_equation03_scalarAdvection
#check @NumStability.leveque01_equation03_advectedProfile
#check @NumStability.leveque01_equation04_profileMovesRight
#check @NumStability.leveque01_equation04_scalarHyperbolicOneWayModel
#check @NumStability.leveque01_equation05_linearAcoustics
#check @NumStability.leveque01_equation06_acousticsMatrixForm
#check @NumStability.leveque01_equation07_pressureWave
#check @NumStability.leveque01_equation08_conservationLawAt_iff
#check @NumStability.leveque01_equation09_quasilinearForm
#check @NumStability.leveque01_equation10_fluxBalance
#check @NumStability.leveque01_equation11_riemannData
#check @NumStability.leveque01_finiteVolumeCellAverage_spec
#check @NumStability.leveque01_finiteVolumeFluxUpdate_spec
#check @NumStability.leveque01_heterogeneousMaterialCellAverage
#check @NumStability.leveque01_hyperbolicMatrixDefinition
#check @NumStability.leveque01_integralLaw_impliesDifferentialLaw_of_smooth
#check @NumStability.leveque01_linearFlux_specializesEquation01
#check @NumStability.leveque01_riemannInterfaceFlux
#check @NumStability.leveque01_scalarEquation_isHyperbolic
