import NumStability.Source.Higham.Chapter28.Section02

/-! Isolated API witness for `NumStability.Source.Higham.Chapter28.Section02`; authored declaration names are retained. -/

#check @NumStability.pascalStirling_two_mul_div_sq
#check @NumStability.integral_realGinibre_det_sq
#check @NumStability.realGinibre_hypergeometric_one
#check @NumStability.ch28gf_slice_eq
#check @NumStability.realEigenvalueCount_le
#check @NumStability.ginibreAbsDetScaleSix_sq
#check @NumStability.integral_standardGaussian_sq
#check @NumStability.gaussianPDFReal_zero_one_zero
#check @NumStability.ginibreCorollary31Factor_shift_two
#check @NumStability.ginibreCorollary31Factor_mul_increment
#check @NumStability.ch28gf_integrable_hw
#check @NumStability.ginibreFinMatrixCoordinates
#check @NumStability.realEigenvalueCount_one
#check @NumStability.abs_ginibreAlternatingCount_le
#check @NumStability.hilbertMatrix_quadraticForm
#check @NumStability.measurable_ginibreIncidenceChart
#check @NumStability.LinearMap.det_lowerBlock
#check @NumStability.ginibrePlaneShear_inv_mul
#check @NumStability.det_ginibreIncidenceFull_sub_externalShift
#check @NumStability.iUnion_ginibreIncidenceRankPieceBelow
#check @NumStability.expectedRealEigenvalueCount_two
#check @NumStability.Matrix.reindex_mulVec_comp_symm
#check @NumStability.map_complexMatrixCharpoly_conj
#check @NumStability.gaussianConeProduct_real
#check @NumStability.det_ginibreLeftMixLinearMap
#check @NumStability.ginibrePlaneChartMatrix_charpoly_factor
#check @NumStability.ginibrePlane_stdBasis_repr_apply
#check @NumStability.fderiv_ginibrePlaneChart
#check @NumStability.integrable_standardGaussianVectorDensity
#check @NumStability.realGinibreDensityReal_pos
#check @NumStability.trace_ginibreTracelessPart
#check @NumStability.measurable_abs_det_matrix
#check @NumStability.strictlyPositiveMatrixSet_nonempty
#check @NumStability.realGinibreMeasure_univ
#check @NumStability.complexUpperEigenvalueCount_eq
#check @NumStability.ginibre_normalized_eigenpair
#check @NumStability.eval_complexMatrixCharpoly
#check @NumStability.neg_one_pow_rootRank_mul_abs_det
#check @NumStability.realGinibreParityIncrement
#check @NumStability.ginibreCorollary31Factor_product_shift_two
#check @NumStability.gaussianPDFReal_zero_one_prod
#check @NumStability.ginibreAlternatingBelowCharpoly_charpoly
#check @NumStability.ginibreOrderedGaussianKernelMoment_sub_eq
#check @NumStability.ginibreAlternatingCount
#check @NumStability.sum_fin_ite_lt_eq_ginibreAlternatingCount
#check @NumStability.tendsto_pow_mul_exp_mul_sub_sq_pow
#check @NumStability.lintegral_ginibreFixedFiber
#check @NumStability.uniformPositivePerronAlmostSure
