import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.LinearProduction
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.RectangleBalance
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.RectangleBalanceTemporalDerivative
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannDataJump
import ComputationalMathematics.Analysis.PartialDifferentialEquations.InitialValue.Examples.LocalMaterialInterface
import ComputationalMathematics.Topology.Order.Jump

#check NumStability.HasJumpAt
#print axioms NumStability.HasJumpAt
#check NumStability.HasJumpAt.not_continuousAt
#print axioms NumStability.HasJumpAt.not_continuousAt
#check NumStability.HasJumpAt.congr
#print axioms NumStability.HasJumpAt.congr
#check NumStability.IsRiemannData.hasJumpAt
#print axioms NumStability.IsRiemannData.hasJumpAt
#check NumStability.hasJumpAt_and_iff_product_traces
#print axioms NumStability.hasJumpAt_and_iff_product_traces
#check NumStability.LocalMaterialInterface.varyingMedium
#print axioms NumStability.LocalMaterialInterface.varyingMedium
#check NumStability.LocalMaterialInterface.varyingMedium_hasJumpAt
#print axioms NumStability.LocalMaterialInterface.varyingMedium_hasJumpAt
#check NumStability.LocalMaterialInterface.varyingMedium_not_isRiemannData
#print axioms NumStability.LocalMaterialInterface.varyingMedium_not_isRiemannData
#check NumStability.LocalMaterialInterface.varyingMedium_interface_witness
#print axioms NumStability.LocalMaterialInterface.varyingMedium_interface_witness
#check NumStability.LocalMaterialInterface.product_jump_with_constant_medium
#print axioms NumStability.LocalMaterialInterface.product_jump_with_constant_medium
#check NumStability.IsRectangleBalanceLawSolution
#print axioms NumStability.IsRectangleBalanceLawSolution
#check NumStability.IsRectangleBalanceLawSolution.integrated_source_eq_mass_defect
#print axioms NumStability.IsRectangleBalanceLawSolution.integrated_source_eq_mass_defect
#check NumStability.IsRectangleBalanceLawSolution.rectangle_conservation_iff_source_integral_zero
#print axioms NumStability.IsRectangleBalanceLawSolution.rectangle_conservation_iff_source_integral_zero
#check NumStability.IsRectangleBalanceLawSolution.conservation_iff_source_integrals_zero
#print axioms NumStability.IsRectangleBalanceLawSolution.conservation_iff_source_integrals_zero
#check NumStability.IsRectangleBalanceLawSolution.not_conservation_iff_exists_nonzero_source_integral
#print axioms NumStability.IsRectangleBalanceLawSolution.not_conservation_iff_exists_nonzero_source_integral
#check NumStability.IsRectangleBalanceLawSolution.integrated_source_unique
#print axioms NumStability.IsRectangleBalanceLawSolution.integrated_source_unique
#check NumStability.IsRectangleBalanceLawSolution.hasDerivAt_mass_ae
#print axioms NumStability.IsRectangleBalanceLawSolution.hasDerivAt_mass_ae
#check NumStability.isRectangleBalanceLawSolution_zero_iff
#print axioms NumStability.isRectangleBalanceLawSolution_zero_iff
#check NumStability.linearAmplitude_isRectangleBalanceLawSolution
#print axioms NumStability.linearAmplitude_isRectangleBalanceLawSolution
#check NumStability.linearAmplitude_hasDerivAt_mass
#print axioms NumStability.linearAmplitude_hasDerivAt_mass
#check NumStability.linearAmplitude_isBalanceLawSolutionAt
#print axioms NumStability.linearAmplitude_isBalanceLawSolutionAt
#check NumStability.riemannStep_unitCell
#print axioms NumStability.riemannStep_unitCell
#check NumStability.riemannStep_signed_source_integral
#print axioms NumStability.riemannStep_signed_source_integral
#check NumStability.riemannStep_source_nonvacuity
#print axioms NumStability.riemannStep_source_nonvacuity
