import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.QRTransfer.Signed
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.ForwardError.ComputedOutput.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.MinimumNorm.Solvers.Executor.Core
import ComputationalMathematics.Source.Higham.Chapter21.Theorem01.ComponentwisePerturbation.RankStability
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.ForwardError.Forward
import ComputationalMathematics.Source.Higham.Chapter21.Equation11.Forward
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.Forward
import ComputationalMathematics.Source.Higham.Chapter21.Equation11.ActualOutput
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.ActualOutput
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.Signed

/-!
# Algorithms.Underdetermined.Higham21SNESigned

Import-only historical compatibility facade for the W04 migration.
-/
