import ComputationalMathematics.Algorithms.LinearSystems.QR.HouseholderQApply
import ComputationalMathematics.Source.Higham.Chapter21.Attainability.Results
import ComputationalMathematics.Source.Higham.Chapter21.Equation11.UniformEnvelope.Core
import ComputationalMathematics.Source.Higham.Chapter21.Equation08.Results.Core
import ComputationalMathematics.Source.Higham.Chapter21.Equation09.Results.Core
import ComputationalMathematics.Source.Higham.Chapter21.Equation11.Results.Core
import ComputationalMathematics.Source.Higham.Chapter21.Equation11.ScalarCase.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.QR.Givens.BackwardError.Core
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.GivensQMethod.Core
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.RowwiseBackwardError
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.QR.Givens.EndToEnd.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.QR.Givens.Rounded.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.QR.ModifiedGramSchmidt.CorrectedRecurrence.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.MinimumNorm.Solvers.Executor.Core
import ComputationalMathematics.Source.Higham.Chapter21.Section03.MethodComparison.Core
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.ModifiedGramSchmidtQMethod.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.QR.ModifiedGramSchmidt.Rounded.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.Perturbation.Bounds.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.Perturbation.Radius.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.Projectors.ComplementNorm.ProjectorNorm
import ComputationalMathematics.Source.Higham.Chapter21.Equation08.ProjectorNorm
import ComputationalMathematics.Source.Higham.Chapter21.Equation09.ProjectorNorm
import ComputationalMathematics.Source.Higham.Chapter21.Equation01.QRFoundations
import ComputationalMathematics.Source.Higham.Chapter21.Equation03.QRFoundations
import ComputationalMathematics.Source.Higham.Chapter21.Equation04.QRFoundations
import ComputationalMathematics.Source.Higham.Chapter21.Theorem01.ComponentwisePerturbation.RankStability
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.ForwardError.ComputedOutput.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.ForwardError.Forward
import ComputationalMathematics.Source.Higham.Chapter21.Equation11.Forward
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.Forward
import ComputationalMathematics.Source.Higham.Chapter21.Equation11.ActualOutput
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.ActualOutput
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.EndToEnd.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.ConditionTransfer.Core
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.QRTransfer.EnvelopeTransfer
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.TriangularSolves.EnvelopeTransfer
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.EnvelopeTransfer

import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.QRTransfer.QRMajorant
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.QRTransfer.Signed
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.Signed
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.QRMajorant
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.ForwardError.RemainderBounds
import ComputationalMathematics.Source.Higham.Chapter21.Equation11.RemainderBounds
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SeminormalEquations.RemainderBounds

import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.SeminormalEquations.Uniform.Core
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04.SourceClosure.Supplement.Core
import ComputationalMathematics.Source.Higham.Chapter21
import ComputationalMathematics.Source.Higham.Chapter21.Theorem03
import ComputationalMathematics.Source.Higham.Chapter21.Theorem04

/-!
# Algorithms.Underdetermined.Higham21

Import-only historical compatibility facade for the W04 migration.
-/
