import Mathlib.Data.Real.Basic
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.MinimumNorm.Pseudoinverse.UnderdeterminedSpec
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.MinimumNorm.Solvers.UnderdeterminedSpec
import ComputationalMathematics.Algorithms.LinearSystems.Underdetermined.MinimumNorm.Specifications.UnderdeterminedSpec
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Source.Higham.Chapter21.Equation04.UnderdeterminedSpec
import ComputationalMathematics.Source.Higham.Chapter21.Equation05.UnderdeterminedSpec
import ComputationalMathematics.Source.Higham.Chapter21.Lemma02.Symmetrization.UnderdeterminedSpec
import ComputationalMathematics.Source.Higham.Chapter21.Theorem01.ComponentwisePerturbation.UnderdeterminedSpec

/-!
# Algorithms.Underdetermined.UnderdeterminedSpec

Import-only historical compatibility facade for the W04 migration.
-/
