import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.Elementwise.Core
import ComputationalMathematics.Analysis.FiniteProbability
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.Rounding
import ComputationalMathematics.Analysis.Summation.ErrorBounds
import ComputationalMathematics.FloatingPoint.Model
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm01.ElementwiseSampling.Sampling
import Mathlib.Data.Fin.Tuple.Basic
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Concentration.HitCounts.Bounds
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm01.ElementwiseSampling.HitCountConcentration
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm01.ElementwiseSampling.HitPairEvents
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.Elementwise
import ComputationalMathematics.Analysis.MatrixInequalities.LiebTrace.Concavity
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm01.ElementwiseSampling.TraceMGF

import Mathlib.Analysis.SpecialFunctions.Trigonometric.Series
import ComputationalMathematics.Algorithms.MatMul
import ComputationalMathematics.Algorithms.DotProduct
import Mathlib.Data.Real.Sqrt
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.RowNorm.Core
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm02.RowSampling.Endpoints
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation04.RowSamplingProbability.Normalization
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.RowNorm.Gram
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation05.GramApproximation.Bounds
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation05.GramApproximation.SampledGramEndpoints
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.LeverageScore.Core
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation06.LeverageProbability.Normalization
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.Leverage
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.SampledGramOperatorNorm
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.Core
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.GramMoments
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm03.RandomProjectionPreconditioning.UniformRows
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.HashCollisionProbabilities
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.SketchedGramLoewnerCovers
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.SketchedGramMoments
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.SketchInjectivityBounds
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.ExactTransforms.Core
import ComputationalMathematics.Algorithms.Summation.Tree.Core
import ComputationalMathematics.Analysis.MatrixConcentration
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm03.RandomProjectionPreconditioning.Preconditioning
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Concentration.SpectralTransfer.Elementwise


import ComputationalMathematics.Analysis.MatrixSpectral
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation02.SpectralApproximation.ElementwiseSpectral
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation02.SpectralApproximation.ResidualMomentBounds
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation02.SpectralApproximation.SpectralEventEndpoints

/-!
Historical owner retained as an import-only compatibility wrapper; its declarations were relocated under the R09/R10 completion waves per the reviewed route ledger.
-/
