import Mathlib.Data.Fin.Tuple.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.DotProduct
import Mathlib.Data.Real.Sqrt
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.RowNorm.Core
import ComputationalMathematics.Analysis.FiniteProbability
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.FloatingPoint.Model
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm02.RowSampling.Endpoints
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation04.RowSamplingProbability.Normalization
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.RowNorm.Gram
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation05.GramApproximation.Bounds
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation05.GramApproximation.SampledGramEndpoints
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.RowNorm
import ComputationalMathematics.Analysis.MatrixInequalities.LiebTrace.Concavity
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.RowNormTraceMGF

/-!
# NumStability.Algorithms.RandNLA.RowSamplingTraceMGF

Historical W11 import-only compatibility facade. Declarations moved unchanged to the canonical modules imported above.
-/
