import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Series
import Mathlib.Data.Fin.Tuple.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.MatMul
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import ComputationalMathematics.Algorithms.DotProduct
import Mathlib.Data.Real.Sqrt
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.RowNorm.Core
import ComputationalMathematics.Analysis.FiniteProbability
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.FloatingPoint.Model
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm02.RowSampling.Endpoints
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation04.RowSamplingProbability.Normalization
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.RowNorm.Gram
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation05.GramApproximation.Bounds
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation05.GramApproximation.SampledGramEndpoints
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.LeverageScore.Core
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation06.LeverageProbability.Normalization
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.Leverage
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.SampledGramOperatorNorm
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.Core
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.UniformRows.GramMoments
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm03.RandomProjectionPreconditioning.UniformRows
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.HashCollisionProbabilities
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.SketchedGramLoewnerCovers
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.SketchedGramMoments
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.CountSketch.SketchInjectivityBounds
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Preconditioning.ExactTransforms.Core
import ComputationalMathematics.Algorithms.Summation.Tree.Core
import ComputationalMathematics.Analysis.MatrixConcentration
import ComputationalMathematics.Analysis.Summation.ErrorBounds
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Algorithm03.RandomProjectionPreconditioning.Preconditioning
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.RowNorm
import ComputationalMathematics.Analysis.MatrixInequalities.LiebTrace.Concavity
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.RowNormTraceMGF
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Concentration.TraceMGF.LeverageScore
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.LeverageTraceMGF
import ComputationalMathematics.Algorithms.RandomizedLinearAlgebra.Sampling.LeverageScore.ComputedBasis
import ComputationalMathematics.Source.DrineasMahoney.RandNLA2016.Equation07.SubspaceEmbedding.ComputedBasis

/-!
# NumStability.Algorithms.RandNLA.RowSamplingLeverageComputedBasis

Historical W11 import-only compatibility facade. Declarations moved unchanged to the canonical modules imported above.
-/
