import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.LocalRiemannRoutine
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.LocalRiemannRoutineUpdate
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.Examples.BiasedLocalRiemannRoutine
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannLocalRoutineInterface

#check NumStability.LocalRiemannInformation.Routine
#print axioms NumStability.LocalRiemannInformation.Routine
#check NumStability.LocalRiemannInformation.Routine.flux
#print axioms NumStability.LocalRiemannInformation.Routine.flux
#check NumStability.LocalRiemannInformation.Routine.Consistent
#print axioms NumStability.LocalRiemannInformation.Routine.Consistent
#check NumStability.LocalRiemannInformation.Method.toRoutine
#print axioms NumStability.LocalRiemannInformation.Method.toRoutine
#check NumStability.LocalRiemannInformation.Method.toRoutine_flux
#print axioms NumStability.LocalRiemannInformation.Method.toRoutine_flux
#check NumStability.LocalRiemannInformation.Method.toRoutine_consistent
#print axioms NumStability.LocalRiemannInformation.Method.toRoutine_consistent
#check NumStability.LocalRiemannInformation.biasedRoutine
#print axioms NumStability.LocalRiemannInformation.biasedRoutine
#check NumStability.LocalRiemannInformation.biasedRoutine_selected
#print axioms NumStability.LocalRiemannInformation.biasedRoutine_selected
#check NumStability.LocalRiemannInformation.exists_biasedRoutine
#print axioms NumStability.LocalRiemannInformation.exists_biasedRoutine
#check NumStability.LocalRiemannInformation.Routine.reference_comparison
#print axioms NumStability.LocalRiemannInformation.Routine.reference_comparison
#check NumStability.LocalRiemannInformation.routine_local_interface_contract
#print axioms NumStability.LocalRiemannInformation.routine_local_interface_contract
#check NumStability.BiasedLocalRiemannRoutine.law
#print axioms NumStability.BiasedLocalRiemannRoutine.law
#check NumStability.BiasedLocalRiemannRoutine.proper_states
#print axioms NumStability.BiasedLocalRiemannRoutine.proper_states
#check NumStability.BiasedLocalRiemannRoutine.reference
#print axioms NumStability.BiasedLocalRiemannRoutine.reference
#check NumStability.BiasedLocalRiemannRoutine.reference_mean
#print axioms NumStability.BiasedLocalRiemannRoutine.reference_mean
#check NumStability.BiasedLocalRiemannRoutine.actual_error
#print axioms NumStability.BiasedLocalRiemannRoutine.actual_error
#check NumStability.BiasedLocalRiemannRoutine.equalProblem
#print axioms NumStability.BiasedLocalRiemannRoutine.equalProblem
#check NumStability.BiasedLocalRiemannRoutine.equal_state_selected
#print axioms NumStability.BiasedLocalRiemannRoutine.equal_state_selected
#check NumStability.BiasedLocalRiemannRoutine.equal_state_error
#print axioms NumStability.BiasedLocalRiemannRoutine.equal_state_error
#check NumStability.BiasedLocalRiemannRoutine.not_consistent
#print axioms NumStability.BiasedLocalRiemannRoutine.not_consistent
#check NumStability.BiasedLocalRiemannRoutine.zero_cell_update
#print axioms NumStability.BiasedLocalRiemannRoutine.zero_cell_update
#check NumStability.leveque01_localRiemannRoutineInterface_sourceContract
#print axioms NumStability.leveque01_localRiemannRoutineInterface_sourceContract
