import ComputationalMathematics.Algorithms.MatMul
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.Executor
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.TriangularBartelsStewart.EndToEnd
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.TriangularBartelsStewart.ResidualAssembly
import ComputationalMathematics.Source.Higham.Chapter16.Foundations.Core
import ComputationalMathematics.Analysis.Rounding
import ComputationalMathematics.Source.Higham.Chapter16.Section02.BartelsStewart.Equation09.Assembly
import ComputationalMathematics.Source.Higham.Chapter19.Core
import Mathlib.Data.Fin.Rev
import Mathlib.LinearAlgebra.Matrix.Block
import Mathlib.Logic.Equiv.Fin.Basic
import ComputationalMathematics.Algorithms.LinearSystems.Triangular.BackSubstitution
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.TriangularBartelsStewart.RoundedSolve
import ComputationalMathematics.Source.Higham.Chapter16.Spectrum.Results
import ComputationalMathematics.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.RoundedTriangular
import ComputationalMathematics.Source.Higham.Chapter16.Section02.BartelsStewart.Equation09.EndToEnd
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.QuasiQuasiSolve
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.SmallSystemRounding
import ComputationalMathematics.Source.Higham.Chapter16.QuasiRounded.Sylvester
import ComputationalMathematics.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.QuasiQuasiSylvester
import ComputationalMathematics.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.RoundedExecutor

/-!
# Algorithms.Sylvester.Higham16RoundedExecutor

Historical import-only compatibility facade for the W06 semantic modules.
-/
