import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.QuasiQuasiSolve
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.SmallSystemRounding
import ComputationalMathematics.Source.Higham.Chapter16.QuasiRounded.Sylvester
import ComputationalMathematics.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.QuasiQuasiSylvester

/-!
# Algorithms.Sylvester.Higham16QuasiQuasiSylvester

Historical import-only compatibility facade for the W06 semantic modules.
-/
