import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Conditioning.StructuredSylvester
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Equation.Diagonal
import ComputationalMathematics.Source.Higham.Chapter16.Foundations.Core
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Conditioning.FirstOrder
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Perturbation.Basic
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.BackwardError.Specification
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Equation.Basic
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Equation.Lyapunov
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.Equation10
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.Equation11
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.Equation12
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.Equation21
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.LyapunovDefinition
import ComputationalMathematics.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation22
import ComputationalMathematics.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation23
import ComputationalMathematics.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation24
import ComputationalMathematics.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation25
import ComputationalMathematics.Source.Higham.Chapter16.Section03.PerturbationAndConditioning.Equation27



/-!
# Algorithms.Sylvester.Higham16Psi

Historical compatibility facade for the W05 semantic modules.
-/
