import ComputationalMathematics.Algorithms.LU.GaussianElimination
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.PivotedSmallBlocks.CompletePivot
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.QuasiQuasiSolve
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.SmallSystemRounding
import ComputationalMathematics.Source.Higham.Chapter16.QuasiRounded.Sylvester
import ComputationalMathematics.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.QuasiQuasiSylvester
import ComputationalMathematics.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.PivotedSmallBlocks

/-!
# Algorithms.Sylvester.Higham16PivotedSmallBlocks

Historical import-only compatibility facade for the W06 semantic modules.
-/
