import ComputationalMathematics.Algorithms.CondEstimation
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Conditioning.PracticalErrorBounds
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Conditioning.PracticalEstimator.OneNorm
import ComputationalMathematics.Algorithms.NormEstimation.OneNorm.GeneralIndex
import ComputationalMathematics.Source.Higham.Chapter16.Section04.PracticalErrorBounds.NormEstimator.Equation29

/-!
# Algorithms.Sylvester.Higham16NormEstimator

Historical import-only compatibility facade for the W06 semantic modules.
-/
