import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.BackwardError.Specification
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Equation.Basic
import ComputationalMathematics.Algorithms.MatrixEquations.Sylvester.Equation.Lyapunov
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.Equation10
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.Equation11
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.Equation12
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.Equation21
import ComputationalMathematics.Source.Higham.Chapter16.Section02.SylvesterAndLyapunovBackwardError.LyapunovDefinition

/-!
# Algorithms.Sylvester.SylvesterSpec

Historical compatibility facade for the W05 semantic modules.
-/
