import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.CellAverageTraceEstimate
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannFieldFluxMethod
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannFieldFluxError
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.Examples.StationaryRiemannField

#check NumStability.RiemannFieldFluxMethod
#print axioms NumStability.RiemannFieldFluxMethod
#check NumStability.RiemannFieldFluxMethod.interfaceFlux
#print axioms NumStability.RiemannFieldFluxMethod.interfaceFlux
#check NumStability.RiemannFieldFluxMethod.ofExact
#print axioms NumStability.RiemannFieldFluxMethod.ofExact
#check NumStability.RiemannFieldFluxMethod.ofExact_interfaceFlux
#print axioms NumStability.RiemannFieldFluxMethod.ofExact_interfaceFlux
#check NumStability.RiemannFieldFluxMethod.ofExact_returnedField
#print axioms NumStability.RiemannFieldFluxMethod.ofExact_returnedField
#check NumStability.norm_sub_oneDimensionalCellAverage_le_of_trace
#print axioms NumStability.norm_sub_oneDimensionalCellAverage_le_of_trace
#check NumStability.RiemannFieldFluxMethod.interface_error_le
#print axioms NumStability.RiemannFieldFluxMethod.interface_error_le
#check NumStability.RiemannFieldFluxMethod.update_error_le
#print axioms NumStability.RiemannFieldFluxMethod.update_error_le
#check NumStability.StationaryRiemannField.transportLaw
#print axioms NumStability.StationaryRiemannField.transportLaw
#check NumStability.StationaryRiemannField.physicalFlux
#print axioms NumStability.StationaryRiemannField.physicalFlux
#check NumStability.StationaryRiemannField.stationary
#print axioms NumStability.StationaryRiemannField.stationary
#check NumStability.StationaryRiemannField.stationary_initial
#print axioms NumStability.StationaryRiemannField.stationary_initial
#check NumStability.StationaryRiemannField.stationary_trace_integrable
#print axioms NumStability.StationaryRiemannField.stationary_trace_integrable
#check NumStability.StationaryRiemannField.StationaryResult
#print axioms NumStability.StationaryRiemannField.StationaryResult
#check NumStability.StationaryRiemannField.method
#print axioms NumStability.StationaryRiemannField.method
#check NumStability.StationaryRiemannField.reference
#print axioms NumStability.StationaryRiemannField.reference
#check NumStability.StationaryRiemannField.reference_rectangle
#print axioms NumStability.StationaryRiemannField.reference_rectangle
#check NumStability.StationaryRiemannField.reference_initial
#print axioms NumStability.StationaryRiemannField.reference_initial
#check NumStability.StationaryRiemannField.stationary_not_rectangle
#print axioms NumStability.StationaryRiemannField.stationary_not_rectangle
#check NumStability.StationaryRiemannField.method_flux_eq_returned_trace
#print axioms NumStability.StationaryRiemannField.method_flux_eq_returned_trace
#check NumStability.StationaryRiemannField.stationary_trace_eq_reference
#print axioms NumStability.StationaryRiemannField.stationary_trace_eq_reference
#check NumStability.StationaryRiemannField.stationary_reference_error_le
#print axioms NumStability.StationaryRiemannField.stationary_reference_error_le
#check NumStability.StationaryRiemannField.nonexact_instance
#print axioms NumStability.StationaryRiemannField.nonexact_instance
