import ComputationalMathematics.Source.LeVeque.Chapter01

#check NumStability.leveque01_acousticsLeftMode
#print axioms NumStability.leveque01_acousticsLeftMode
#check NumStability.leveque01_acousticsMatrixEigenvalues
#print axioms NumStability.leveque01_acousticsMatrixEigenvalues
#check NumStability.leveque01_acousticsRightMode
#print axioms NumStability.leveque01_acousticsRightMode
#check NumStability.leveque01_acousticsTwoWaveDecomposition
#print axioms NumStability.leveque01_acousticsTwoWaveDecomposition
#check NumStability.leveque01_acoustics_hasConservationForm
#print axioms NumStability.leveque01_acoustics_hasConservationForm
#check NumStability.leveque01_advectionFlux_isSpeedTimesState
#print axioms NumStability.leveque01_advectionFlux_isSpeedTimesState
#check NumStability.leveque01_advectionLinearFlux
#print axioms NumStability.leveque01_advectionLinearFlux
#check NumStability.leveque01_advectionLinearFlux_fromMassConservation
#print axioms NumStability.leveque01_advectionLinearFlux_fromMassConservation
#check NumStability.leveque01_advectionWaveIdentity
#print axioms NumStability.leveque01_advectionWaveIdentity
#check NumStability.leveque01_dimensionalSplitting
#print axioms NumStability.leveque01_dimensionalSplitting
#check NumStability.leveque01_dimensionalSplitting_nonvacuity
#print axioms NumStability.leveque01_dimensionalSplitting_nonvacuity
#check NumStability.leveque01_dimensionalSplitting_sourceContract
#print axioms NumStability.leveque01_dimensionalSplitting_sourceContract
#check NumStability.leveque01_eigenvaluesAreWaveSpeeds
#print axioms NumStability.leveque01_eigenvaluesAreWaveSpeeds
#check NumStability.leveque01_equation01_constantLinearSystem
#print axioms NumStability.leveque01_equation01_constantLinearSystem
#check NumStability.leveque01_equation01_constantLinearSystemAt_iff
#print axioms NumStability.leveque01_equation01_constantLinearSystemAt_iff
#check NumStability.leveque01_equation01_isLinearFluxConservationLaw
#print axioms NumStability.leveque01_equation01_isLinearFluxConservationLaw
#check NumStability.leveque01_equation02_isOneDimensionalSpecialization
#print axioms NumStability.leveque01_equation02_isOneDimensionalSpecialization
#check NumStability.leveque01_equation03_advectedProfile
#print axioms NumStability.leveque01_equation03_advectedProfile
#check NumStability.leveque01_equation03_profilePropagates
#print axioms NumStability.leveque01_equation03_profilePropagates
#check NumStability.leveque01_equation03_scalarAdvection
#print axioms NumStability.leveque01_equation03_scalarAdvection
#check NumStability.leveque01_equation04_positiveSpeedOneWayWave
#print axioms NumStability.leveque01_equation04_positiveSpeedOneWayWave
#check NumStability.leveque01_equation04_profileMovesRight
#print axioms NumStability.leveque01_equation04_profileMovesRight
#check NumStability.leveque01_equation04_scalarHyperbolicOneWayModel
#print axioms NumStability.leveque01_equation04_scalarHyperbolicOneWayModel
#check NumStability.leveque01_equation05_linearAcoustics
#print axioms NumStability.leveque01_equation05_linearAcoustics
#check NumStability.leveque01_equation06_acousticsMatrixForm
#print axioms NumStability.leveque01_equation06_acousticsMatrixForm
#check NumStability.leveque01_equation07_pressureWave
#print axioms NumStability.leveque01_equation07_pressureWave
#check NumStability.leveque01_equation08_conservationLawAt_iff
#print axioms NumStability.leveque01_equation08_conservationLawAt_iff
#check NumStability.leveque01_equation09_quasilinearForm
#print axioms NumStability.leveque01_equation09_quasilinearForm
#check NumStability.leveque01_equation10_fluxBalance
#print axioms NumStability.leveque01_equation10_fluxBalance
#check NumStability.leveque01_equation11_characterization
#print axioms NumStability.leveque01_equation11_characterization
#check NumStability.leveque01_equation11_riemannData
#print axioms NumStability.leveque01_equation11_riemannData
#check NumStability.leveque01_finiteVolumeCellAverage_spec
#print axioms NumStability.leveque01_finiteVolumeCellAverage_spec
#check NumStability.leveque01_finiteVolumeFluxUpdate_characterization
#print axioms NumStability.leveque01_finiteVolumeFluxUpdate_characterization
#check NumStability.leveque01_finiteVolumeFluxUpdate_finiteConservation
#print axioms NumStability.leveque01_finiteVolumeFluxUpdate_finiteConservation
#check NumStability.leveque01_finiteVolumeFluxUpdate_preservesTotal
#print axioms NumStability.leveque01_finiteVolumeFluxUpdate_preservesTotal
#check NumStability.leveque01_finiteVolumeFluxUpdate_sourceContract
#print axioms NumStability.leveque01_finiteVolumeFluxUpdate_sourceContract
#check NumStability.leveque01_finiteVolumeFluxUpdate_spec
#print axioms NumStability.leveque01_finiteVolumeFluxUpdate_spec
#check NumStability.leveque01_heterogeneousMaterialCellAverage
#print axioms NumStability.leveque01_heterogeneousMaterialCellAverage
#check NumStability.leveque01_heterogeneousMaterialCellAverage_nonvacuity
#print axioms NumStability.leveque01_heterogeneousMaterialCellAverage_nonvacuity
#check NumStability.leveque01_heterogeneousMaterialCellAverage_sourceContract
#print axioms NumStability.leveque01_heterogeneousMaterialCellAverage_sourceContract
#check NumStability.leveque01_hyperbolicMatrixDefinition
#print axioms NumStability.leveque01_hyperbolicMatrixDefinition
#check NumStability.leveque01_hyperbolicMatrix_uniqueEigenbasisDecomposition
#print axioms NumStability.leveque01_hyperbolicMatrix_uniqueEigenbasisDecomposition
#check NumStability.leveque01_integralLaw_impliesDifferentialLaw_of_smooth
#print axioms NumStability.leveque01_integralLaw_impliesDifferentialLaw_of_smooth
#check NumStability.leveque01_linearFlux_specializesEquation01
#print axioms NumStability.leveque01_linearFlux_specializesEquation01
#check NumStability.leveque01_riemannInterfaceFlux
#print axioms NumStability.leveque01_riemannInterfaceFlux
#check NumStability.leveque01_riemannInterfaceFlux_sourceContract
#print axioms NumStability.leveque01_riemannInterfaceFlux_sourceContract
#check NumStability.leveque01_scalarEquation_isHyperbolic
#print axioms NumStability.leveque01_scalarEquation_isHyperbolic
