import ComputationalMathematics.Source.LeVeque.Chapter01
import NumStability.Source.LeVeque.Chapter01

#check NumStability.leveque01_acoustics_hasConservationForm
#print axioms NumStability.leveque01_acoustics_hasConservationForm
#check NumStability.leveque01_acousticsMatrixEigenvalues
#print axioms NumStability.leveque01_acousticsMatrixEigenvalues
#check NumStability.leveque01_acousticsLeftMode
#print axioms NumStability.leveque01_acousticsLeftMode
#check NumStability.leveque01_acousticsRightMode
#print axioms NumStability.leveque01_acousticsRightMode
#check NumStability.leveque01_acousticsTwoWaveDecomposition
#print axioms NumStability.leveque01_acousticsTwoWaveDecomposition
#check NumStability.leveque01_advectionLinearFlux_fromMassConservation
#print axioms NumStability.leveque01_advectionLinearFlux_fromMassConservation
#check NumStability.leveque01_advectionWaveIdentity
#print axioms NumStability.leveque01_advectionWaveIdentity
#check NumStability.leveque01_dimensionalSplitting_sourceContract
#print axioms NumStability.leveque01_dimensionalSplitting_sourceContract
#check NumStability.leveque01_discontinuity_integralBalance_witness
#print axioms NumStability.leveque01_discontinuity_integralBalance_witness
#check NumStability.leveque01_hyperbolicMatrix_uniqueEigenbasisDecomposition
#print axioms NumStability.leveque01_hyperbolicMatrix_uniqueEigenbasisDecomposition
#check NumStability.leveque01_eigenvaluesAreWaveSpeeds
#print axioms NumStability.leveque01_eigenvaluesAreWaveSpeeds
#check NumStability.leveque01_equation01_constantLinearSystemAt_iff
#print axioms NumStability.leveque01_equation01_constantLinearSystemAt_iff
#check NumStability.leveque01_equation10_integralConservation_iff
#print axioms NumStability.leveque01_equation10_integralConservation_iff
#check NumStability.leveque01_equation11_characterization
#print axioms NumStability.leveque01_equation11_characterization
#check NumStability.leveque01_equation02_uniformTransportModel
#print axioms NumStability.leveque01_equation02_uniformTransportModel
#check NumStability.leveque01_equation03_transportSolution
#print axioms NumStability.leveque01_equation03_transportSolution
#check NumStability.leveque01_equation04_acousticOneWayModel
#print axioms NumStability.leveque01_equation04_acousticOneWayModel
#check NumStability.leveque01_equation05_linearAcousticsAt_iff
#print axioms NumStability.leveque01_equation05_linearAcousticsAt_iff
#check NumStability.leveque01_equation06_acousticsMatrixForm
#print axioms NumStability.leveque01_equation06_acousticsMatrixForm
#check NumStability.leveque01_equation07_pressureWave
#print axioms NumStability.leveque01_equation07_pressureWave
#check NumStability.leveque01_equation08_conservationLawAt_iff
#print axioms NumStability.leveque01_equation08_conservationLawAt_iff
#check NumStability.leveque01_equation09_quasilinearForm
#print axioms NumStability.leveque01_equation09_quasilinearForm
#check NumStability.leveque01_finiteVolumeCellAverage_spec
#print axioms NumStability.leveque01_finiteVolumeCellAverage_spec
#check NumStability.leveque01_finiteVolumeFluxUpdate_sourceContract
#print axioms NumStability.leveque01_finiteVolumeFluxUpdate_sourceContract
#check NumStability.leveque01_fluxJacobian_hyperbolicity_iff
#print axioms NumStability.leveque01_fluxJacobian_hyperbolicity_iff
#check NumStability.leveque01_heterogeneousMaterialCellAverage_sourceContract
#print axioms NumStability.leveque01_heterogeneousMaterialCellAverage_sourceContract
#check NumStability.leveque01_hyperbolicMatrixDefinition
#print axioms NumStability.leveque01_hyperbolicMatrixDefinition
#check NumStability.leveque01_hyperbolicSystem_scalarWaveDecomposition
#print axioms NumStability.leveque01_hyperbolicSystem_scalarWaveDecomposition
#check NumStability.leveque01_integralLaw_impliesDifferentialLaw_of_smooth
#print axioms NumStability.leveque01_integralLaw_impliesDifferentialLaw_of_smooth
#check NumStability.leveque01_linearFlux_specializesEquation01
#print axioms NumStability.leveque01_linearFlux_specializesEquation01
#check NumStability.leveque01_linearRiemann_eigensolution
#print axioms NumStability.leveque01_linearRiemann_eigensolution
#check NumStability.leveque01_materialInterfaceRiemannData_iff
#print axioms NumStability.leveque01_materialInterfaceRiemannData_iff
#check NumStability.leveque01_nonconservation_requires_sourceTerm
#print axioms NumStability.leveque01_nonconservation_requires_sourceTerm
#check NumStability.leveque01_nonlinear_shock_formation
#print axioms NumStability.leveque01_nonlinear_shock_formation
#check NumStability.leveque01_oneStepMethod_iff_currentStateMap
#print axioms NumStability.leveque01_oneStepMethod_iff_currentStateMap
#check NumStability.leveque01_riemannInitialConfiguration_iff
#print axioms NumStability.leveque01_riemannInitialConfiguration_iff
#check NumStability.leveque01_rectangleRiemannInterfaceFlux_sourceContract
#print axioms NumStability.leveque01_rectangleRiemannInterfaceFlux_sourceContract
#check NumStability.leveque01_riemannRayZeroValue_iff
#print axioms NumStability.leveque01_riemannRayZeroValue_iff
#check NumStability.leveque01_scalarEquation_isHyperbolic
#print axioms NumStability.leveque01_scalarEquation_isHyperbolic
#check NumStability.leveque01_equation07_secondOrderHyperbolic
#print axioms NumStability.leveque01_equation07_secondOrderHyperbolic
#check NumStability.leveque01_exists_hyperbolic_variableCoefficient_without_localFlux
#print axioms NumStability.leveque01_exists_hyperbolic_variableCoefficient_without_localFlux
