from pathlib import Path
import hashlib,json,re,subprocess
S=Path(__file__).resolve().parent;R=S.parents[3];D=S/'left-mode-domain-draft';sha=lambda b:hashlib.sha256(b).hexdigest()
query=['rg','-n','linearAcousticsLeftInvariant_isLinearAdvectionSolutionAt|travelingWave_isLinearAdvectionSolution_iff|travelingWave_isRectangleConservationLawSolution_iff|travelingWave_at_translated_point','ComputationalMathematics/Analysis/PartialDifferentialEquations','.lake/packages/mathlib/Mathlib','-g','*.lean']
run=subprocess.run(query,cwd=R,stdout=subprocess.PIPE,stderr=subprocess.PIPE);assert run.returncode==0
paths=['ComputationalMathematics/Analysis/PartialDifferentialEquations/LinearAcoustics.lean','ComputationalMathematics/Analysis/PartialDifferentialEquations/Transport/Characteristics.lean','ComputationalMathematics/Analysis/PartialDifferentialEquations/ConservationLaws/TravelingWaveCharacterization.lean','ComputationalMathematics/Analysis/PartialDifferentialEquations/LinearAdvection.lean','.lake/packages/mathlib/Mathlib/Data/Real/Sqrt.lean']
proof=(S/'left-mode-domain-draft-check-output.txt').read_bytes();e=json.loads((S/'left-mode-domain-draft-check-exit.json').read_text());assert e['exit_code']==0 and e['output_sha256']==sha(proof)
assert b'sorryAx' not in proof and b'error:' not in proof
name='NumStability.LeftModeDomainsDraft.leftMode_solutionDomains'
ax=re.search(re.escape("'"+name+"' depends on axioms:")+r'\s*\[([^\]]*)\]',proof.decode());assert ax
assert {x.strip() for x in ax.group(1).split(',')}<={'propext','Classical.choice','Quot.sound'}
r={'schema':1,'head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),'source':{'path':'gates/leveque-finite-volume/artifacts/session-20260908/source/LeVeque_Finite_Volume_Methods_for_Hyperbolic_Problems_2002.pdf','sha256':'b3adec0d3616dbde57a5522cfce1861890887d7c03a2232d2136cb94c9bac1d5'},'candidate_sha256':sha((D/'candidate.lean').read_bytes()),'declarations':[name],'native':e,'native_exit_sha256':sha((S/'left-mode-domain-draft-check-exit.json').read_bytes()),'current_tree_search':{'argv':query,'exit_code':run.returncode,'stdout':run.stdout.decode(),'stderr':run.stderr.decode()},'selected_inputs':[{'path':p,'sha256':sha((R/p).read_bytes())} for p in paths],'selection':'Compose the existing actual acoustic left-mode equation and exact generic translated-profile domains. No duplicate generic producer is introduced. The acoustic mode and the independent translated profile remain separate fields.','rejected_candidate':'The old left source wrapper gives only a locally differentiable profile branch; its frozen independent audit remains undetermined on exhaustive nonsmooth coverage. Its source comment identifying q2 with w2 is not copied.','absence_claim':'This is a bounded current-tree query, not a global semantic absence proof.','interpretation_status':'A separate user question for the left-moving mode is pending; the conventions previously adopted for other rows are not treated as authorization for this source row. This generic draft is not a source-faithfulness acceptance.'}
assert sha((R/r['source']['path']).read_bytes())==r['source']['sha256']
p=D/'final-receipt.json';assert not p.exists();p.write_text(json.dumps(r,indent=2)+'\n')
print(json.dumps({'receipt_sha256':sha(p.read_bytes()),'candidate_sha256':r['candidate_sha256'],'native_exit':0}))
