from pathlib import Path
import hashlib,json,re
S=Path(__file__).resolve().parent;R=S.parents[3];sha=lambda b:hashlib.sha256(b).hexdigest()
D=S/'characteristic-converse-draft';p=D/'EigenbasisPropagationFinal.lean'
assert sha(p.read_bytes())=='6364aa0ed693f0de98ea2471c3859bdf76a8971067f86fc99a22b5160f468dc1'
e=json.loads((S/'eigenbasis-propagation-draft-final-exit.json').read_text());assert e['exit_code']==0
out=(S/'eigenbasis-propagation-draft-final-output.txt').read_text()
assert 'warning:' not in out and 'error:' not in out and 'sorryAx' not in out
decls=['NumStability.'+n for n in ['linearAdvection_hasDerivAt_characteristic','linearAdvection_eq_travelingWave_of_differentiable','constantCoefficientSystem_characteristicPropagation','leveque01_eigenvalues_completeWavePropagation']]
for d in decls:
 assert '#check '+d in p.read_text() and '#print axioms '+d in p.read_text()
 m=re.search(re.escape("'"+d+"' depends on axioms:")+r'\s*\[([^\]]*)\]',out);assert m
 assert {x.strip() for x in m.group(1).split(',')}<={'propext','Classical.choice','Quot.sound'}
dependencies=['ComputationalMathematics/Analysis/PartialDifferentialEquations/LinearSystems/EigenbasisCoordinates.lean','ComputationalMathematics/Analysis/PartialDifferentialEquations/Transport/UniformAdvection.lean','.lake/packages/mathlib/Mathlib/Analysis/Calculus/MeanValue.lean','.lake/packages/mathlib/Mathlib/Analysis/Calculus/Deriv/Comp.lean','.lake/packages/mathlib/Mathlib/Analysis/Calculus/Deriv/Prod.lean','lean-toolchain','lake-manifest.json']
receipt={'schema':1,'draft':p.relative_to(R).as_posix(),'draft_sha256':sha(p.read_bytes()),'declarations':decls,'check_exit_code':0,'check_output_sha256':sha((S/'eigenbasis-propagation-draft-final-output.txt').read_bytes()),'check_exit_sha256':sha((S/'eigenbasis-propagation-draft-final-exit.json').read_bytes()),'dependencies':[{'path':x,'sha256':sha((R/x).read_bytes())} for x in dependencies],'search_evidence_sha256':sha((D/'current-tree-search.json').read_bytes()),'scope':'Joint differentiability is explicit; complete fixed eigenbasis, nonzero vectors, scalar PDE equivalence, propagation of independently supplied solution components and reconstruction. Source audit pending; original rejected audit is preserved.'}
final=D/'final-receipt.json';assert not final.exists();final.write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
source=R/'ledgers/leveque-finite-volume/book-issues/leveque-finite-volume/chapters/chapter-01/issues.md'
process=R/'ledgers/leveque-finite-volume/skill-issues/book-formalization/leveque-finite-volume/sessions/codex-start-1-v5-0-1-20260908/issues.md'
entries=[
(source,'LEV-C1-USER-DISCONTINUITY-INTERPRETATION-018','| LEV-C1-USER-DISCONTINUITY-INTERPRETATION-018 | LEV-CH01-DISCONTINUITY-INTEGRAL-LAW | explicit user interpretation of the discussion around (1.10) | The printed exceptional-time convention and classical state-regularity requirement remain implicit and preserved | User adopted rectangle conservation, mass-rate identity almost everywhere for each fixed interval, and classical solutionhood requiring spatial state differentiability | interpretation adopted; general capstone draft checked; independent fresh audit pending | user receipt b27e7d260e93edcd5408daa8c5d291ba8bfefd9e66a079480ae6b940aa869030; worker final receipt 06db27f7742b7f9e6c72ee039c4b66034ad8151407bafcf7d44a5a116530bd6c; root rehash verification 2bf69f335b7b2fa8331c128335d8157c857dada11a89b8aeb77539dfb29b7e6a | Place the general finite-vector arbitrary-flux comparison and substantive jump witnesses, then audit under the separately recorded convention. Preserve prior UND. The weaker conservative residual may still hold for a discontinuous stationary field with constant flux; do not silently equate it to classical solutionhood. |'),
(source,'LEV-C1-EIGENVALUE-COMPONENT-COVERAGE-019','| LEV-C1-EIGENVALUE-COMPONENT-COVERAGE-019 | LEV-CH01-EIGENVALUES-WAVE-SPEEDS | structural mismatch in existing source target | The source describes component propagation in a complete eigenbasis of a hyperbolic matrix | The old target constructs one prescribed traveling mode under one eigenrelation, also allowing defective matrices and zero vectors | not-faithful-different after adjudication; accepted false; both implications no | decision 76b47f8b86892598730cf10051a9726470201d8a1993933e3a5cdf333c79d5dd; report 6130fc357ac5862afe9427dfc06151b20d01874dc07475226b604c1ebb563784 | Preserve the valid supporting lemma and rejected audit. A checked successor draft uses an actual complete eigenbasis with nonzero vectors, existing bidirectional PDE decoupling, an explicit-joint-differentiability characteristic converse, propagation of independently supplied fields and full reconstruction. Place and independently audit it; remaining source regularity is not silently settled. |'),
(process,'BF-LEV-RUN-20260908-018','| BF-LEV-RUN-20260908-018 | 2026-09-08 | second scoped user interpretation | After a checked arbitrary-flux comparison exposed the source temporal ambiguity and the conservative-residual regularity caveat, the user explicitly adopted the proposed discontinuity convention. | user-discontinuity-interpretation-20260908.json SHA b27e7d260e93edcd5408daa8c5d291ba8bfefd9e66a079480ae6b940aa869030 | This is a separate scoped instruction from the earlier transport convention; neither rewrites printed source facts or prior audit decisions. | recorded; fresh capstone work active | Bind the exact reply and interpretation in a new audit environment and judging inputs; retain fresh blind/source separation, old decisions and fixed-interval-before-a.e. quantifier order. |')]
for path,ident,entry in entries:
 before=path.read_bytes();assert ident.encode() not in before
 (S/('ledger-before-'+ident+'-'+sha(before)+'.bin')).write_bytes(before)
 path.write_bytes(before.rstrip(b'\r\n')+b'\n'+entry.encode()+b'\n')
G=R/'gates/leveque-finite-volume/chapter-01.json';before=G.read_bytes();g=json.loads(before)
(S/('gate-before-general-drafts-'+sha(before)+'.json')).write_bytes(before)
updates={
'LEV-CH01-DISCONTINUITY-INTEGRAL-LAW':'The user explicitly adopted the recorded rectangle/a.e.-mass-rate and spatial-state-differentiability convention. The general finite-vector arbitrary-flux comparison and vector jump witnesses passed native checks with only allowed axioms. Place canonical owners and a source capstone, then run a fresh interpretation-bound audit preserving the old UND result and the conservative-residual caveat.',
'LEV-CH01-EIGENVALUES-WAVE-SPEEDS':'The old single-mode target is independently rejected as not-faithful-different, both implications no. A complete-eigenbasis successor draft now passes native checks: bidirectional scalar PDE decoupling, nonzero eigenvectors, propagation of independently supplied joint-differentiable solutions and reconstruction. Place reusable characteristic and system producers and the source wrapper, then perform a fresh audit with source regularity explicit.'}
for row in g['rows']:
 if row['id'] in updates:assert row['status']=='READY';row['next_foundation']=updates[row['id']]
G.write_text(json.dumps(g,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
print(json.dumps({'propagation_final_receipt_sha256':sha(final.read_bytes()),'gate_sha256':sha(G.read_bytes()),'new_draft_declarations':4,'production_change':False}))

