import ComputationalMathematics.Analysis.PartialDifferentialEquations.Transport.ClassicalCharacteristics
import ComputationalMathematics.Analysis.PartialDifferentialEquations.LinearSystems.CharacteristicPropagation
import ComputationalMathematics.Source.LeVeque.Chapter01.EigenvaluePropagation
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Discontinuity
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.MovingRiemannJump
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.StationaryJump
import ComputationalMathematics.Source.LeVeque.Chapter01.DiscontinuityGeneralComparison

#check NumStability.linearAdvection_hasDerivAt_characteristic
#print axioms NumStability.linearAdvection_hasDerivAt_characteristic
#check NumStability.linearAdvection_eq_travelingWave_of_differentiable
#print axioms NumStability.linearAdvection_eq_travelingWave_of_differentiable
#check NumStability.constantCoefficientSystem_characteristicPropagation
#print axioms NumStability.constantCoefficientSystem_characteristicPropagation
#check NumStability.leveque01_eigenvalues_completeWavePropagation
#print axioms NumStability.leveque01_eigenvalues_completeWavePropagation
#check NumStability.IsRectangleConservationLawSolution.discontinuity_comparison
#print axioms NumStability.IsRectangleConservationLawSolution.discontinuity_comparison
#check NumStability.not_conservationLawSolutionAt_of_flux_not_continuousAt
#print axioms NumStability.not_conservationLawSolutionAt_of_flux_not_continuousAt
#check NumStability.vectorStep_not_continuousAt_jump
#print axioms NumStability.vectorStep_not_continuousAt_jump
#check NumStability.vectorStep_rectangle_and_discontinuity
#print axioms NumStability.vectorStep_rectangle_and_discontinuity
#check NumStability.exists_discontinuous_rectangle_field
#print axioms NumStability.exists_discontinuous_rectangle_field
#check NumStability.stationaryField_constantFlux_residual
#print axioms NumStability.stationaryField_constantFlux_residual
#check NumStability.discontinuous_stationary_conservative_residual
#print axioms NumStability.discontinuous_stationary_conservative_residual
#check NumStability.leveque01_discontinuity_generalIntegralComparison
#print axioms NumStability.leveque01_discontinuity_generalIntegralComparison
