import ComputationalMathematics.Source.LeVeque.Chapter01.Hyperbolicity
import ComputationalMathematics.Source.LeVeque.Chapter01.ScalarHyperbolicity

#check NumStability.IsRealHyperbolicMatrix
#check NumStability.isRealHyperbolicMatrix_iff_independent_real_eigenvectors
#check NumStability.IsRealHyperbolicMatrix.exists_unique_eigenbasis_decomposition
#check NumStability.leveque01_hyperbolicMatrixDefinition
#check NumStability.leveque01_scalarEquation_isHyperbolic
#check NumStability.leveque01_hyperbolicMatrix_uniqueEigenbasisDecomposition
#check basisOfPiSpaceOfLinearIndependent
#check coe_basisOfPiSpaceOfLinearIndependent
#check Module.Basis.equivFun_symm_apply
#check LinearIndependent.of_subsingleton

#print axioms NumStability.isRealHyperbolicMatrix_iff_independent_real_eigenvectors
#print axioms NumStability.IsRealHyperbolicMatrix.exists_unique_eigenbasis_decomposition
#print axioms NumStability.leveque01_hyperbolicMatrixDefinition
#print axioms NumStability.leveque01_scalarEquation_isHyperbolic
#print axioms NumStability.leveque01_hyperbolicMatrix_uniqueEigenbasisDecomposition
