import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RectangleRiemannInterface
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.LinearRectangleRiemannInterface
import ComputationalMathematics.Source.LeVeque.Chapter01.RectangleRiemannInterfaceFlux
import ComputationalMathematics.Analysis.PartialDifferentialEquations.Transport.Characteristics
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.TravelingWaveCharacterization
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation03TransportSolution

#check NumStability.IsRectangleHyperbolicRiemannSolution
#print axioms NumStability.IsRectangleHyperbolicRiemannSolution
#check NumStability.CertifiedRectangleRiemannSolution
#print axioms NumStability.CertifiedRectangleRiemannSolution
#check NumStability.RectangleRiemannInterfaceFluxMethod
#print axioms NumStability.RectangleRiemannInterfaceFluxMethod
#check NumStability.adjacentCellRectangleRiemannInformation
#print axioms NumStability.adjacentCellRectangleRiemannInformation
#check NumStability.rectangleRiemannInterfaceFlux
#print axioms NumStability.rectangleRiemannInterfaceFlux
#check NumStability.rectangleRiemannInterface_finiteVolumeStep
#print axioms NumStability.rectangleRiemannInterface_finiteVolumeStep
#check NumStability.linearHyperbolicConservationLaw
#print axioms NumStability.linearHyperbolicConservationLaw
#check NumStability.linearRiemannSolution_constant
#print axioms NumStability.linearRiemannSolution_constant
#check NumStability.certifiedLinearRectangleRiemannSolution
#print axioms NumStability.certifiedLinearRectangleRiemannSolution
#check NumStability.linearRectangleRiemannInterfaceFluxMethod
#print axioms NumStability.linearRectangleRiemannInterfaceFluxMethod
#check NumStability.linearRectangleRiemannInterfaceFluxMethod_exists_total
#print axioms NumStability.linearRectangleRiemannInterfaceFluxMethod_exists_total
#check NumStability.linearRectangleRiemannInterfaceFluxMethod_nonempty
#print axioms NumStability.linearRectangleRiemannInterfaceFluxMethod_nonempty
#check NumStability.linearRectangleRiemannInterfaceFluxMethod_information
#print axioms NumStability.linearRectangleRiemannInterfaceFluxMethod_information
#check NumStability.leveque01_rectangleRiemannInterfaceFlux_sourceContract
#print axioms NumStability.leveque01_rectangleRiemannInterfaceFlux_sourceContract
#check NumStability.travelingWave_characteristic_translate
#print axioms NumStability.travelingWave_characteristic_translate
#check NumStability.travelingWave_hasDerivAt_characteristic
#print axioms NumStability.travelingWave_hasDerivAt_characteristic
#check NumStability.travelingWave_isLinearAdvectionSolution_iff
#print axioms NumStability.travelingWave_isLinearAdvectionSolution_iff
#check NumStability.travelingWave_isRectangleConservationLawSolution_iff
#print axioms NumStability.travelingWave_isRectangleConservationLawSolution_iff
#check NumStability.leveque01_equation03_transportSolution
#print axioms NumStability.leveque01_equation03_transportSolution
