import ComputationalMathematics.Source.LeVeque.Chapter01.Equation02SolutionDomains
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation03SolutionDomains
import ComputationalMathematics.MeasureTheory.Integral.IntervalIntegral.LebesgueDifferentiation
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.TemporalDerivative

#check NumStability.leveque01_equation02_uniformTransportDomains
#print axioms NumStability.leveque01_equation02_uniformTransportDomains
#check NumStability.leveque01_equation03_solutionDomains
#print axioms NumStability.leveque01_equation03_solutionDomains
#check NumStability.ae_hasDerivAt_intervalIntegral_pi
#print axioms NumStability.ae_hasDerivAt_intervalIntegral_pi
#check NumStability.IsRectangleConservationLawSolution.hasDerivAt_mass_ae
#print axioms NumStability.IsRectangleConservationLawSolution.hasDerivAt_mass_ae
