# Issues — chapter 1

Record book, source, or source-to-Lean issues encountered in this scope. Use stable IDs; never delete history—mark superseded or closed entries.

| ID | Source row | Category | Printed issue | Lean artifact | Relation/status | Evidence | Owner/next action |
|---|---|---|---|---|---|---|---|
| LEV-C1-DOMAIN-001 | LEV-CH01-RIEMANN-INTERFACE-FLUX; LEV-CH01-LINEAR-RIEMANN-EIGENSOLUTION | effective solution domain | Printed page 5 admits discontinuous Riemann fields; the displayed rate law on page 4 needs a careful interpretation at endpoint crossings | IsHyperbolicRiemannSolution uses IsIntegralConservationLawSolution, which requires HasDerivAt of every interval mass at every time | OPEN: suspected source-to-Lean mismatch, not yet a certified counterexample or source error | session-20260908/transport-rectangle-reuse-review.md; checked transport-rectangle-candidate.lean and final output | Root and Riemann foundation worker: construct explicit eigenmode solution with time-integrated rectangle balance; independently audit applicability before closing either row |
| LEV-C1-INVENTORY-002 | general scalar decoupling; material-interface Riemann data; general Riemann problem definition | source coverage | Printed pages 3, 8, and 5 contain substantive assertions beyond the neighboring algebraic decomposition, wave-dynamics description, and piecewise data formula | Three new READY inventory rows; checked eigenbasis-decoupling and Riemann candidates are prerequisites only | inventory corrected; formalization and audits remain | independent-inventory-review-final.md and exact hash-bound mutation script | Root: place the reusable producers and source wrappers, then independently audit each selected contract |
| LEV-C1-SHOCK-003 | LEV-CH01-NONLINEAR-SHOCK-FORMATION; LEV-CH01-DISCONTINUITY-INTEGRAL-LAW | source scope and prerequisite | An unnamed existential witness is not a valid reason to skip discontinuity formation from smooth data; lack of a weak framework does not remove the integral-law assertion | Reopened READY rows; checked Burgers classical-breakdown prerequisite and rectangle Riemann construction are not complete source coverage | actionable; no source discrepancy certified | independent-inventory-review-final.md; session shock-foundation and riemann-foundation artifacts | Extend to actual discontinuous continuation and adjudicate the integral-law time/trace interpretation |
| LEV-C1-DOMAIN-001-VERIFIED-WITNESS | LEV-CH01-DISCONTINUITY-INTEGRAL-LAW; LEV-CH01-LINEAR-RIEMANN-EIGENSOLUTION; LEV-CH01-RIEMANN-INTERFACE-FLUX | effective solution domain follow-up | A moving unit step obeys rectangle balance while its unit-cell mass has a corner at endpoint crossing, independently of the selected value at the jump; time translation puts the crossing at a positive time | ShockFoundation.timeShiftedStep_rectangle and timeShiftedStep_no_classical_mass_derivative in the frozen scratch candidate | counterexample checked; source interpretation/adjudication remains OPEN | shock-foundation/final-verification.json SHA-256 633a729cb8df2c3dd4abde2dc5fa8e8e237cff65558989dd0815530dec87e584; native exit 0 and allowed axioms | Root: place one reusable weak-balance producer and distinct source witness/correction, then obtain the required independent interpretation and adjudication; do not silently redefine the printed derivative |
| LEV-C1-SHOCK-004 | LEV-CH01-NONLINEAR-SHOCK-FORMATION | complete candidate and effective domain | Section 1.1.2 permits spontaneous jumps from smooth data but does not supply a named witness in this chapter | New reusable Huber-flux continuation and leveque01_nonlinear_shock_formation provide a C1 nonaffine flux, C-infinity initial data, spatial continuity before T=1, distinct one-sided traces at T and full oriented rectangle balance | native checked candidate; independent source audit remains OPEN | shock-continuation/final-verification.json and shock-production; production source wrapper's LF SHA-256 ff38f13c8d6dfa9b66558340d588eb92b9d0d02d677b09a1825000d3e3e7a753 | Audit the existential source claim explicitly: witness data -x are unbounded, flux is C1 rather than C2, and no general entropy uniqueness theorem is asserted. |
| LEV-C1-DOMAIN-001-PRODUCTION-WITNESS | LEV-CH01-DISCONTINUITY-INTEGRAL-LAW; LEV-CH01-RIEMANN-INTERFACE-FLUX | precise positive-time classical failure | The moving jump has no classical PDE derivative at x=0,t=1 and no classical mass derivative for the unit cell at t=1, for every chosen point value at the jump; its rectangle balance remains valid | leveque01_movingStep_classicalDerivative_witness, leveque01_movingStep_rectangleBalance and their combined witness in the new DiscontinuityWitnesses source module | both failures and corrected rectangle balance checked; no source discrepancy accepted yet | production-postrename-build-exit.json and production-postrename-declarations-output.txt; new immutable discontinuity audit task | Independent source/trace adjudication must decide the printed (1.10) reading. Complete a separate explicit-domain rectangle-certified interface adapter instead of silently changing the existing public classical certificate. |
