"""Freeze source-only boundaries without claiming local exhaustion or a terminal state."""
from pathlib import Path
import hashlib,json
S=Path(__file__).resolve().parent;R=S.parents[3]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':p.relative_to(R).as_posix(),'sha256':sha(p)}
PDF=S/'source/LeVeque_Finite_Volume_Methods_for_Hyperbolic_Problems_2002.pdf'
assert sha(PDF)=='b3adec0d3616dbde57a5522cfce1861890887d7c03a2232d2136cb94c9bac1d5'
items=[
('LEV-CH01-ACOUSTICS-LEFT-MODE','LEV-CH01-ACOUSTICS-LEFT-MODE-CANONICAL-20260908','Printed page 2 uses the left-going profile after the classical acoustic calculation without stating its function class, and changes its printed symbol from w2 to q2. The proposed domain split distinguishes arbitrary geometric translation, differentiable classical solutions and locally integrable rectangle solutions. The two earlier adopted interpretations concern specified other rows; application to this left-mode assertion remains an explicit pending choice. The printed symbol switch and physical positive material convention remain disclosed.'),
('LEV-CH01-EIGENVALUES-WAVE-SPEEDS','LEV-CH01-EIGENVALUES-GENERAL-PROPAGATION-PRODUCTION-20260908','Printed pages 1–3 identify eigenvalues with component-wave speeds without a regularity convention for the full solution class. The complete-eigenbasis classical propagation and reconstruction result explicitly requires global joint differentiability. The latest general audit isolates that source-domain uncertainty; it does not identify a spectral or sign defect. The proposed classical interpretation remains pending.'),
('LEV-CH01-FINITE-VOLUME-FLUX-UPDATE','LEV-CH01-FINITE-VOLUME-FLUX-UPDATE-CANONICAL-20260908','Printed page 5 describes approximate cell averages and numerical fluxes approximating physical edge fluxes reasonably well, but supplies no numerical tolerance, norm, order or step error formula. The proposed interpretation uses independent numerical old data, time-averaged physical fluxes and explicit old/face-error bounds implying a next-step bound. That quantitative convention is not uniquely selected by the source and its pending question remains material.'),
('LEV-CH01-RIEMANN-INTERFACE-FLUX','LEV-CH01-RIEMANN-RECTANGLE-INTERFACE-PRODUCTION-20260908','Printed page 5 assigns the ordered neighboring cell averages to Riemann states, obtains information from the solution and computes fluxes and updates; the nearby continuation permits approximate solvers. The source does not prescribe a full returned field or an all-real trace domain. The information-only alternative removes that avoidable representation restriction. The independent-reference finite-step comparison still requires the separately pending interpretation of the qualitative accuracy relationship; no universal accuracy guarantee follows merely from solve/extract functions.'),
('LEV-CH01-DIMENSIONAL-SPLITTING','LEV-CH01-DIMENSIONAL-SPLITTING-CANONICAL-20260908','Printed page 6 describes rectangular or logically rectangular grids and successive one-dimensional coordinate-direction problems. It does not define logical rectangularity through an explicit chart, topology, metric or Jacobian condition. The proposed interpretation uses coordinate connectivity, supplied physical cell volumes, shared normal face fluxes and successive conservative line updates, with actual measured Cartesian specialization. Whether this captures the intended logical geometry remains the pending source choice; totality/exactness of numerical solvers is separate repairable implementation scope.'),
('LEV-CH01-HETEROGENEOUS-CELL-AVERAGING','LEV-CH01-HETEROGENEOUS-CELL-AVERAGING-CANONICAL-20260908','Printed page 8 permits assigning material properties by appropriate averaging over each cell volume, without defining an averaging operator or requiring different output values. Normalized volume integration with cellwise integrability is a concrete proposed meaning; model-specific alternatives such as harmonic averaging are not ruled out by the passage. The pending choice concerns selection of this operator, not an unsupported requirement that heterogeneous inputs have unequal cell averages.'),
('LEV-CH01-NONCONSERVATION-SOURCE-TERMS','LEV-CH01-NONCONSERVATION-SOURCE-TERMS-PRODUCTION-20260908','Printed page 4 states that failure of contaminant mass conservation, for example through reactions, requires source terms. It does not delimit a full mathematical production class or select ordinary integrable densities over possible singular production measures. The proposed signed-density rectangle balance retains finite mass/flux/production integrability and the adopted fixed-interval almost-everywhere mass-rate interpretation. Its density-versus-more-general-production boundary remains a separate pending choice.'),
('LEV-CH01-MATERIAL-INTERFACE-RIEMANN-DATA','LEV-CH01-MATERIAL-INTERFACE-RIEMANN-DATA-PRODUCTION-20260908','Printed page 8 explicitly requires a medium discontinuity and an initial-data discontinuity at the same interface, but does not display a globally piecewise-constant material profile. The proposed local-medium interpretation requires distinct one-sided medium traces and distinct state traces, retaining global strict-half-line initial states; the stronger alternative makes the medium constant on both entire half-lines too. Both alternatives are explicit, and their source selection remains pending.'),
('LEV-CH01-RIEMANN-INITIAL-VALUE-DEFINITION','LEV-CH01-RIEMANN-INITIAL-VALUE-DEFINITION-PRODUCTION-20260908','Printed page 5 specifies a hyperbolic equation together with two-state piecewise-constant initial data. Its prose calls this a jump, while equation (1.11) has no inequality and leaves the interface value unstated. The proposed positive-dimensional first-order hyperbolic system/data classification includes equal-state degeneracies and does not assert existence of solutions. The exact governing-equation/domain and equal-state interpretation remains the pending choice.')]
rows=[]
for row_id,task,boundary in items:
 P=S/'audits'/task/'faithfulness'
 decision=json.loads((P/'decision.json').read_bytes());assert decision['accepted'] is False
 locator=json.loads((P/'inputs/source_locator.json').read_bytes());assert locator['source_sha256']==sha(PDF)
 rows.append({'row_id':row_id,'source_locator':ref(P/'inputs/source_locator.json'),'frozen_audits':[ref(P/'decision.json'),ref(P/'manifest.json')],'boundary':boundary})
dest=S/'prospective-source-choice-boundaries-batch10.json'
data={'schema_version':1,'kind':'material-choice-source-boundaries','source':ref(PDF),'rows':rows}
with dest.open('x',encoding='utf-8',newline='') as f:f.write(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
print(json.dumps({'source_boundary_manifest':ref(dest),'rows':len(rows),'source_acceptance':False,'local_exhaustion_asserted':False}))

