from pathlib import Path
import hashlib,json
S=Path(__file__).resolve().parent;D=S/'characteristic-converse-draft'
p=D/'CharacteristicConverse.lean';before=p.read_bytes()
assert hashlib.sha256(before).hexdigest()=='788c262ddfc54e575f3c7346ad3eb4f4abe061bbcda0c479899bedc8211c863b'
assert json.loads((S/'characteristic-converse-draft-corrected-exit.json').read_text())['exit_code']==0
text=before.decode();text=text[:text.index('\nend NumStability')]
text='import ComputationalMathematics.Analysis.PartialDifferentialEquations.LinearSystems.EigenbasisCoordinates\n'+text
text+='\n'+"\ntheorem constantCoefficientSystem_characteristicPropagation {m : ℕ}\n    (A : Matrix (Fin m) (Fin m) ℝ) (b : Module.Basis (Fin m) ℝ (Fin m → ℝ))\n    (speeds : Fin m → ℝ) (heigen : ∀ i, A.mulVec (b i) = speeds i • b i)\n    (q : ℝ → ℝ → (Fin m → ℝ))\n    (hq : Differentiable ℝ (Function.uncurry q))\n    (hpde : ∀ x t, IsConstantCoefficientLinearSystemSolutionAt q A x t) :\n    (∀ i x t, b.equivFun (q x t) i =\n      b.equivFun (q (x - speeds i * t) 0) i) ∧\n    ∀ x t, q x t =\n      ∑ i, (b.equivFun (q (x - speeds i * t) 0) i) • b i := by\n  have hcoordinates (i : Fin m) (x t : ℝ) :\n      b.equivFun (q x t) i = b.equivFun (q (x - speeds i * t) 0) i := by\n    let L : (Fin m → ℝ) →L[ℝ] ℝ :=\n      (ContinuousLinearMap.proj (R := ℝ) i).comp\n        b.equivFun.toContinuousLinearEquiv.toContinuousLinearMap\n    have hcoord : Differentiable ℝ\n        (Function.uncurry (fun ξ τ => b.equivFun (q ξ τ) i)) := by\n      exact L.differentiable.comp hq\n    have heq := linearAdvection_eq_travelingWave_of_differentiable hcoord\n      (fun ξ τ => (constantCoefficientSystem_iff_eigenbasisAdvection\n        A b speeds heigen q ξ τ).mp (hpde ξ τ) i)\n    exact congrFun (congrFun heq x) t\n  refine ⟨hcoordinates, ?_⟩\n  intro x t\n  rw [← b.sum_equivFun (q x t)]\n  apply Finset.sum_congr rfl\n  intro i _\n  rw [hcoordinates i x t]\n\ntheorem leveque01_eigenvalues_completeWavePropagation {m : ℕ}\n    (A : Matrix (Fin m) (Fin m) ℝ) (hA : IsRealHyperbolicMatrix A) :\n    ∃ (speeds : Fin m → ℝ) (b : Module.Basis (Fin m) ℝ (Fin m → ℝ)),\n      (∀ i, b i ≠ 0 ∧ A.mulVec (b i) = speeds i • b i) ∧\n      (∀ (q : ℝ → ℝ → (Fin m → ℝ)) (x t : ℝ),\n        IsConstantCoefficientLinearSystemSolutionAt q A x t ↔\n          ∀ i, IsLinearAdvectionSolutionAt\n            (fun ξ τ => b.equivFun (q ξ τ) i) (speeds i) x t) ∧\n      ∀ (q : ℝ → ℝ → (Fin m → ℝ)),\n        Differentiable ℝ (Function.uncurry q) →\n        (∀ x t, IsConstantCoefficientLinearSystemSolutionAt q A x t) →\n        (∀ i x t, b.equivFun (q x t) i =\n          b.equivFun (q (x - speeds i * t) 0) i) ∧\n        ∀ x t, q x t =\n          ∑ i, (b.equivFun (q (x - speeds i * t) 0) i) • b i := by\n  obtain ⟨speeds, b, heigen⟩ := hA\n  refine ⟨speeds, b, fun i => ⟨b.ne_zero i, heigen i⟩,\n    constantCoefficientSystem_iff_eigenbasisAdvection A b speeds heigen, ?_⟩\n  exact constantCoefficientSystem_characteristicPropagation A b speeds heigen\n\n"+'\nend NumStability\n'
for decl in ['linearAdvection_hasDerivAt_characteristic','linearAdvection_eq_travelingWave_of_differentiable','constantCoefficientSystem_characteristicPropagation','leveque01_eigenvalues_completeWavePropagation']:
 text+='\n#check NumStability.'+decl+'\n#print axioms NumStability.'+decl+'\n'
out=D/'EigenbasisPropagation.lean';assert not out.exists();out.write_text(text,encoding='utf-8',newline='\n')
print(hashlib.sha256(out.read_bytes()).hexdigest())

