from pathlib import Path
import hashlib,json
S=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert sha(S/'root-eigen-fv-qualification-verification.json')=='134c763a80150fb97111d1dc770564ee1ceb6406af777625f5871eb847f5ba4f'
assert sha(S/'root-information-method-production-verification.json')=='c3c9d7120d9e2976c3f7743b58546701b379331f67d07dbad801384b415289e4'
records=[]
def add(task,row,next_foundation,entry):
 p=S/'audits'/task/'faithfulness/decision.json';d=json.loads(p.read_bytes());assert d['accepted'] is False
 records.append({'task':task,'row':row,'decision_sha256':sha(p),'next_foundation':next_foundation,'ledger_entry':entry})
add('LEV-CH01-EIGENVALUES-GENERAL-PROPAGATION-PRODUCTION-20260908','LEV-CH01-EIGENVALUES-WAVE-SPEEDS',
'The complete classical target now has a root-verified proof-free source/definition qualification packet with native checks of complete paired eigendata, pointwise system/advection equivalence and global joint-differentiability propagation/reconstruction. Existing nonsmooth eigenmode-sum construction is separately checked; universal weak uniqueness is not an added prerequisite. Preserve unanswered call_6YQjDMqpCa41f93c3kdBhahI; source-specific acceptance awaits this recorded classical-domain choice and a fresh independent audit.',
'| LEV-C1-EIGEN-PROPAGATION-QUALIFICATION-065 | LEV-CH01-EIGENVALUES-WAVE-SPEEDS | complete classical target qualification | The source does not state whether less regular component waves are included | Current definition and producer types are explicitly checked; no spectral or reconstruction gap identified | READY; source choice pending | root qualification 134c763a80150fb97111d1dc770564ee1ceb6406af777625f5871eb847f5ba4f; 18 native reports across the shared EIGEN/FV packet | Available weak mode-sum construction is retained separately; weak uniqueness is not imposed as extra work for the proposed classical interpretation. |')
add('LEV-CH01-FINITE-VOLUME-FLUX-UPDATE-CANONICAL-20260908','LEV-CH01-FINITE-VOLUME-FLUX-UPDATE',
'The compiled independent-array/physical-reference capstone now has explicit native Real.measureSpace, Stieltjes-Lebesgue, complete Fin m codomain, Bochner integrability/totalization and actual spatial/time-volume-average qualifications. All prior capstone inputs still match. Preserve unanswered call_1UY4fVuKrjpIIQfhLdeuFoRH; only the specified source accuracy/time-flux interpretation remains before selecting the capstone and a fresh qualified audit. No tolerance, order, CFL or unconditional accuracy theorem is inferred.',
'| LEV-C1-FV-MEASURE-QUALIFICATION-066 | LEV-CH01-FINITE-VOLUME-FLUX-UPDATE | ordinary physical-average semantics checked | Qualitative reasonable flux accuracy does not select a norm, bound or order | Complete finite vectors, actual interval integrability and existing normalized-volume bridges qualify the independent-reference error contract | READY; Q7 pending | prospective-eigen-fv-qualification-review native exit 0, output e2ad806c00634c2e7d442e1b6dfbb86b648fd258761cfda2beb2fb38c4877361 | Equality of totalized averages alone is insufficient; the explicit integrability and completeness qualifications are retained. |')
add('LEV-CH01-RIEMANN-RECTANGLE-INTERFACE-PRODUCTION-20260908','LEV-CH01-RIEMANN-INTERFACE-FLUX',
'The broader information-only execution, field adapter, finite-step error bounds and ordered-state example are now placed in four canonical leaves, with explicit nominal maps and 52 preservation checks. Root verified 24 canonical declarations and 105 final reports. This removes compulsory returned fields/all-real trace integrability, so call_gBZtG6Mn328LLCQ5DfzmFZtV is no longer a required choice for this alternative. Complete the prospective canonical information-interface capstone and its literal application; preserve separate unanswered accuracy call_1UY4fVuKrjpIIQfhLdeuFoRH and the printed source ambiguity.',
'| LEV-C1-INFORMATION-METHOD-PLACEMENT-067 | LEV-CH01-RIEMANN-INTERFACE-FLUX | broader reusable solver information interface | The source does not require a complete returned field or traces on every real interval | Actual admitted ordered solve and same-result extraction are separate from optional finite-step physical comparisons; four leaves are placed | READY; prospective capstone integration active | production final receipt 5f602458855faa07f2b770cd42e832e72f704ace3862025b53b15e87810b3645; root verification c3c9d7120d9e2976c3f7743b58546701b379331f67d07dbad801384b415289e4 | Pending Q11 remains recorded but is avoidable for the broader alternative; Q7 still concerns qualitative accuracy. |')
process=[
'| LEV-SKILL-INFORMATION-NOMINAL-COMPARISON-048 | codex-start-1-v5-0-1-20260908 | canonical placement checks | Two initial extractor-field comparisons omitted the implicit dependent problem index | Preserve failed comparison-01 input/output/actual exit and make both entire dependent functions explicit | resolved | comparison-02 and final native checks exit 0; 52 maps, round trips, commuting and complete-type comparisons verified | The nominal structures remain distinct; no false definitional equality or production change was used. |',
'| LEV-SKILL-ROOT-UTF8-QUALIFICATION-049 | codex-start-1-v5-0-1-20260908 | native root evidence reader | One unqualified read_text used Windows cp1252 and raised UnicodeDecodeError on Lean text | Preserve the verifier source and failed observed exit; rerun the same read-only verifier under explicit Python -X utf8 -B | resolved | Same verifier exited 0 and checked 77 bindings and 18 actual axiom reports; root result 134c763a80150fb97111d1dc770564ee1ceb6406af777625f5871eb847f5ba4f | Future native text readers should specify UTF-8 explicitly. No Lean input or frozen evidence was changed. |'
]
p=S/'root-batch10-qualified-progress-spec.json'
with p.open('x',encoding='utf-8',newline='') as f:f.write(json.dumps({'label':'root-batch10-qualified-progress','audits':records,'process_entries':process},indent=2)+'\n')
print(json.dumps({'sha256':sha(p),'book_entries':len(records),'process_entries':len(process)}))

