import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaw.BalanceLaw
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaw.Examples.MovingStep
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaw.Hyperbolicity
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaw.Rectangle
import ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaw.VariableCoefficient
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.LinearRiemannSolution
import ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannData.Regularity
import ComputationalMathematics.Analysis.PartialDifferentialEquations.Hyperbolicity.EigenbasisCoordinates
import ComputationalMathematics.Analysis.PartialDifferentialEquations.InitialValue.Riemann
import ComputationalMathematics.Analysis.PartialDifferentialEquations.InitialValue.SelfSimilarity
import ComputationalMathematics.Analysis.PartialDifferentialEquations.SecondOrder.Classification
import ComputationalMathematics.Source.LeVeque.Chapter01.DiscontinuityWitnesses
import ComputationalMathematics.Source.LeVeque.Chapter01.EigenbasisDecoupling
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation05Definition
import ComputationalMathematics.Source.LeVeque.Chapter01.Equation10Definition
import ComputationalMathematics.Source.LeVeque.Chapter01.FluxJacobianHyperbolicity
import ComputationalMathematics.Source.LeVeque.Chapter01.LinearRiemannEigensolution
import ComputationalMathematics.Source.LeVeque.Chapter01.MaterialInterfaceRiemannData
import ComputationalMathematics.Source.LeVeque.Chapter01.NonconservationSourceTerms
import ComputationalMathematics.Source.LeVeque.Chapter01.OneStepMethod
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannInitialConfiguration
import ComputationalMathematics.Source.LeVeque.Chapter01.RiemannRayZero
import ComputationalMathematics.Source.LeVeque.Chapter01.SecondOrderHyperbolicity
import ComputationalMathematics.Source.LeVeque.Chapter01.VariableCoefficientConservationForm

#check NumStability.IsBalanceLawSolutionAt
#print axioms NumStability.IsBalanceLawSolutionAt
#check NumStability.balanceLaw_source_eq_zero_of_conservationLaw
#print axioms NumStability.balanceLaw_source_eq_zero_of_conservationLaw
#check NumStability.integral_internalProduction_eq_massDefect
#print axioms NumStability.integral_internalProduction_eq_massDefect
#check NumStability.nonconservation_requires_nonzero_source
#print axioms NumStability.nonconservation_requires_nonzero_source
#check NumStability.integral_any_source_eq_massDefect
#print axioms NumStability.integral_any_source_eq_massDefect
#check NumStability.uniform_unit_production_nonvacuity
#print axioms NumStability.uniform_unit_production_nonvacuity
#check NumStability.MovingStep.movingStep
#print axioms NumStability.MovingStep.movingStep
#check NumStability.MovingStep.movingStep_rectangle
#print axioms NumStability.MovingStep.movingStep_rectangle
#check NumStability.MovingStep.stepMass
#print axioms NumStability.MovingStep.stepMass
#check NumStability.MovingStep.stepMass_nonpositive
#print axioms NumStability.MovingStep.stepMass_nonpositive
#check NumStability.MovingStep.stepMass_unitInterval
#print axioms NumStability.MovingStep.stepMass_unitInterval
#check NumStability.MovingStep.stepMass_not_differentiableAt_zero
#print axioms NumStability.MovingStep.stepMass_not_differentiableAt_zero
#check NumStability.MovingStep.movingStep_rectangle_without_classical_mass_derivative
#print axioms NumStability.MovingStep.movingStep_rectangle_without_classical_mass_derivative
#check NumStability.MovingStep.timeShiftedStep
#print axioms NumStability.MovingStep.timeShiftedStep
#check NumStability.MovingStep.timeShiftedStep_rectangle
#print axioms NumStability.MovingStep.timeShiftedStep_rectangle
#check NumStability.MovingStep.timeShiftedStep_no_classical_mass_derivative
#print axioms NumStability.MovingStep.timeShiftedStep_no_classical_mass_derivative
#check NumStability.MovingStep.timeShiftedStep_no_classical_advection_at_crossing
#print axioms NumStability.MovingStep.timeShiftedStep_no_classical_advection_at_crossing
#check NumStability.IsHyperbolicFluxAt
#print axioms NumStability.IsHyperbolicFluxAt
#check NumStability.isHyperbolicFluxAt_iff_independent_real_eigenvectors
#print axioms NumStability.isHyperbolicFluxAt_iff_independent_real_eigenvectors
#check NumStability.IsHyperbolicFluxOn
#print axioms NumStability.IsHyperbolicFluxOn
#check NumStability.isHyperbolicFluxOn_iff_independent_real_eigenvectors
#print axioms NumStability.isHyperbolicFluxOn_iff_independent_real_eigenvectors
#check NumStability.hyperbolicConservationLaw_isHyperbolicFluxAt
#print axioms NumStability.hyperbolicConservationLaw_isHyperbolicFluxAt
#check NumStability.IsRectangleConservationLawSolution
#print axioms NumStability.IsRectangleConservationLawSolution
#check NumStability.travelingWave_intervalBalance
#print axioms NumStability.travelingWave_intervalBalance
#check NumStability.travelingWave_intervalIntegrable_space
#print axioms NumStability.travelingWave_intervalIntegrable_space
#check NumStability.travelingWave_intervalIntegrable_time
#print axioms NumStability.travelingWave_intervalIntegrable_time
#check NumStability.travelingWave_isRectangleConservationLawSolution
#print axioms NumStability.travelingWave_isRectangleConservationLawSolution
#check NumStability.RepresentsScalarTransportFlux
#print axioms NumStability.RepresentsScalarTransportFlux
#check NumStability.RepresentsScalarTransportFlux.position_independent
#print axioms NumStability.RepresentsScalarTransportFlux.position_independent
#check NumStability.RepresentsScalarTransportFlux.state_derivative
#print axioms NumStability.RepresentsScalarTransportFlux.state_derivative
#check NumStability.RepresentsScalarTransportFlux.coefficient_eq
#print axioms NumStability.RepresentsScalarTransportFlux.coefficient_eq
#check NumStability.riemannData_intervalIntegrable
#print axioms NumStability.riemannData_intervalIntegrable
#check NumStability.eigenmodeTravelingWave_isRectangleSolution
#print axioms NumStability.eigenmodeTravelingWave_isRectangleSolution
#check NumStability.finite_sum_isRectangleSolution
#print axioms NumStability.finite_sum_isRectangleSolution
#check NumStability.linearRiemannSolution
#print axioms NumStability.linearRiemannSolution
#check NumStability.linearRiemannSolution_isRectangleSolution
#print axioms NumStability.linearRiemannSolution_isRectangleSolution
#check NumStability.linearRiemannSolution_initial
#print axioms NumStability.linearRiemannSolution_initial
#check NumStability.riemannData_mul_pos
#print axioms NumStability.riemannData_mul_pos
#check NumStability.linearRiemannSolution_selfSimilar
#print axioms NumStability.linearRiemannSolution_selfSimilar
#check NumStability.selectedLinearRiemannRayZeroValue
#print axioms NumStability.selectedLinearRiemannRayZeroValue
#check NumStability.linearRiemannSolution_rayZero
#print axioms NumStability.linearRiemannSolution_rayZero
#check NumStability.IsRealHyperbolicMatrix.exists_rectangle_riemann_solution
#print axioms NumStability.IsRealHyperbolicMatrix.exists_rectangle_riemann_solution
#check NumStability.IsRiemannData.tendsto_left
#print axioms NumStability.IsRiemannData.tendsto_left
#check NumStability.IsRiemannData.tendsto_right
#print axioms NumStability.IsRiemannData.tendsto_right
#check NumStability.IsRiemannData.not_continuousAt_zero
#print axioms NumStability.IsRiemannData.not_continuousAt_zero
#check NumStability.eigenbasis_coordinates_mulVec
#print axioms NumStability.eigenbasis_coordinates_mulVec
#check NumStability.constantCoefficientSystem_iff_eigenbasisAdvection
#print axioms NumStability.constantCoefficientSystem_iff_eigenbasisAdvection
#check NumStability.IsRiemannInitialValueSolution
#print axioms NumStability.IsRiemannInitialValueSolution
#check NumStability.isRiemannInitialValueSolution_iff
#print axioms NumStability.isRiemannInitialValueSolution_iff
#check NumStability.isRiemannInitialValueSolution_iff_exists_origin
#print axioms NumStability.isRiemannInitialValueSolution_iff_exists_origin
#check NumStability.isRiemannData_prod_iff
#print axioms NumStability.isRiemannData_prod_iff
#check NumStability.riemannData_prod
#print axioms NumStability.riemannData_prod
#check NumStability.IsPositiveTimeSelfSimilar
#print axioms NumStability.IsPositiveTimeSelfSimilar
#check NumStability.similarityRayValue
#print axioms NumStability.similarityRayValue
#check NumStability.IsPositiveTimeSelfSimilar.on_ray
#print axioms NumStability.IsPositiveTimeSelfSimilar.on_ray
#check NumStability.IsPositiveTimeSelfSimilar.rayValue_iff
#print axioms NumStability.IsPositiveTimeSelfSimilar.rayValue_iff
#check NumStability.IsPositiveTimeSelfSimilar.rayZero
#print axioms NumStability.IsPositiveTimeSelfSimilar.rayZero
#check NumStability.ratioProfile_isPositiveTimeSelfSimilar
#print axioms NumStability.ratioProfile_isPositiveTimeSelfSimilar
#check NumStability.SecondOrderPrincipalPart
#print axioms NumStability.SecondOrderPrincipalPart
#check NumStability.SecondOrderPrincipalPart.IsHyperbolic
#print axioms NumStability.SecondOrderPrincipalPart.IsHyperbolic
#check NumStability.wavePrincipalPart
#print axioms NumStability.wavePrincipalPart
#check NumStability.wavePrincipalPart_isHyperbolic
#print axioms NumStability.wavePrincipalPart_isHyperbolic
#check NumStability.leveque01_movingStep_classicalDerivative_witness
#print axioms NumStability.leveque01_movingStep_classicalDerivative_witness
#check NumStability.leveque01_movingStep_rectangleBalance
#print axioms NumStability.leveque01_movingStep_rectangleBalance
#check NumStability.leveque01_hyperbolicSystem_scalarWaveDecomposition
#print axioms NumStability.leveque01_hyperbolicSystem_scalarWaveDecomposition
#check NumStability.leveque01_equation05_linearAcousticsAt_iff
#print axioms NumStability.leveque01_equation05_linearAcousticsAt_iff
#check NumStability.leveque01_equation10_integralConservation_iff
#print axioms NumStability.leveque01_equation10_integralConservation_iff
#check NumStability.leveque01_fluxJacobian_hyperbolicity_iff
#print axioms NumStability.leveque01_fluxJacobian_hyperbolicity_iff
#check NumStability.leveque01_linearRiemann_eigensolution
#print axioms NumStability.leveque01_linearRiemann_eigensolution
#check NumStability.leveque01_materialInterfaceRiemannData_iff
#print axioms NumStability.leveque01_materialInterfaceRiemannData_iff
#check NumStability.leveque01_materialInterfaceRiemannData_pair
#print axioms NumStability.leveque01_materialInterfaceRiemannData_pair
#check NumStability.leveque01_nonconservation_requires_sourceTerm
#print axioms NumStability.leveque01_nonconservation_requires_sourceTerm
#check NumStability.leveque01_sourceTerm_unitProduction
#print axioms NumStability.leveque01_sourceTerm_unitProduction
#check NumStability.leveque01IsOneStepMethodAt
#print axioms NumStability.leveque01IsOneStepMethodAt
#check NumStability.leveque01_oneStepMethod_iff_currentStateMap
#print axioms NumStability.leveque01_oneStepMethod_iff_currentStateMap
#check NumStability.leveque01RiemannInitialConfiguration
#print axioms NumStability.leveque01RiemannInitialConfiguration
#check NumStability.leveque01_riemannInitialConfiguration_iff
#print axioms NumStability.leveque01_riemannInitialConfiguration_iff
#check NumStability.leveque01RiemannRayZeroValue
#print axioms NumStability.leveque01RiemannRayZeroValue
#check NumStability.leveque01_riemannRayZeroValue_iff
#print axioms NumStability.leveque01_riemannRayZeroValue_iff
#check NumStability.leveque01_equation07_secondOrderHyperbolic
#print axioms NumStability.leveque01_equation07_secondOrderHyperbolic
#check NumStability.leveque01_exists_hyperbolic_variableCoefficient_without_localFlux
#print axioms NumStability.leveque01_exists_hyperbolic_variableCoefficient_without_localFlux
