$ErrorActionPreference = 'Stop'
$directory = 'gates/leveque-finite-volume/artifacts/session-20260908'
& lake build ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.BalanceLaw ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Examples.MovingStep ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Hyperbolicity ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.Rectangle ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.VariableCoefficient ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.LinearRiemannSolution ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RiemannDataRegularity ComputationalMathematics.Analysis.PartialDifferentialEquations.InitialValue.Riemann ComputationalMathematics.Analysis.PartialDifferentialEquations.InitialValue.SelfSimilarity ComputationalMathematics.Analysis.PartialDifferentialEquations.LinearSystems.EigenbasisCoordinates ComputationalMathematics.Analysis.PartialDifferentialEquations.SecondOrder.Classification ComputationalMathematics.Source.LeVeque.Chapter01.DiscontinuityWitnesses ComputationalMathematics.Source.LeVeque.Chapter01.EigenbasisDecoupling ComputationalMathematics.Source.LeVeque.Chapter01.Equation05Definition ComputationalMathematics.Source.LeVeque.Chapter01.Equation10Definition ComputationalMathematics.Source.LeVeque.Chapter01.FluxJacobianHyperbolicity ComputationalMathematics.Source.LeVeque.Chapter01.LinearRiemannEigensolution ComputationalMathematics.Source.LeVeque.Chapter01.MaterialInterfaceRiemannData ComputationalMathematics.Source.LeVeque.Chapter01.NonconservationSourceTerms ComputationalMathematics.Source.LeVeque.Chapter01.OneStepMethod ComputationalMathematics.Source.LeVeque.Chapter01.RiemannInitialConfiguration ComputationalMathematics.Source.LeVeque.Chapter01.RiemannRayZero ComputationalMathematics.Source.LeVeque.Chapter01.SecondOrderHyperbolicity ComputationalMathematics.Source.LeVeque.Chapter01.VariableCoefficientConservationForm 2>&1 | Tee-Object -FilePath "$directory/production-postrename-build-output.txt"
$buildExit = $LASTEXITCODE
[ordered]@{command='lake build (24 modules enumerated in production-postrename-inputs.json)';exit_code=$buildExit} | ConvertTo-Json | Set-Content -LiteralPath "$directory/production-postrename-build-exit.json" -Encoding utf8
if ($buildExit -ne 0) { exit $buildExit }
& lake env lean "$directory/production-postrename-declarations.lean" 2>&1 | Tee-Object -FilePath "$directory/production-postrename-declarations-output.txt"
$checkExit = $LASTEXITCODE
[ordered]@{command='lake env lean gates/leveque-finite-volume/artifacts/session-20260908/production-postrename-declarations.lean';exit_code=$checkExit} | ConvertTo-Json | Set-Content -LiteralPath "$directory/production-postrename-declarations-exit.json" -Encoding utf8
exit $checkExit
