$ErrorActionPreference = 'Stop'
& lake build ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RectangleRiemannInterface ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.LinearRectangleRiemannInterface ComputationalMathematics.Source.LeVeque.Chapter01.RectangleRiemannInterfaceFlux ComputationalMathematics.Analysis.PartialDifferentialEquations.Transport.Characteristics ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.TravelingWaveCharacterization ComputationalMathematics.Source.LeVeque.Chapter01.Equation03TransportSolution 2>&1 | Tee-Object -FilePath 'gates/leveque-finite-volume/artifacts/session-20260908/interface-transport-production-build-output.txt'
$checkExit = $LASTEXITCODE
[ordered]@{command='lake build ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.RectangleRiemannInterface ComputationalMathematics.Analysis.PartialDifferentialEquations.FiniteVolume.LinearRectangleRiemannInterface ComputationalMathematics.Source.LeVeque.Chapter01.RectangleRiemannInterfaceFlux ComputationalMathematics.Analysis.PartialDifferentialEquations.Transport.Characteristics ComputationalMathematics.Analysis.PartialDifferentialEquations.ConservationLaws.TravelingWaveCharacterization ComputationalMathematics.Source.LeVeque.Chapter01.Equation03TransportSolution';exit_code=$checkExit} | ConvertTo-Json | Set-Content -LiteralPath 'gates/leveque-finite-volume/artifacts/session-20260908/interface-transport-production-build-exit.json' -Encoding utf8
if ($checkExit -ne 0) { exit $checkExit }
& lake env lean gates/leveque-finite-volume/artifacts/session-20260908/interface-transport-production-checks.lean 2>&1 | Tee-Object -FilePath 'gates/leveque-finite-volume/artifacts/session-20260908/interface-transport-production-checks-output.txt'
$checkExit = $LASTEXITCODE
[ordered]@{command='lake env lean gates/leveque-finite-volume/artifacts/session-20260908/interface-transport-production-checks.lean';exit_code=$checkExit} | ConvertTo-Json | Set-Content -LiteralPath 'gates/leveque-finite-volume/artifacts/session-20260908/interface-transport-production-checks-exit.json' -Encoding utf8
exit $checkExit
