"""Read pinned Git blobs and emit a review draft; never invoke reconciliation or mutate Git.

--check recomputes every generated byte without writing anything.
"""
from pathlib import Path
import hashlib,json,re,subprocess,sys
sys.stdout.reconfigure(encoding='utf-8')
P=Path(__file__).resolve().parent; R=P.parents[4]
B='9e2225705fed906b1120d55105d607baabef57c9'
C='c4bfd6deb756ba46184c9418edc83bda33084719'
S='gates/leveque-finite-volume/artifacts/session-20260908/'
ROW='LEV-CH01-EQ-1.3-ADVECTED-PROFILE'
G='gates/leveque-finite-volume/chapter-01.json'
W=R.parent/'formalization-collaboration-v5.0.1'
M=W/'skills/book-formalization-migration'
BOOK=W/'books/candidates/leveque-finite-volume/module'
def sha(b):return hashlib.sha256(b).hexdigest()
def canonical(o):return json.dumps(o,sort_keys=True,separators=(',',':'),ensure_ascii=True).encode('utf-8')
def pretty(o):return (json.dumps(o,indent=2,ensure_ascii=True)+'\n').encode('utf-8')
def xp(p):return Path(chr(92)*2+'?'+chr(92)+str(Path(p).resolve()))
def git(*args):return subprocess.check_output(['git','-c','core.longpaths=true',*args],cwd=R)
def entries(ref):
 return {p.decode():h.decode().split()[2] for record in git('ls-tree','-r','-z',ref).split(b'\0') if record for h,p in [record.split(b'\t',1)]}
trees={ref:entries(ref) for ref in [B,C]}
cache={}
def blob(ref,p):
 oid=trees[ref][p]
 if oid not in cache:cache[oid]=git('cat-file','blob',oid)
 return cache[oid]
def obj(ref,p):return json.loads(blob(ref,p))
def record(ref,p):return {'commit':ref,'path':p,'git_blob_oid':trees[ref][p],'sha256':sha(blob(ref,p)),'bytes':len(blob(ref,p))}
def live_record(p):return {'path':str(p).replace(chr(92),'/'),'sha256':sha(xp(p).read_bytes()),'bytes':xp(p).stat().st_size}
out={}
def emit(name,value):out[name]=pretty(value)
gates={ref:obj(ref,G) for ref in [B,C]}
rows={ref:next(r for r in gates[ref]['rows'] if r['id']==ROW) for ref in [B,C]}
assert [r['id'] for r in gates[B]['rows'] if r['status']=='PROVED']==[ROW]
tasks={ref:obj(ref,rows[ref]['faithfulness_task']) for ref in [B,C]}
contracts={ref:obj(ref,'gates/leveque-finite-volume/'+rows[ref]['source_contract_artifact']) for ref in [B,C]}
assert all(rows[ref]['status']=='PROVED' for ref in [B,C])
fp_paths=[S+'baseline-equation03-expression-fingerprints.json',S+'chapter01-current-expression-fingerprints-3239.json']
fp_expected=['e29b3e71a3bffdba15b88e5e2ef5f45907e16aa982c40bb93da828c91aafd720','6ca24e74145d412e69237d0059c018cf12a1843f0d0609d0087638a51b5e233d']
fps={};records={}
for p,want in zip(fp_paths,fp_expected):
 assert sha(blob(C,p))==want
 f=obj(C,p);fps[p]=f
 for r in f['records']:
  if r['name'].startswith('NumStability.leveque01_equation03_'):
   assert r['name'] not in records
   records[r['name']]={**r,'fingerprint_artifact':record(C,p)}
oldname=tasks[B]['target']['declaration'];newname=tasks[C]['target']['declaration']
assert oldname=='NumStability.leveque01_equation03_advectedProfile'
assert newname=='NumStability.leveque01_equation03_solutionDomains'
assert rows[C]['lean_declarations']==[newname]
retained=[]
for name in rows[B]['lean_declarations']:
 r=records[name];owner=r['module'].replace('.','/')+'.lean'
 assert blob(B,owner)==blob(C,owner)
 f=fps[r['fingerprint_artifact']['path']]
 fs=next(x for x in f['files'] if x['path']==owner)
 assert fs['sha256']==sha(blob(B,owner))
 retained.append({'name':name,'canonical_module':r['module'],'canonical_owner':owner,
  'baseline_owner':record(B,owner),'checkpoint_owner':record(C,owner),'owner_bytes_identical':True,
  'compiled_fingerprint_source':r['fingerprint_artifact'],
  'type_sha256':r['type_sha256'],'proof_sha256':r['value_sha256'],
  'level_params':r['level_params'],'level_params_sha256':r['level_params_sha256'],
  'recursor_values_sha256':r['recursor_values_sha256'],
  'retention':'Declaration and original proof retained in the same canonical owner; not deleted or replaced by the new scalar certificate.'})
assert len(retained)==3
legacy=tasks[B]['target']['path'];canonical_old=records[oldname]['module'].replace('.','/')+'.lean'
assert blob(B,legacy)==blob(C,legacy)
assert 'import '+records[oldname]['module'] in blob(B,legacy).decode()
assert not re.search(r'^\s*(?:theorem|def|lemma|abbrev|structure)\s',blob(B,legacy).decode(),re.M)
newowner=records[newname]['module'].replace('.','/')+'.lean'
assert newowner==tasks[C]['target']['path'] and newowner not in trees[B]
assert sha(blob(C,newowner))==next(x['sha256'] for x in fps[fp_paths[1]]['files'] if x['path']==newowner)
emit('declaration-retention.json',{'baseline':B,'checkpoint':C,'retained':retained,
 'legacy_forwarding_path':{'baseline':record(B,legacy),'checkpoint':record(C,legacy),
 'actual_owner':canonical_old,'declares_target':False,'role':'Compatibility import only; the task target path is not the declaration owner.'},
 'new_owner':record(C,newowner),
 'limit':'Owner bytes and previously native-extracted alpha-canonical fingerprints are bound here. No new native compilation or candidate dependency replay is performed by this draft.'})
for label,ref in [('baseline',B),('checkpoint',C)]:
 emit(label+'-source-selection.json',{'gate':record(ref,G),'row':rows[ref],
  'task_artifact':record(ref,rows[ref]['faithfulness_task']),'task':tasks[ref],
  'source_contract_artifact':record(ref,'gates/leveque-finite-volume/'+rows[ref]['source_contract_artifact']),
  'source_contract':contracts[ref]})
userpath=S+'user-transport-interpretation-20260908.json'
assert sha(blob(C,userpath))=='26f16aeef42a0c7de4865c4c00e9ba223a9ae53604abf55da427171f6bf8e16b'
user=obj(C,userpath)
out['user-interpretation.exact.json']=blob(C,userpath)
profile=BOOK/'book-profile.json';profile_bytes=xp(profile).read_bytes()
assert sha(profile_bytes)==gates[C]['bindings']['module_profile_sha256']
out['current-book-profile.exact.json']=profile_bytes
policy_files=['scripts/gate.py','instructions.md','references/source-audit.md','references/source-faithfulness.md','references/verification.md','references/reporting.md']
policy_digest=hashlib.sha256();policy_records=[]
for p in policy_files:
 b=xp(BOOK/p).read_bytes();policy_digest.update(p.encode()+b'\0'+b+b'\0')
 policy_records.append(live_record(BOOK/p))
assert policy_digest.hexdigest()==gates[C]['bindings']['gate_policy_sha256']
emit('profile-and-policy-binding-evidence.json',{'current_profile':live_record(profile),
 'current_policy_files':policy_records,'current_policy_sha256':policy_digest.hexdigest(),
 'current_policy_hash_method':'Released gate.py gate_policy_sha256: ordered UTF-8 relative path, NUL, exact file bytes, NUL for the six listed files.',
 'baseline_recorded_bindings':{k:gates[B]['bindings'][k] for k in ['module_profile_sha256','gate_policy_sha256']},
 'checkpoint_recorded_bindings':{k:gates[C]['bindings'][k] for k in ['module_profile_sha256','gate_policy_sha256']},
 'historical_profile_and_policy_bytes_recovered':False,
 'interpretation_scope':'The user convention is a separate exact receipt. It does not replace, rewrite, or narrow the current book profile. Current actual profile bytes are independently frozen. Baseline and checkpoint recorded profile/policy digests differ; no cross-baseline byte equality or unexplained historical semantic equivalence is asserted.'})
policy_payloads={};producer_payloads={};controlled={}
for label,ref,name in [('old',B,oldname),('new',C,newname)]:
 r=records[name];source=tasks[ref]['source']
 policy_payloads[label]={
  'format':'equation03-policy-domain-v1','row':ROW,
  'source_document':{k:source[k] for k in ['sha256','version']},
  'source_locations':source['locations'],
  'row_source_locator':{k:rows[ref].get(k) for k in ['printed_page','pdf_page','source_label']},
  'source_contract':contracts[ref]['payload']['contract'],
  'recorded_book_bindings':{k:gates[ref]['bindings'][k] for k in ['module_profile_sha256','gate_policy_sha256']},
  'user_interpretation':({'sha256':sha(blob(C,userpath)),'receipt':user} if ref==C else None)}
 producer_payloads[label]={'format':'canonical-producer-identity-v1','module':r['module'],'declaration':name,
  'kind':r['kind'],'type_sha256':r['type_sha256'],'level_params_sha256':r['level_params_sha256']}
 controlled[label]={'source':source['sha256'],'type':r['type_sha256'],'policy':sha(canonical(policy_payloads[label])),
  'producer':sha(canonical(producer_payloads[label])),'proof':r['value_sha256']}
 emit(label+'-policy-domain.json',policy_payloads[label]);emit(label+'-producer-identity.json',producer_payloads[label])
assert controlled['old']['source']==controlled['new']['source']
assert all(controlled['old'][k]!=controlled['new'][k] for k in ['type','policy','producer','proof'])
transport={'id':'leveque-ch01-equation03-interpreted-producer','change_class':'producer',
 'old_module':records[oldname]['module'],'new_module':records[newname]['module'],
 'old_declaration':oldname,'new_declaration':newname,'old_hashes':controlled['old'],'new_hashes':controlled['new'],
 'faithfulness':'full-reaudit','affected_books':['leveque-finite-volume']}
schema=json.loads((M/'references/schemas/reconciliation-epoch.schema.json').read_bytes())
assert set(transport)==set(schema['$defs']['transport']['required'])
assert transport['change_class'] in schema['$defs']['transport']['properties']['change_class']['enum']
assert transport['faithfulness'] in schema['$defs']['transport']['properties']['faithfulness']['enum']
for side in ['old_hashes','new_hashes']:
 assert set(transport[side])==set(schema['$defs']['controlledHashes']['required'])
 assert all(re.fullmatch('[0-9a-f]{64}',v) for v in transport[side].values())
emit('transport-entry.draft.json',transport)
A=tasks[C]['audit_output']+'/'
manifest=obj(C,A+'manifest.json');decision=obj(C,A+'decision.json')
assert manifest['status']=='completed' and decision['accepted'] is True and decision['adjudicated'] is True
assert decision['classification']=='faithful-equivalent'
assert decision['judge_classifications']=={'direct':'faithful-equivalent','roundtrip':'undetermined'}
assert sha(blob(C,A+'decision.json'))=='7592cfc9bc82067b1f89c4fa3c040111ab8e34ee3eb3e6264cfa9d1b0dacf79c'
bindings=[]
groups={'inputs':list(manifest['inputs'].values()),'outputs':list(manifest['outputs'].values()),
 'target':[manifest['target']],'task_metadata':[manifest['task_metadata']],
 'source':[manifest['source']],'local_import_sources':manifest['local_import_sources'],
 'lean_environment':manifest['lean_environment'],'audit_setup':manifest['audit_setup']}
for group,items in groups.items():
 for item in items:
  p=item['path'];expected=item['sha256']
  if p in trees[C]:
   actual=sha(blob(C,p));status='git-blob-match' if actual==expected else 'git-blob-mismatch'
   assert actual==expected,(group,p,expected,actual)
   evidence=record(C,p)
  elif xp(R/p).is_file():
   evidence=live_record(R/p);actual=evidence['sha256']
   status='external-current-bytes-match' if actual==expected else 'external-current-bytes-mismatch'
  else:evidence={'path':p};actual=None;status='external-not-available'
  bindings.append({'group':group,'expected_sha256':expected,'actual_sha256':actual,'status':status,'evidence':evidence})
assert all(x['status'] in ['git-blob-match','external-current-bytes-match'] for x in bindings),[x for x in bindings if 'match' not in x['status'] or 'mismatch' in x['status']]
members=sorted(p for p in trees[C] if p.startswith(A))
inventory=[record(C,p) for p in members]
agent_runs=obj(C,A+'agent_outputs/agent_runs.json')['runs']
assert len(agent_runs)==5 and len({r['agent_id'] for r in agent_runs})==5
role_map={'s':'source-contract','b':'blind-translation','d':'direct-judge','r':'roundtrip-judge','a':'adjudicator'}
role_checks=[]
for letter,role in role_map.items():
 runtime=obj(C,A+'orchestration/'+letter+'_runtime.json')
 run=next(x for x in agent_runs if x['role']==role)
 assert runtime['agent_id']==run['agent_id'] and runtime['tool_calls']==0
 for key,suffix in [('events_sha256','_events.jsonl'),('stdin_sha256','_input.txt'),('raw_final_sha256','_final.json'),('transport_sha256','_transport.json')]:
  assert runtime[key]==sha(blob(C,A+'orchestration/'+letter+suffix))
 events=[json.loads(line) for line in blob(C,A+'orchestration/'+letter+'_events.jsonl').splitlines() if line.strip()]
 found=[]
 def tool_items(v):
  if isinstance(v,dict):
   if v.get('type') in {'function_call','custom_tool_call','command_execution','mcp_tool_call','web_search','file_change','collab_tool_call'}:found.append(v.get('type'))
   for q in v.values():tool_items(q)
  elif isinstance(v,list):
   for q in v:tool_items(q)
 tool_items(events);assert not found,(role,found)
 role_checks.append({'role':role,'agent_id':run['agent_id'],'model':run['model'],'reasoning_effort':run['reasoning_effort'],
  'recorded_runtime_tool_calls':runtime['tool_calls'],'tool_items_in_committed_cli_events':found,
  'runtime':record(C,A+'orchestration/'+letter+'_runtime.json'),
  'events':record(C,A+'orchestration/'+letter+'_events.jsonl'),
  'limit':'Checks the committed CLI events and frozen runtime receipt; does not claim a new role invocation or a fresh host-session inspection.'})
blind_packet=blob(C,A+'inputs/blind_review_packet.md');blind_stdin=blob(C,A+'orchestration/b_input.txt')
assert blind_stdin.count(blind_packet)==1
assert userpath.encode() not in blind_stdin and sha(blob(C,userpath)).encode() not in blind_stdin
oldroot=rows[B]['faithfulness_task'].rsplit('/',1)[0]+'/'
oldfiles=sorted(p for p in trees[B] if p.startswith(oldroot))
assert all(p in trees[C] for p in oldfiles)
changed_old=[p for p in oldfiles if blob(B,p)!=blob(C,p)]
assert sorted(p.removeprefix(oldroot) for p in changed_old)==['gate-blind.json','gate-direct.json','gate-round-trip.json','gate-source-contract.json']
projection_changes=[]
for p in changed_old:
 before=obj(B,p);after=obj(C,p)
 assert {k:v for k,v in before.items() if k!='bindings'}=={k:v for k,v in after.items() if k!='bindings'}
 changed_keys=[k for k in sorted(set(before['bindings'])|set(after['bindings'])) if before['bindings'].get(k)!=after['bindings'].get(k)]
 projection_changes.append({'baseline':record(B,p),'checkpoint':record(C,p),'nonbinding_payload_unchanged':True,
  'changed_bindings':{k:{'old':before['bindings'].get(k),'new':after['bindings'].get(k)} for k in changed_keys}})
 out['baseline-historical-'+p.rsplit('/',1)[1]]=blob(B,p)
emit('full-reaudit-evidence.json',{'checkpoint':C,'task':record(C,rows[C]['faithfulness_task']),
 'manifest':record(C,A+'manifest.json'),'decision':record(C,A+'decision.json'),'report':record(C,A+'report.md'),
 'recorded_decision':decision,'manifest_binding_checks':bindings,'role_checks':role_checks,
 'blind_packet_occurs_exactly_once_in_frozen_stdin':True,'blind_stdin_has_no_user_receipt_path_or_digest':True,
 'artifacts':inventory,'artifact_inventory_sha256':sha(canonical(inventory)),
 'prior_baseline_audit_retention':{'root':oldroot,'all_baseline_paths_retained':True,
 'raw_faithfulness_task_and_other_artifacts_byte_identical':True,
 'gate_projections_rebound':projection_changes,
 'note':'Four historical gate projections changed only their binding objects. Exact baseline projection bytes are copied into this draft; all baseline blobs remain identified by the pinned baseline commit. The whole historical directory is not claimed byte-identical.',
 'files':[{'baseline':record(B,p),'checkpoint':record(C,p),'byte_identical':blob(B,p)==blob(C,p)} for p in oldfiles]},
 'limit':'This is mechanical evidence review of a completed independent audit, not a new audit, released complete validation, pristine candidate replay, or epoch verdict. Original source ambiguity and original roundtrip undetermined remain part of the accepted qualified record.'})
preview=R/'.formalization/reconciliation/asset-inventories/checkpoint-c4bfd6de-preview.json'
assert sha(xp(preview).read_bytes())=='9a14b8d66b842520d0beeb4296d9cf89d8c61be83001b378b1194ffdca08379e'
pr=json.loads(xp(preview).read_bytes())
assert pr['head']==C and pr['anchor']==B
emit('draft-provenance.json',{'kind':'additive-baseline-equation03-transport-review-draft','baseline_commit':B,
 'checkpoint_commit':C,'baseline_tree':git('rev-parse',B+'^{tree}').decode().strip(),
 'checkpoint_tree':git('rev-parse',C+'^{tree}').decode().strip(),
 'candidate':None,'epoch':None,'acceptance_claimed':False,'protected_ref_changed':False,
 'released_inputs':[live_record(M/p) for p in ['references/reconciliation.md','scripts/reconciliation.py','references/schemas/reconciliation-epoch.schema.json']],
 'asset_preview':live_record(preview),'fingerprint_inputs':[record(C,p) for p in fp_paths],
 'fingerprint_normalization':[{'path':p,'normalization':fps[p]['normalization']} for p in fp_paths],
 'helper':live_record(Path(__file__)),
 'hash_conventions':{'composite':'SHA256 of json.dumps(sort_keys=True,separators=(comma,colon),ensure_ascii=True).encode(UTF-8), without trailing newline; pretty file bytes have separate artifact hashes.',
 'source':'Exact immutable PDF byte SHA256. Expanded source selection and actual contract are separately bound inside policy-domain payload, so unchanged PDF alone never establishes unchanged source claim.',
 'type':'Existing native-extracted alpha-canonical expression SHA256, used exactly as emitted; not a hash of printed Lean text or a claim of full definitional normalization.',
 'policy':'Digest of exact semantic contract object, source version/locations/row locator, historical or current profile and gate-policy bindings, and separately recorded complete user interpretation. Excludes mutable gate epoch/tree/rebinding coordinates; exact original artifact blobs remain in source-selection evidence.',
 'producer':'Digest of actual canonical module/declaration/kind/type/universe-parameter fingerprints. Proof bytes and the legacy forwarding path are not part of producer identity; both remain separately bound.',
 'proof':'Existing native-extracted alpha-canonical proof expression SHA256; owner exact bytes and original proof retention checked independently.'},
 'required_next_owner_work':['Review and adopt or revise the explicit fingerprint convention consistently in final candidate assets/transports.',
 'Bind the actual candidate and affected-book verdict; rerun required source/import/signature/body/declaration/build checks in pristine replay.',
 'Resolve historical profile/policy provenance if any final claim depends on historical byte equality. This draft deliberately makes no such claim.',
 'Use the external exact-candidate authority route for any epoch/admission/protected-ref action.'],
 'read_only_local_checks':{'actual_git_blob_binding':True,'three_baseline_owners_byte_identical':True,
 'producer_and_type_and_policy_changed':True,'transport_schema_field_shape_checked':True,
 'released_semantic_transport_rule_satisfied_in_draft':True,'fresh_pristine_replay_performed':False}})
check='--check' in sys.argv
for name,data in out.items():
 dest=xp(P/name)
 if check:assert dest.read_bytes()==data,('Generated artifact drift',name)
 elif dest.exists():assert dest.read_bytes()==data,('Refusing overwrite',name)
 else:dest.write_bytes(data)
print(json.dumps({'mode':'read-only-recompute' if check else 'freeze-draft','baseline':B,'checkpoint':C,
 'artifacts':[{'path':name,'sha256':sha(data),'bytes':len(data)} for name,data in out.items()],
 'retained_declarations':len(retained),'bound_manifest_entries':len(bindings),'fresh_role_records':len(role_checks),
 'old_hashes':controlled['old'],'new_hashes':controlled['new'],
 'candidate_or_epoch_acceptance':False},indent=2))
