import Mathlib.Data.Complex.Basic
import ComputationalMathematics.Algorithms.Cholesky.CholeskyDemmel
import ComputationalMathematics.Algorithms.Cholesky.CholeskyFl
import ComputationalMathematics.Algorithms.Cholesky.CholeskyNonsym
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.LinearAlgebra.Matrix.Block
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.LinearAlgebra.Matrix.Rank
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.Cholesky.CholeskySpec
import ComputationalMathematics.Algorithms.LU.GaussianElimination
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.PositiveSemidefinite.Basic
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.PositiveSemidefinite.PivotedFactorization.Existence
import ComputationalMathematics.Analysis.Rounding
import ComputationalMathematics.FloatingPoint.Model
import ComputationalMathematics.Source.Higham.Chapter10.Lemma13.KahanSharpness.CompletePivotingBound
import ComputationalMathematics.Source.Higham.Chapter10.Problem01.PositiveSemidefiniteEntries.EntryBounds.Results
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.ConstructiveFactorization.Existence
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.Existence
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.QuadraticFormBounds.WeightedNorm
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.SchurComplement
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.Termination
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.TrailingTermination.Bound
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.WNormBound
import ComputationalMathematics.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.PsdErrorAnalysis
import ComputationalMathematics.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.RoundedErrorAnalysis.Bounds
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.ErrorAnalysis.Certificates
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.ErrorAnalysis.PositivePivots.Certificate
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.Perturbation.Basic
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.PositiveSemidefinite.KahanMatrix
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.PositiveSemidefinite.KahanTelescope.Identity
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.PositiveSemidefinite.ScaledStage
import ComputationalMathematics.Algorithms.LinearSystems.Cholesky.PositiveSemidefinite.StageEmbedding.InteriorMass
import ComputationalMathematics.Analysis.MatrixNorms.EntrywiseAbsolute.Basic
import ComputationalMathematics.Analysis.MatrixNorms.SpectralExtrema.Basic
import ComputationalMathematics.Analysis.MatrixNorms.SpectralExtrema.PrincipalSubmatrices.Bounds
import ComputationalMathematics.Analysis.MatrixSpectral
import ComputationalMathematics.Source.Higham.Chapter09.Problems
import ComputationalMathematics.Source.Higham.Chapter09.Section01
import ComputationalMathematics.Source.Higham.Chapter09.Section02
import ComputationalMathematics.Source.Higham.Chapter09.Section03
import ComputationalMathematics.Source.Higham.Chapter09.Section04
import ComputationalMathematics.Source.Higham.Chapter09.Section05
import ComputationalMathematics.Source.Higham.Chapter09.Section06
import ComputationalMathematics.Source.Higham.Chapter09.Section08
import ComputationalMathematics.Source.Higham.Chapter09.Section10
import ComputationalMathematics.Source.Higham.Chapter09.Section11
import ComputationalMathematics.Source.Higham.Chapter10.Equation07.AbsoluteFactorNorm.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Equation29.Mathias.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Equation30.ComplexPositiveDefinite.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Lemma11.PivotSequenceStability.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Lemma13.KahanSharpness.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Lemma13.KahanSharpness.UnboundedGrowth.Construction
import ComputationalMathematics.Source.Higham.Chapter10.Problem01.PositiveSemidefiniteEntries.Basic
import ComputationalMathematics.Source.Higham.Chapter10.Problem04.UnpivotedGrowth.Basic
import ComputationalMathematics.Source.Higham.Chapter10.Problem04.UnpivotedGrowth.PositivePivots.Bounds
import ComputationalMathematics.Source.Higham.Chapter10.Problem08.LeadingMinorsCounterexample.Basic
import ComputationalMathematics.Source.Higham.Chapter10.Section01.Factorization.Basic
import ComputationalMathematics.Source.Higham.Chapter10.Section01.Factorization.ExistenceUniqueness.Results
import ComputationalMathematics.Source.Higham.Chapter10.Section02.ErrorAnalysis.Basic
import ComputationalMathematics.Source.Higham.Chapter10.Section02.ErrorAnalysis.FactorizationAndSolve.Bounds
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Section03.PositiveSemidefinite.PivotingAndScaling.Results
import ComputationalMathematics.Source.Higham.Chapter10.Section04.PositiveDefiniteSymmetricPart.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Section04.PositiveDefiniteSymmetricPart.SchurStages.Bounds
import ComputationalMathematics.Source.Higham.Chapter10.Theorem06.RoundedCholesky.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Theorem07.FailureVacuity.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Theorem07.SuccessThreshold.Factorization
import ComputationalMathematics.Source.Higham.Chapter10.Theorem08.ComponentwisePerturbation.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Theorem08.NormwiseDiscrepancy.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.Endpoints
import ComputationalMathematics.Source.Higham.Chapter10.Theorem14.CompletePivotedPSD.SuccessfulRun.StageBounds
import ComputationalMathematics.Source.Higham.Chapter10.Theorem08.NormwiseDiscrepancy.Counterexample.Uniqueness
import ComputationalMathematics.Source.Higham.Chapter10.Theorem08.NormwiseDiscrepancy.LiteralSource

/-!
# Ch10Theorem108Source (compatibility module)

Import-only module retained so existing imports of `NumStability.Algorithms.Ch10Theorem108Source` keep
resolving. Every declaration moved unchanged to the routed canonical
destination(s). The module's own original imports are re-stated so
consumers reaching an identifier transitively through this path still
see the same surface.
-/
