import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.DotProduct
import ComputationalMathematics.Algorithms.LinearSystems.Triangular.ForwardSubstitution
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.LinearAlgebra.Matrix.Orthogonal
import Mathlib.Tactic.FieldSimp
import ComputationalMathematics.Algorithms.LinearSystems.Triangular.BackSubstitution
import ComputationalMathematics.Algorithms.LU.GaussianElimination
import ComputationalMathematics.Algorithms.LU.GrowthFactor
import ComputationalMathematics.Algorithms.LU.LUSolve
import ComputationalMathematics.Algorithms.MatMul
import ComputationalMathematics.Algorithms.MatrixInversion.LUFactors.ErrorAnalysis.MatrixInversion
import ComputationalMathematics.Algorithms.MatrixInversion.LUFactors.Methods.MatrixInversion
import ComputationalMathematics.Algorithms.MatrixInversion.Residuals.MatrixInversion
import ComputationalMathematics.Algorithms.MatrixInversion.Triangular.ErrorAnalysis.MatrixInversion
import ComputationalMathematics.Algorithms.MatrixInversion.Triangular.Specifications.MatrixInversion
import ComputationalMathematics.Algorithms.MatVec
import ComputationalMathematics.Algorithms.TestMatrices.UpperTriangularStress
import ComputationalMathematics.Analysis.Error.MatrixProducts.Contracts.MatrixInversion
import ComputationalMathematics.Analysis.Error.RoundingProducts.Core
import ComputationalMathematics.Analysis.ForwardError
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.MatrixNorms.HadamardDeterminant
import ComputationalMathematics.Analysis.Perturbation.LeastSquares.Wedin
import ComputationalMathematics.Analysis.Rounding
import ComputationalMathematics.FloatingPoint.Model
import ComputationalMathematics.Source.Higham.Chapter14.Equation34.DeterminantFromLU.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Equation35.HymanBlockFactorization.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Equation36.HymanDeterminant.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem03.ResidualComparison.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem04.ResidualCounterexample.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem05.InverseBasedSolve.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem07.OnesVector.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem08.ComplexInverseRealBlock.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem10.EntryPerturbation.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem11.HadamardCondition.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem12.ConditionNumberExamples.StressAndPeiMatrices
import ComputationalMathematics.Source.Higham.Chapter14.Problem12.HadamardExamples.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem13.GEJBound.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem14.HymanDeterminant.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem15.DeterminantPerturbation.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Section01.InverseErrorAnalysis.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Section02.TriangularInversion.Method2B.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Section03.LUFactorInversion.MethodD.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Section02.TriangularInversion.Method1B.BlockTriInverse

import ComputationalMathematics.Source.Higham.Chapter14.Section02.TriangularInversion.Method1B.BlockResidual.WholeMatrixBounds
import ComputationalMathematics.Source.Higham.Chapter14.Section02.TriangularInversion.Method1B.Method1BWhole

/-!
# Ch14Method1BWhole (compatibility module)

Import-only module retained so existing imports of `NumStability.Algorithms.Ch14Method1BWhole` keep
resolving. Every declaration moved unchanged to `NumStability.Source.Higham.Chapter14.Section02.TriangularInversion.Method1B.BlockResidual.WholeMatrixBounds`.
The module's own original imports are re-stated so consumers reaching an
identifier transitively through this path still see the same surface.
-/
