import ComputationalMathematics.Algorithms.DotProduct
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.LinearSystems.GaussJordan.ErrorAnalysis.GaussJordan
import ComputationalMathematics.Algorithms.LU.GaussianElimination
import ComputationalMathematics.Analysis.ForwardError
import ComputationalMathematics.Analysis.Rounding
import ComputationalMathematics.FloatingPoint.Model
import ComputationalMathematics.Source.Higham.Chapter09.Problems
import ComputationalMathematics.Source.Higham.Chapter09.Section01
import ComputationalMathematics.Source.Higham.Chapter09.Section02
import ComputationalMathematics.Source.Higham.Chapter09.Section03
import ComputationalMathematics.Source.Higham.Chapter09.Section04
import ComputationalMathematics.Source.Higham.Chapter09.Section05
import ComputationalMathematics.Source.Higham.Chapter09.Section06
import ComputationalMathematics.Source.Higham.Chapter09.Section08
import ComputationalMathematics.Source.Higham.Chapter09.Section10
import ComputationalMathematics.Source.Higham.Chapter09.Section11
import ComputationalMathematics.Source.Higham.Chapter14.Corollary07.RowDominantCertificates.CumulativeProductBounds
import Mathlib.LinearAlgebra.Matrix.Orthogonal
import ComputationalMathematics.Algorithms.LinearSystems.Triangular.BackSubstitution
import ComputationalMathematics.Algorithms.LinearSystems.Triangular.ForwardSubstitution
import ComputationalMathematics.Algorithms.LU.GrowthFactor
import ComputationalMathematics.Algorithms.LU.LUSolve
import ComputationalMathematics.Algorithms.MatMul
import ComputationalMathematics.Algorithms.MatrixInversion.LUFactors.ErrorAnalysis.MatrixInversion
import ComputationalMathematics.Algorithms.MatrixInversion.LUFactors.Methods.MatrixInversion
import ComputationalMathematics.Algorithms.MatrixInversion.Residuals.MatrixInversion
import ComputationalMathematics.Algorithms.MatrixInversion.Triangular.ErrorAnalysis.MatrixInversion
import ComputationalMathematics.Algorithms.MatrixInversion.Triangular.Specifications.MatrixInversion
import ComputationalMathematics.Algorithms.MatVec
import ComputationalMathematics.Algorithms.TestMatrices.UpperTriangularStress
import ComputationalMathematics.Analysis.Error.MatrixProducts.Contracts.MatrixInversion
import ComputationalMathematics.Analysis.Error.RoundingProducts.Core
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.MatrixNorms.HadamardDeterminant
import ComputationalMathematics.Analysis.Perturbation.LeastSquares.Wedin
import ComputationalMathematics.Source.Higham.Chapter14.Equation34.DeterminantFromLU.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Equation35.HymanBlockFactorization.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Equation36.HymanDeterminant.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem03.ResidualComparison.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem04.ResidualCounterexample.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem05.InverseBasedSolve.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem07.OnesVector.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem08.ComplexInverseRealBlock.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem10.EntryPerturbation.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem11.HadamardCondition.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem12.ConditionNumberExamples.StressAndPeiMatrices
import ComputationalMathematics.Source.Higham.Chapter14.Problem12.HadamardExamples.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem13.GEJBound.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem14.HymanDeterminant.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Problem15.DeterminantPerturbation.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Section01.InverseErrorAnalysis.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Section02.TriangularInversion.Method2B.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Section03.LUFactorInversion.MethodD.MatrixInversion
import ComputationalMathematics.Source.Higham.Chapter14.Section02.TriangularInversion.Method2.Method2Loop





import ComputationalMathematics.Source.Higham.Chapter14.Section03.LUFactorInversion.MethodD.MethodDLeftResidual

/-!
# Ch14MethodDLeftResidual (compatibility module)

Import-only module retained so existing imports of `NumStability.Algorithms.Ch14MethodDLeftResidual`
keep resolving. Every declaration moved unchanged to the canonical
modules imported above. The module's own original imports are
re-stated so consumers reaching an identifier transitively through
this path still see the same surface.
-/
