import Mathlib.Analysis.Calculus.FDeriv.Comp
import Mathlib.Analysis.Normed.Algebra.GelfandFormula
import Mathlib.Analysis.Seminorm
import Mathlib.Analysis.Calculus.FDeriv.Basic
import Mathlib.LinearAlgebra.Matrix.Irreducible.Defs
import Mathlib.Topology.MetricSpace.Contracting
import Mathlib.Topology.Order.Compact
import Mathlib.Order.Fin.Basic
import Mathlib.Topology.MetricSpace.ProperSpace
import Mathlib.Topology.Order.MonotoneConvergence
import Mathlib.Topology.Sequences
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Convergence.ConvergenceStatements
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Duality.ConvergenceStatements
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Analysis.Calculus.Deriv.Add
import Mathlib.Analysis.Calculus.LocalExtr.Basic
import Mathlib.Analysis.InnerProductSpace.NormPow
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import ComputationalMathematics.Algorithms.LU.GrowthFactor
import ComputationalMathematics.Algorithms.NormEstimation.OneNorm.FiniteIndex.Basic
import ComputationalMathematics.Algorithms.NormEstimation.OneNorm.PowerMethod.CondEstimation
import ComputationalMathematics.Algorithms.NormEstimation.OneNorm.PowerMethod.PNormPowerMethod
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.OneAndInfinityNorms.Square
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.PowerMethod.PNormPowerMethod
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.MatrixNorms.Lp
import ComputationalMathematics.Analysis.SingularValues.Realification
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.PNormGeneral
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Duality.PNormGeneral
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.PowerMethod.PNormGeneral
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Rectangular.PNormGeneral
import ComputationalMathematics.Algorithms.CondEstimation
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Duality.PNormPowerMethod
import ComputationalMathematics.Source.Higham.Chapter15.Algorithm01.PNormPowerMethod.PNormPowerMethod
import ComputationalMathematics.Source.Higham.Chapter15.Equation02.Subgradient.PNormPowerMethod
import ComputationalMathematics.Source.Higham.Chapter15.Equation03.GradientQuotient.PNormPowerMethod
import ComputationalMathematics.Source.Higham.Chapter15.Equation04.NormalizedDualDiscrepancy.Basic
import ComputationalMathematics.Source.Higham.Chapter15.Equation05.SubgradientInequality.Basic
import ComputationalMathematics.Source.Higham.Chapter15.Lemma02.PNormPowerMethod.PNormPowerMethod
import ComputationalMathematics.Source.Higham.Chapter15.Equation02.Subgradient.PNormGeneral
import ComputationalMathematics.Source.Higham.Chapter15.Equation03.GradientQuotient.PNormGeneral
import ComputationalMathematics.Source.Higham.Chapter15.Algorithm01.PNormPowerMethod.ConvergenceStatements
import ComputationalMathematics.Source.Higham.Chapter15.Equation03.GradientQuotient.ConvergenceStatements
import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.Corrections.ConvergenceStatements
import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.EndpointTermination.ConvergenceStatements
import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.GlobalConvergence.ConvergenceStatements
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Carrier.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.Differentiation.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.FixedPoints.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.LocalStability.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Convergence.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Duality.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.PowerMethod.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Rectangular.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.OneAndInfinityNorms.Rectangular
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Rectangular.PNormRectangular
import ComputationalMathematics.Source.Higham.Chapter15.Algorithm01.PNormPowerMethod.PNormRectangular
import ComputationalMathematics.Source.Higham.Chapter15.Lemma02.PNormPowerMethod.PNormRectangular
import ComputationalMathematics.Source.Higham.Chapter15.Lemma02.PNormPowerMethod.BoydInterface
import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.GlobalConvergence.BoydInterface
import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.LocalConvergence.BoydInterface
import ComputationalMathematics.Algorithms.NormEstimation.PNorm.Boyd.LocalStability.BoydLocalStability
import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.Corrections.BoydLocalStability
import ComputationalMathematics.Source.Higham.Chapter15.Section02.Boyd.LocalConvergence.BoydLocalStability

/-!
# HighamChapter15BoydLocalStability (compatibility wrapper)

Declaration-free reviewed owner. Its imports are normalized to the exact
canonical and source targets that now hold the material it used to reach
through historical paths, and the historical path itself is retained so
existing imports of `NumStability.Algorithms.HighamChapter15BoydLocalStability` keep resolving. This module declares nothing.
-/
