import ComputationalMathematics.Source.Vershynin.Chapter01.BernoulliAndBinomial.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.CauchySchwarz.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.CDFAndTail.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.ConvergenceInDistribution.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.ConvexFunction.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.DistributionDetermined.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Equation02.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Equation03.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Equation04.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Equation05.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Equation07.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.ExpectationAndVariance.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.HolderInequality.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Indicator.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.JensenInequality.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.L2Geometry.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.LayerCakePointwise.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.LpBanachSpace.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.LpNormedSpace.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.LpQuasinorm.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.LpSpace.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.MinkowskiInequality.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.MomentGeneratingFunction.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Moments.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.PoissonDistribution.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.SampleMeanVarianceLimit.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section01.Remark01.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Corollary05.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Exercise02.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Exercise03.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Exercise06.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Lemma01.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Lemma01.Fubini.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Lemma01.IndicatorExpectation.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Proposition04.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section02.Proposition04.Decomposition.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section03.Exercise03.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section03.Theorem01.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section03.Theorem02.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.Section03.Theorem04.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.StandardDeviationAndCovariance.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.StandardizedSum.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.StandardNormal.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.TailCDFIdentity.Contract
import ComputationalMathematics.Source.Vershynin.Chapter01.VarianceOfSum.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Equation12.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Equation18.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.ErdosRenyiModel.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.ExponentialMarkov.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.IndependentSumMGF.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.PsiTwoNormCharacterizations.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section02.Definition01.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section02.Exercise10B.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section02.Theorem06.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section03.Exercise05.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section05.Definition06.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section05.Example08B.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section05.Example08C.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section05.Exercise01.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section05.Proposition02.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section05.Remark03.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section06.Lemma08.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section06.Proposition01.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section06.Theorem02.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section06.Theorem03.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section07.Example12.Contract
import ComputationalMathematics.Source.Vershynin.Chapter02.Section07.Example13.Contract
import ComputationalMathematics.Source.Vershynin.Chapter05.Section01.Exercise13.Contract
import ComputationalMathematics.Source.Vershynin.Chapter05.Section01.Exercise14.Contract
import ComputationalMathematics.Source.Vershynin.Chapter05.Section02.Exercise11.Contract

/-!
# HDP source contracts

Historical family entry point for the stable, source-numbered HDP contracts.
Canonical declarations live in the Vershynin source hierarchy; the legacy leaf
paths remain available as import-only compatibility wrappers.
-/
