import ComputationalMathematics.Analysis.CStarMatrices.Expectation.Finite
import Mathlib.Analysis.SpecialFunctions.ContinuousFunctionalCalculus.ExpLog.Basic
import ComputationalMathematics.Analysis.CStarMatrices.Trace.Basic
import ComputationalMathematics.Analysis.MatrixSpectral
import Mathlib.Analysis.CStarAlgebra.CStarMatrix
import Mathlib.Analysis.CStarAlgebra.Classes
import Mathlib.Analysis.SpecialFunctions.ContinuousFunctionalCalculus.ExpLog.Order
import Mathlib.Topology.Instances.Matrix
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Order
import Mathlib.Analysis.Matrix.Order
import Mathlib.Data.Matrix.Block
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.BlockDiagonal
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.BlockDiagonalCompression
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPair
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairPinching
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeProjection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ColumnPairRangeReflection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteDimensional
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteMatrixOrder
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealEmbedding
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.FiniteRealOrder
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ProjectionReflection
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.RectangularCompression
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.RectangularMultiplication
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.ReflectionAverage
import ComputationalMathematics.Analysis.CStarMatrices.FiniteMatrixAlgebra.StrictPositivity
import ComputationalMathematics.Analysis.FunctionalCalculus.OperatorLog.Monotonicity
import ComputationalMathematics.Analysis.FiniteProbability

/-!
# Analysis.CStarMatrixExpectation

Historical import-only compatibility facade for the W06 semantic modules.
-/
