import Mathlib.MeasureTheory.Integral.CircleIntegral
import ComputationalMathematics.Analysis.FunctionalCalculus.Resolvent.DunfordResidue
import Mathlib.Analysis.Calculus.FDeriv.Mul
import Mathlib.Analysis.Complex.CauchyIntegral
import Mathlib.Analysis.Normed.Algebra.GelfandFormula
import ComputationalMathematics.Analysis.FunctionalCalculus.Resolvent.Analyticity
import Mathlib.Analysis.Normed.Algebra.Spectrum
import Mathlib.Analysis.SpecificLimits.Normed
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Tactic.FieldSimp
import ComputationalMathematics.Algorithms.MatVec
import ComputationalMathematics.Algorithms.MatrixPowers.ComputedIteration.Model
import ComputationalMathematics.Algorithms.PolynomialEvaluation.MatrixNorms
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.ExactNormBounds.Real
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.JordanScaling.RealDiagonal
import ComputationalMathematics.Analysis.MatrixAlgebra
import ComputationalMathematics.Analysis.Rounding
import ComputationalMathematics.Source.Higham.Chapter18.Section01.MatrixPowerBounds.Equations04And05.RealDiagonal
import ComputationalMathematics.Source.Higham.Chapter18.Section02.FinitePrecisionPowers.Equations08To14.ComputedIteration
import ComputationalMathematics.Source.Higham.Chapter18.Section02.FinitePrecisionPowers.Theorems01And02.RealCases
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.JordanScaling.RealJordan
import ComputationalMathematics.Source.Higham.Chapter18.Section01.MatrixPowerBounds.Equations04And05.RealJordan
import ComputationalMathematics.Source.Higham.Chapter18.Section02.FinitePrecisionPowers.Theorems01And02.RealJordan
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.ExactNormBounds.Complex
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.JordanScaling.Complex
import ComputationalMathematics.Analysis.MatrixNorms.Basic
import ComputationalMathematics.Source.Higham.Chapter18.Section02.FinitePrecisionPowers.Equations08To14.ComplexSimilarity
import ComputationalMathematics.Source.Higham.Chapter18.Section02.FinitePrecisionPowers.Theorems01And02.ComplexJordan
import ComputationalMathematics.Analysis.LinearOperators.Pseudospectra.Perturbation.Definitions
import ComputationalMathematics.Analysis.MatrixNorms.SpectralRadius
import ComputationalMathematics.Source.Higham.Chapter18.Section02.FinitePrecisionPowers.Theorems01And02.PseudospectralPackaging
import ComputationalMathematics.Analysis.LinearOperators.Pseudospectra.Perturbation.ConvergenceCriterion
import ComputationalMathematics.Source.Higham.Chapter18.Section02.FinitePrecisionPowers.Theorems01And02.PseudospectralCriterion
import ComputationalMathematics.Analysis.LinearOperators.Pseudospectra.Resolvent.LowerBounds

/-!
# Analysis.DunfordResidue

Historical import-only compatibility facade for the W06 semantic modules.
-/
