import ComputationalMathematics.Analysis.Error.Measures.AccuracyPrecision
import ComputationalMathematics.Analysis.Error.Measures.Componentwise
import ComputationalMathematics.Analysis.Error.Measures.ScalarDefinitions
import ComputationalMathematics.Analysis.Error.Measures.ScalarProperties
import ComputationalMathematics.Analysis.Error.Measures.ScalarWitnesses
import ComputationalMathematics.Analysis.FloatingPointArithmetic.ErrorModels.Additive
import ComputationalMathematics.Analysis.FloatingPointArithmetic.ErrorModels.AdditiveProperties
import ComputationalMathematics.Analysis.FloatingPointArithmetic.ErrorModels.NoGuardBasic
import ComputationalMathematics.Analysis.FloatingPointArithmetic.ErrorModels.NoGuardModel
import ComputationalMathematics.Source.Higham.Chapter01.Problem01.RelativeError.Bounds
import ComputationalMathematics.Source.Higham.Chapter01.Section03.ErrorSources.Core
import ComputationalMathematics.Source.Higham.Chapter01.Section07.Cancellation.Basic
import ComputationalMathematics.Source.Higham.Chapter02.Section04.NoGuardModel.BinaryT3Example

/-!
# Analysis.Error compatibility facade

W02 semantic entry point generated from the reviewed B0002 routing contract.
-/
