-- NumStability/Analysis/HighamChapter7.lean
--
-- Import-only compatibility wrapper retained by reorganization wave R03
-- (phase branch B0005, projection P0005). This historical path is preserved,
-- not deleted and not Git-renamed, so every existing `import` keeps resolving.
-- All of its declarations moved unchanged to the canonical module(s) below.

import Mathlib.Algebra.Order.GroupWithZero.Finset
import Mathlib.LinearAlgebra.Basis.VectorSpace
import Mathlib.LinearAlgebra.Charpoly.ToMatrix
import Mathlib.LinearAlgebra.Eigenspace.Charpoly
import Mathlib.LinearAlgebra.Finsupp.Pi
import Mathlib.LinearAlgebra.Matrix.FiniteDimensional
import Mathlib.LinearAlgebra.Matrix.Irreducible.Defs
import ComputationalMathematics.Algorithms.CondEstimation
import ComputationalMathematics.Analysis.Asymptotics.Bounds
import ComputationalMathematics.Analysis.Conditioning.DistanceToSingularity
import ComputationalMathematics.Analysis.Conditioning.LinearSystems.InversePerturbation
import ComputationalMathematics.Analysis.Conditioning.LinearSystems.PerronFrobenius
import ComputationalMathematics.Analysis.Conditioning.LinearSystems.SubordinatePerturbation
import ComputationalMathematics.Analysis.MatrixNorms.SpectralRadius
import ComputationalMathematics.Analysis.PerturbationTheory
import ComputationalMathematics.Analysis.Summation.Signs
import ComputationalMathematics.Source.Higham.Chapter06.Problem05
import ComputationalMathematics.Source.Higham.Chapter07.Corollary06.LinearSystemsConditioning.Basic
import ComputationalMathematics.Source.Higham.Chapter07.Corollary06.LinearSystemsConditioning.Results
import ComputationalMathematics.Source.Higham.Chapter07.Equation17.KahanConditioningExample
import ComputationalMathematics.Source.Higham.Chapter07.Equation25.InverseConditioning.ExactPerturbation
import ComputationalMathematics.Source.Higham.Chapter07.Equation26.DistanceToSingularity.Results
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.ComputedResidual
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.ConditionNumbers
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Equation05
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Equation32
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Equation33
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.ForwardErrorKernels
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Lemma09
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem01
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem02
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem04
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem05
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem06Columnwise
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem06Rowwise
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem07
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem08RectangularBackwardError
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem09Exact
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem09Linearized
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem10Bauer.Part01
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem10Bauer.Part02
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem10Bauer.Part03
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem10OneNorm
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem13SparseResidual
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Problem15Hadamard
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.RowScaling
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem02
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem04
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem05.Part01
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem05.Part02
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem05.Part03
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem05.Part04
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem05.Part05
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem05.Part06
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem05.RowInfinityScaleCounterexample.Theorems
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem07FrobeniusScaling
import ComputationalMathematics.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem08Aliases

/-!
# HighamChapter7 (compatibility wrapper)

Declaration-free import-only wrapper. Canonical module(s):

* `NumStability.Source.Higham.Chapter07.Equation17.KahanConditioningExample`
* `NumStability.Source.Higham.Chapter07.LinearSystemsConditioning.Theorem05.RowInfinityScaleCounterexample.Theorems`

Retained by wave R03 so historical imports continue to resolve unchanged.
-/
