import Mathlib.Algebra.Order.BigOperators.Ring.Finset
import Mathlib.Data.Complex.BigOperators
import Mathlib.Data.Real.Sqrt
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Henrici.Extremal
import Mathlib.Data.Complex.Basic
import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic
import Mathlib.LinearAlgebra.Matrix.Trace
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Henrici.DepartureFromNormality
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Laszlo.NearestNormal
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Henrici.NormalMatrices
import Mathlib.Analysis.CStarAlgebra.Matrix
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.ExactNormBounds.Schur
import ComputationalMathematics.Analysis.LinearOperators.Schur.Complex.Triangulation
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.ExactNormBounds.NormalMatrices.Powers
import ComputationalMathematics.Analysis.LinearOperators.MatrixPowers.Henrici.NormalCharacterization.Schur
import ComputationalMathematics.Analysis.LinearOperators.Schur.Complex.NormalTriangular.Diagonal
import ComputationalMathematics.Source.Higham.Chapter18.Section01.MatrixPowerBounds.NamedBounds.Laszlo

/-!
# Analysis.MatrixPowersLaszlo

Historical import-only compatibility facade for the W06 semantic modules.
-/
