import ComputationalMathematics.Algorithms.LinearSystems.Iterative.Stationary.Semiconvergence.BlockForm.Existence
import ComputationalMathematics.Algorithms.LinearSystems.Iterative.Stationary.Semiconvergence.BlockForm.ProjectorLimit
import ComputationalMathematics.Algorithms.LinearSystems.Iterative.Stationary.Semiconvergence.Execution.RoundedCertificates
import ComputationalMathematics.Algorithms.LinearSystems.Iterative.Stationary.Semiconvergence.Projectors.FixedRange

/-!
# Stationary-iteration semiconvergence

Declaration-free reusable aggregate for the stationary-iteration
semiconvergence family.
-/
